### ISSUE TITLE
project cannot run in my pc

### ISSUE THREAD

**Issue by CurrrryChen** [didi/mand-mobile#10]

**Comment by moyus** [comment]
Could you give more details?

**Comment by CurrrryChen** [comment]
Does the project require the Python env ? I tried npm install window pc, but all failed. And in Mac, it also failed when I run the commend "npm run dev". Error is as the picture shows: 
<img width="1065" alt="2018-04-12 5 40 37" src="https://user-images.githubusercontent.com/23257507/38669425-e9c3bc5e-3e78-11e8-8d69-9a7782032471.png">

**Comment by lucker2046** [comment]
@CurrrryChen , I add a pull request and try to fix it, could you please help me to validate it？ I'm unable to recurring this problem in my local environment.
https://github.com/didi/mand-mobile/pull/15

**Comment by CurrrryChen** [comment]
I got the latest code and tried once more, but sadly the same erorr occured. And I tried in my colleague`s mac, also failed because of the same error. Pics attached for your reference.

<img width="1169" alt="2018-04-13 2 10 59" src="https://user-images.githubusercontent.com/23257507/38719951-0836e392-3f27-11e8-8f80-a9bb24d44ba7.png">
![2018-04-13 2 20 51](https://user-images.githubusercontent.com/23257507/38719980-0fc5a170-3f27-11e8-91f3-27878c416938.png)

**Comment by CurrrryChen** [comment]
I got the same error, and I tried in my colleage`s mac, also failed.
<img width="1164" alt="2018-04-13 2 40 30" src="https://user-images.githubusercontent.com/23257507/38720424-d0c752a0-3f28-11e8-89d6-251892ef0e4d.png">

**Comment by lucker2046** [comment]
In the beginning，I add a rollup plugin name is `rollup-plugin-commonjs` to avoid this problem, but it seems dosen't work in your computer. could you tell me the real version of this package in your project, and what's your npm version and node version? @CurrrryChen 
![image](https://user-images.githubusercontent.com/12725583/38723929-3b1d2e02-3f35-11e8-9f05-95c00c2262ba.png)

**Comment by CurrrryChen** [comment]
I tried both the master code and branch 'fix_issue_#1' code in my mac and my colleage`s mac, and all failed because of the same error.
Mine:
node version: v8.6.0
npm version: 5.6.0

My colleage`s:
node version: v8.9.4
npm version: 5.6.0

**Comment by lucker2046** [comment]
@CurrrryChen 
I guess you install dependences with `cnpm`, and `cnpm install ` is difference with `yarn` or `npm`,
I fix it,  it's ok now
https://github.com/didi/mand-mobile/pull/18
https://github.com/cnpm/npminstall
