### ISSUE TITLE
快速上手文档 .babelrc 的配置有错误

### ISSUE THREAD

**Issue by shoyuf** [didi/mand-mobile#100]
https://didi.github.io/mand-mobile/#/docs/started
.babelrc的配置
文档的写法会直接报错吧？

- **Expectant Behaviors**

```js
{
"plugins": [
    "transform-vue-jsx",
    "transform-runtime", [
      "import",
      {
        "libraryName": "mand-mobile",
        "libraryDirectory": "components"
      }
    ]
  ]
}
```
- **Actual Behaviors**

```js
// .babelrc
{
  plugins: [
    [import, {
      libraryName: "mand-mobile",
      libraryDirectory: "lib" // 默认为lib，其他目录参考 #产出包目录，无需配置style
    }]
  ]
}
```

**Comment by xxyan0205** [comment]
会的，所以要把注释去掉

**Comment by shoyuf** [comment]
![http://c.shoyuf.top/18-5-24/75998397.jpg](http://c.shoyuf.top/18-5-24/75998397.jpg)
😄使用了这个plugin报错是什么原因

**Comment by xxyan0205** [comment]
`stylus-loader`等相关loader安装配置一下，https://didi.github.io/mand-mobile/#/docs/theme?anchor=%E5%8F%98%E9%87%8F%E8%A6%86%E7%9B%96
