### ISSUE TITLE
navigators组件和list组件不弄一个吗

### ISSUE THREAD

**Issue by hnu0416** [didi/mand-mobile#101]

**Comment by xxyan0205** [comment]
具体有什么功能，或者有没有类似的案例？

**Comment by hnu0416** [comment]
1、就是toolbar导航栏
2、list的话就是包括loadmore事件的高效的列表组件
可以看看有赞vant的list和NavBar

**Comment by xxyan0205** [comment]
我们会在未来的迭代中讨论是否会添加，也欢迎提一些金融场景相关的业务组件需求。
