### ISSUE TITLE
postcss-pxtorem如何只转换mand-mobile组件的px

### ISSUE THREAD

**Issue by u14e** [didi/mand-mobile#103]
- **Mand Mobile Version：** 1.7.0

因为项目之前用了rem和px混合编写，目前按需加载mend-mobile组件，会打乱之前的size。希望postcss-pxtorem只转换mend-mobile组件里面的样式，看postcss-pxtorem官网貌似没有忽略文件的功能

[https://github.com/cuth/postcss-pxtorem/issues/39](https://github.com/cuth/postcss-pxtorem/issues/39)

- **我的配置文件**

- `.babelrc`
```json
{
  "plugins": [
    ["import",
      {
        "libraryName": "mand-mobile",
        "libraryDirectory": "lib"
      }
    ]
  ]
}
```
- `.postcssrc.js`
```js
module.exports = {
  "plugins": {
    "postcss-import": {},
    "postcss-url": {},
    // to edit target browsers: use "browserslist" field in package.json
    "autoprefixer": {},
    "postcss-pxtorem": {
      rootValue: 100,
      propWhiteList: ['*'],
      selectorBlackList: [/^html$/]
    }
  }
}
```

**Comment by lucker2046** [comment]
猜测您是在webpack中配置的postcss，可以对webpack的module.rules字段自定义匹配规则，针对node_modules/mand-mobile加载自定义的配置而不影响全局

**Comment by u14e** [comment]
@lucker2046 能不能提供一份参考的配置，webpack那边的配置有点理不清

**Comment by u14e** [comment]
`webpack.base.conf.js`做如下配置，还是不生效(webpack 3.6.0)
```js
module: {
    rules: [
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      {
        test: /\.css$/,
        include: [resolve('node_modules/mand-mobile')],
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          { loader: 'postcss-loader', 
            options: {
              plugins: [
                require('postcss-pxtorem')({
                  rootValue: 100,
                  propWhiteList: ['*']
                })
              ]
            }
          }
        ]
      }
    ]
  }
```

**Comment by xxyan0205** [comment]
`.postcssrc.js`  中`postcss-pxtorem`配置去掉没有？

**Comment by u14e** [comment]
已经注释掉了的

**Comment by xxyan0205** [comment]
```
{
  test: new RegExp('\\.css$'),
  use: {
    loader: 'css-loader'
  }
},
{
  test: new RegExp('\\.css$'),
  use: {
    loader: 'postcss-loader',
    options: {
      plugins: [
        require('postcss-pxtorem')({
          rootValue: 100,
          propWhiteList: []
        })
      ]
    }
  },
  include: [resolve('node_modules/mand-mobile')]
}
```

**Comment by vinceok** [comment]
@xxyan0205 大兄弟，怎么单独对mand设置rootValue？按你发的这个似乎不行，我用的scss

**Comment by mrossZ** [comment]
按照这么写 还是不行，项目直接就会报错

**Comment by xxyan0205** [comment]
上面只是一个思路，不一定能使用到每个工程里，因为可能会与原有配置有冲突。思路是将postcss-loader的配置通过**test**或者**include**区分开不同的目录或包，可按下面步骤初始化一个工程参考：

* 初始化一个工程

```bash
vue init mand-mobile/mand-mobile-template my-mand-mobile-project
```
* build/utils.js 中的`styleLoaders`改成如下

```js
exports.styleLoaders = function (options) {
  const output = []
  const loaders = exports.cssLoaders(options)

  for (const extension in loaders) {
    const loader = loaders[extension]
    output.push({
      test: new RegExp('\\.' + extension + '$'),
      use: loader,
      exclude: resolve('node_modules/mand-mobile')
    })
  }

  return output
}
```

* build/webpack.base.conf.js 中rules增加

```js
{
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: [
                require('postcss-pxtorem')({
                  rootValue: 100,
                  propWhiteList: []
                })
              ]
            }
          }
        ],
        include: resolve('node_modules/mand-mobile')
      }
```

**Comment by bart1989** [comment]
2019年3月22日 使用
vue init mand-mobile/mand-mobile-template my-mand-mobile-project 生成的工程

将你提到的 如下两个文件修改完成 无效 。

build/utils.js 中的styleLoaders改成如下
exports.styleLoaders = function (options) {
  const output = []
  const loaders = exports.cssLoaders(options)

  for (const extension in loaders) {
    const loader = loaders[extension]
    output.push({
      test: new RegExp('\\.' + extension + '$'),
      use: loader,
      exclude: resolve('node_modules/mand-mobile')
    })
  }

  return output
}
build/webpack.base.conf.js 中rules增加
{
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: [
                require('postcss-pxtorem')({
                  rootValue: 100,
                  propWhiteList: []
                })
              ]
            }
          }
        ],
        include: resolve('node_modules/mand-mobile')
      }
我看到是postcssrc.js中的   "postcss-pxtorem": config.mand.pxtorem依然在起作用。

**Comment by xxyan0205** [comment]
> 我看到是postcssrc.js中的 "postcss-pxtorem": config.mand.pxtorem依然在起作用。

将`postcssrc.js`中有关`postcss-pxtorem`的配置去掉

**Comment by bart1989** [comment]
将postcssrc.js中有关postcss-pxtorem的配置去掉的话，mand-mobile组件的css单位都是px，即pxtorem未生效。

**Comment by xxyan0205** [comment]
> 将postcssrc.js中有关postcss-pxtorem的配置去掉的话，mand-mobile组件的css单位都是px，即pxtorem未生效。

是否使用了cnpm安装依赖，如果是的话`resolve('node_modules/mand-mobile')`路径需要改，这样找不到

**Comment by bart1989** [comment]
ok解决了

**Comment by bihongbin3027** [comment]
感觉放大了一倍，好难处理啊，我用的是vue-cli3

**Comment by bihongbin3027** [comment]
vue-cli3如何配置postcss-pxtorem，能使大小正常

**Comment by xxyan0205** [comment]
> vue-cli3如何配置postcss-pxtorem，能使大小正常

https://github.com/mand-mobile/vue-cli3-example

**Comment by bihongbin3027** [comment]
多谢，我已经解决，我在vue.config.js里面新增了以下代码：
module.exports = {
	lintOnSave: true,
	css: {
		loaderOptions: {
			postcss: {
				plugins: [
					require('postcss-pxtorem')({
						rootValue : 75, // 换算的基数
						minPixelValue: 2,
						propList: ['*'],
					}),
				]
			}
		}
	}
}

**Comment by bihongbin3027** [comment]
多谢，已经解决，我在vue-cli3的vue.config.js新增了以下代码：
module.exports = {
	lintOnSave: true,
	css: {
		loaderOptions: {
			postcss: {
				plugins: [
					require('postcss-pxtorem')({
						rootValue : 75, // 换算的基数
						minPixelValue: 2,
						propList: ['*'],
					}),
				]
			}
		}
	}
}

**Comment by leida1983** [comment]
vuecli 3.0 怎么弄

**Comment by xxyan0205** [comment]
也可参考 https://rgm-89sc.github.io/2019/05/201905311947/
by: [RGM-89sc](https://github.com/RGM-89sc)

**Comment by AlbatiQue** [comment]
Any idea how to get this integrated in a nuxt.js setup?
知道如何將這個集成到nuxt.js設置中嗎？

**Comment by xxyan0205** [comment]
> Any idea how to get this integrated in a nuxt.js setup?
> 知道如何將這個集成到nuxt.js設置中嗎？

Add the following rule in`build.extend`:

```
export default {
  build: {
    extend (config) {
      config.module.rules.push({
        test:/mand-mobile.*\.css$/,
        use: [
          {
            loader: 'postcss-loader',
            options: {
              plugins: [
                require('postcss-pxtorem')({
                  rootValue: 100,
                  propWhiteList: []
                })
              ]
            }
          }
        ],
      })
    }
  }
}
```

**Comment by Stpcurry30** [comment]
设置了还是很大。。

**Comment by xxyan0205** [comment]
> 设置了还是很大。。

那说明设置的不对，没起作用

**Comment by chenxi5211993** [comment]
> 多谢，已经解决，我在vue-cli3的vue.config.js新增了以下代码：
> module.exports = {
> lintOnSave: true,
> css: {
> loaderOptions: {
> postcss: {
> plugins: [
> require('postcss-pxtorem')({
> rootValue : 75, // 换算的基数
> minPixelValue: 2,
> propList: ['*'],
> }),
> ]
> }
> }
> }
> }

老哥我也是用vue-cli3.0 引入后变的很大，具体你是怎么配置的babel.config.js俩面配置了么？

**Comment by chenxi5211993** [comment]
vue-cli3.0中引入的 组件特别大，按照刚才那个老哥的配置，有没有说一下具体配置流程的？

**Comment by chenxi5211993** [comment]
> 设置了还是很大。。

兄弟，你是怎么解决的？

**Comment by LouisTsang-jk** [comment]
我想只处理我项目里面某个文件夹里面的.vue文件，
改了之后，发现Mustache语法好像不生效了，
不清楚是不是对整个.vue文件都处理了，
然而默认全局处理的时候是只对style标签里面内容作处理的。

**Comment by SingularityXD** [comment]
来挖一波坟,vue-cli 简单暴力解决方法
```
// vue.config.js
const pxtorem = require('postcss-pxtorem');

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('md-postcss')  // 新增规则，规则名自定义
      .test(/mand-mobile.*\.css$/)  // 用正则表达式匹配mand-mobile的组件目录下的所有css文件
      .use('css-loader')  // css加载器
      .loader('postcss-loader')  // css处理器
      .options({  // 这里的内容跟方法一中css.loaderOptions一样
        plugins: [
          pxtorem({
            rootValue: 30,
            minPixelValue: 2,
            propList: ['*'],
            selectorBlackList: []
          })
        ]
      });
  }
};
```

**Comment by suyan123** [comment]
我在项目中设置自身转换比例
![image](https://user-images.githubusercontent.com/43412423/114649721-a39f5600-9d13-11eb-80a3-17d1fc6bf103.png)
又设置了mand-mobile的转换比例
![image](https://user-images.githubusercontent.com/43412423/114649801-c2055180-9d13-11eb-851d-0062438c1703.png)
但是运行的时候报
![image](https://user-images.githubusercontent.com/43412423/114649851-d2b5c780-9d13-11eb-8d35-885d8d8fb058.png)
我查询了一下说是sass-loader版本过高导致，但是我更换了sass-loader版本不起作用   以下是我的配置
![image](https://user-images.githubusercontent.com/43412423/114649980-05f85680-9d14-11eb-9fae-dd46cc707321.png)
