### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Boolean, got Object.

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#110]
- **Mand Mobile Version**

"mand-mobile": "^1.3.0",

- **OS Version & Browser Version**

macOS 10.13.4

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

node -v
v8.11.2

- **Recurring Links**

https://didi.github.io/mand-mobile/#/docs/components/feedback/popup

- **Recurring Steps**

点击弹出左侧Popup窗口，终端提示这个警告。

- **Expectant Behaviors**

- **Actual Behaviors**

```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Boolean, got Object.

found in

---> <MdPopup> at node_modules/mand-mobile/components/popup/index.vue
       <Index> at src/pages/index/index.vue
         <Root>
warn @ vue.esm.js?efeb:591
assertProp @ vue.esm.js?efeb:1632
validateProp @ vue.esm.js?efeb:1560
updateChildComponent @ vue.esm.js?efeb:2849
prepatch @ vue.esm.js?efeb:4144
patchVnode @ vue.esm.js?efeb:5925
updateChildren @ vue.esm.js?efeb:5822
patchVnode @ vue.esm.js?efeb:5936
patch @ vue.esm.js?efeb:6096
Vue._update @ vue.esm.js?efeb:2670
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
run @ vue.esm.js?efeb:3219
flushSchedulerQueue @ vue.esm.js?efeb:2981
(anonymous) @ vue.esm.js?efeb:1837
flushCallbacks @ vue.esm.js?efeb:1758
```

**Comment by xxyan0205** [comment]
?

**Comment by snowdream** [comment]
已经补充内容。

Recurring Links
https://didi.github.io/mand-mobile/#/docs/components/feedback/popup

Recurring Steps
点击弹出左侧Popup窗口，终端提示这个警告。

**Comment by xxyan0205** [comment]
警告中已经提示，Invalid prop: type check failed for prop "value". Expected Boolean, got Object.
请检查下v-model的变量类型。

**Comment by snowdream** [comment]
<template>
  <div id="app" class="xyt-page md-example-child md-example-child-popup md-example-child-popup-0">
    <md-button @click="showPopUp('left')">左侧弹出</md-button>
    <md-popup
      v-model="isPopupShow.left"
      position="left"
    >
    <div class="md-example-popup md-example-popup-left">
    <ul>
      <li><a href="register.html">注册</a></li>
      <li><a href="login.html">登录</a></li>
      <li><a href="reset.html">忘记密码</a></li>
      <li><a href="modify.html">修改密码</a></li>
      <li><a href="changephone.html">更换手机号码</a></li>
    </ul>
    </div>
    </md-popup>
  </div>
</template>

<script>
import { Popup, PopupTitleBar, Button } from 'mand-mobile'
const userutil = require('../../tools/userutil')

export default {
  title: '主页面',
  components: {
    [Popup.name]: Popup,
    [PopupTitleBar.name]: PopupTitleBar,
    [Button.name]: Button
  },
  data () {
    return {
      isPopupShow: {}
    }
  },
  methods: {
    showPopUp (type) {
      this.$set(this.isPopupShow, type, userutil.isLogin())
    },
    hidePopUp (type) {
      this.$set(this.isPopupShow, type, false)
    }
  }
}
</script>


<style lang="stylus" scoped>
.md-example-child-popup-0 {
  float: left;
  width: 100%;

  .md-button {
    margin-bottom: 20px;
  }

  .md-example-popup {
    position: relative;
    font-size: font-minor-large;
    background: color-bg-base;
    box-sizing: border-box;
    text-align: center;
  }

  .md-example-popup-center {
    padding: 50px;
    border-radius: radius-normal;
  }

  .md-example-popup-top {
    width: 100%;
    height: 75px;
    line-height: 75px;
    background: notice-bar-fill;
    color: notice-bar-color;

    .md-icon {
      position: absolute;
      right: 20px;
      top: 50%;
      transform: translateY(-50%);
    }
  }

  .md-example-popup-bottom {
    width: 100%;
    padding: 50px 0;

    p {
      line-height: 50px;
    }
  }

  .md-example-popup-left, .md-example-popup-right {
    height: 100%;
    padding: 0 150px;
    display: flex;
    align-items: center;
  }

  .md-popup-box {
    background-color: #FFF;
  }
}
</style>

**Comment by xxyan0205** [comment]
请 console log 一下 userutil.isLogin()

**Comment by snowdream** [comment]
明白了，是这个返回了object
