### ISSUE TITLE
用import引入mand-mobile报错

### ISSUE THREAD

**Issue by tennessine** [didi/mand-mobile#111]
- **Mand Mobile Version**
1.3.2

- **OS Version & Browser Version**
MacOS / Latest Chrome

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**
node v10.4.0、yarn 1.7.0、npm 6.1.0

- **Recurring Links**
none

- **Recurring Steps**
在app.js里用import mandMobile from 'mind-mobile', 然后console.log(typeof mandMobile)会打印undefined，如果用const mandMobile = require('mand-mobile')就不会

- **Expectant Behaviors**
mandMobile不为undefined

- **Actual Behaviors**
mandMobile为undefined

**Comment by tennessine** [comment]
<img width="1167" alt="wx20180611-183223 2x" src="https://user-images.githubusercontent.com/4545879/41227007-f0d925e0-6da5-11e8-95cb-40f556c3dc0e.png">

**Comment by moyus** [comment]
用的什么构建工具？

**Comment by tennessine** [comment]
@moyus vue-cli生成的
