### ISSUE TITLE
请问主站的文字动画是怎么实现的, mand-mobile 有动画支持吗

### ISSUE THREAD

**Issue by ifyour** [didi/mand-mobile#114]
文字载入到视口, 文字上移的动画, 谢谢.

![1111](https://user-images.githubusercontent.com/15377484/41634206-46380a44-7475-11e8-817a-2ffd6eaffb86.gif)

**Comment by xxyan0205** [comment]
Vue - transition-group
https://github.com/didi/mand-mobile/blob/master/site/theme/default/Home.vue#L51
https://vuejs.org/v2/guide/transitions.html#Staggering-List-Transitions

**Comment by ifyour** [comment]
感谢回答 :)
