### ISSUE TITLE
覆盖系统样式时，Android手机微信浏览器中打不开页面

### ISSUE THREAD

**Issue by xu932045031** [didi/mand-mobile#120]
#### **OS Version & Browser Version**

Android手机微信浏览器

#### **Node Version, Package Management Tool**

node -v8.11.1 , npm -v5.6.0

#### **Recurring Steps**

在覆盖系统样式变量时，在.babelrc文件中如果添加了图中部分时，Android手机微信浏览器中打不开页面
![image](https://user-images.githubusercontent.com/39111041/41892985-becbed5a-794c-11e8-99e5-566a278e9a55.png)

#### **Expectant Behaviors**

在。babelrc文件中配置了属性'"libraryDirectory": "components"'后，在Android手机的微信浏览器中能打开页面

#### **Actual Behaviors**

在。babelrc文件中配置了属性'"libraryDirectory": "components"'后，在Android手机的微信浏览器中不能打开页面

**Comment by xxyan0205** [comment]
有什么报错？

**Comment by xu932045031** [comment]
在手机端看不到错误，在pc端用微信开发工具1.02版本中是能正常使用的。微信开发工具使用v0.7.0版本时会报错
![image](https://user-images.githubusercontent.com/39111041/41893609-f0df62de-794e-11e8-888c-d531d8f60062.png)

![image](https://user-images.githubusercontent.com/39111041/41893600-e7004670-794e-11e8-823c-304fbdf33996.png)

您看还需要什么信息。

**Comment by xxyan0205** [comment]
webpack是如何配置的？相关编译规则有没有包含mand-mobile

**Comment by lucker2046** [comment]
@xu932045031 能否看一下八宝出来的app.js:2356行

**Comment by xu932045031** [comment]
这是 aap.js 2356行的内容：
eval("/* harmony export (immutable) */ __webpack_exports__[\"c\"] = noop;\n/* unused harmony export requireRemoteScript */\n/* harmony export (immutable) */ __webpack_exports__[\"b\"] = getDpr;\n/* harmony export (immutable) */ __webpack_exports__[\"a\"] = functionToUrl;\n/* harmony export (immutable) */ __webpack_exports__[\"d\"] = randomId;\nfunction noop() {}\n\n/**\n * Include external script dynamically\n */\nfunction requireRemoteScript(src, callback) {\n  const doc = document\n  const head = doc.head || doc.getElementsByTagName('head')[0]\n\n  let node = doc.createElement('script')\n  const supportOnload = 'onload' in node\n  const onload = function() {\n    node = null\n    typeof callback === 'function' && callback()\n  }\n\n  if (supportOnload) {\n    node.onload = onload\n  } else {\n    node.onreadystatechange = function() {\n      if (/loaded|complete/.test(node.readyState)) {\n        onload()\n      }\n    }\n  }\n\n  node.async = true\n  node.crossOrigin = true\n  node.charset = 'utf-8'\n  node.src = src\n  head.appendChild(node)\n}\n\nfunction getDpr() {\n  const getParam = (name, str) => {\n    const reg = new RegExp(`(^|,)${name}=([^,]*)(,|$)`, 'i')\n    const r = str.match(reg)\n    if (r != null) {\n      return r[2]\n    }\n    return null\n  }\n\n  const viewPort = document.querySelector('meta[name=viewport]')\n\n  if (!viewPort) {\n    return 1\n  }\n\n  const viewPortContent = viewPort.getAttribute('content')\n  const initialScale = +(getParam('initial-scale', viewPortContent) || 1)\n  const maximumScale = +(getParam('maximum-scale', viewPortContent) || 1)\n  const minimumScale = +(getParam('minimum-scale', viewPortContent) || 1)\n\n  return 1 / Math.min(initialScale, maximumScale, minimumScale)\n}\n\n/**\n * transform a Function to Blob Url\n */\nfunction functionToUrl(fn) {\n  const blob = new Blob([`(${fn.toString()})(null)`], {type: 'application/javascript'})\n  return URL.createObjectURL(blob)\n}\n\n/**\n * generate random id\n */\nfunction randomId(prefix = '', length = 8) {\n  return `${prefix}-${parseInt(Math.random() * 10 ** length)}`\n}\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMjY3LmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL21hbmQtbW9iaWxlL2NvbXBvbmVudHMvX3V0aWwvbGFuZy5qcz80YTA0Il0sInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBmdW5jdGlvbiBub29wKCkge31cblxuLyoqXG4gKiBJbmNsdWRlIGV4dGVybmFsIHNjcmlwdCBkeW5hbWljYWxseVxuICovXG5leHBvcnQgZnVuY3Rpb24gcmVxdWlyZVJlbW90ZVNjcmlwdChzcmMsIGNhbGxiYWNrKSB7XG4gIGNvbnN0IGRvYyA9IGRvY3VtZW50XG4gIGNvbnN0IGhlYWQgPSBkb2MuaGVhZCB8fCBkb2MuZ2V0RWxlbWVudHNCeVRhZ05hbWUoJ2hlYWQnKVswXVxuXG4gIGxldCBub2RlID0gZG9jLmNyZWF0ZUVsZW1lbnQoJ3NjcmlwdCcpXG4gIGNvbnN0IHN1cHBvcnRPbmxvYWQgPSAnb25sb2FkJyBpbiBub2RlXG4gIGNvbnN0IG9ubG9hZCA9IGZ1bmN0aW9uKCkge1xuICAgIG5vZGUgPSBudWxsXG4gICAgdHlwZW9mIGNhbGxiYWNrID09PSAnZnVuY3Rpb24nICYmIGNhbGxiYWNrKClcbiAgfVxuXG4gIGlmIChzdXBwb3J0T25sb2FkKSB7XG4gICAgbm9kZS5vbmxvYWQgPSBvbmxvYWRcbiAgfSBlbHNlIHtcbiAgICBub2RlLm9ucmVhZHlzdGF0ZWNoYW5nZSA9IGZ1bmN0aW9uKCkge1xuICAgICAgaWYgKC9sb2FkZWR8Y29tcGxldGUvLnRlc3Qobm9kZS5yZWFkeVN0YXRlKSkge1xuICAgICAgICBvbmxvYWQoKVxuICAgICAgfVxuICAgIH1cbiAgfVxuXG4gIG5vZGUuYXN5bmMgPSB0cnVlXG4gIG5vZGUuY3Jvc3NPcmlnaW4gPSB0cnVlXG4gIG5vZGUuY2hhcnNldCA9ICd1dGYtOCdcbiAgbm9kZS5zcmMgPSBzcmNcbiAgaGVhZC5hcHBlbmRDaGlsZChub2RlKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gZ2V0RHByKCkge1xuICBjb25zdCBnZXRQYXJhbSA9IChuYW1lLCBzdHIpID0+IHtcbiAgICBjb25zdCByZWcgPSBuZXcgUmVnRXhwKGAoXnwsKSR7bmFtZX09KFteLF0qKSgsfCQpYCwgJ2knKVxuICAgIGNvbnN0IHIgPSBzdHIubWF0Y2gocmVnKVxuICAgIGlmIChyICE9IG51bGwpIHtcbiAgICAgIHJldHVybiByWzJdXG4gICAgfVxuICAgIHJldHVybiBudWxsXG4gIH1cblxuICBjb25zdCB2aWV3UG9ydCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ21ldGFbbmFtZT12aWV3cG9ydF0nKVxuXG4gIGlmICghdmlld1BvcnQpIHtcbiAgICByZXR1cm4gMVxuICB9XG5cbiAgY29uc3Qgdmlld1BvcnRDb250ZW50ID0gdmlld1BvcnQuZ2V0QXR0cmlidXRlKCdjb250ZW50JylcbiAgY29uc3QgaW5pdGlhbFNjYWxlID0gKyhnZXRQYXJhbSgnaW5pdGlhbC1zY2FsZScsIHZpZXdQb3J0Q29udGVudCkgfHwgMSlcbiAgY29uc3QgbWF4aW11bVNjYWxlID0gKyhnZXRQYXJhbSgnbWF4aW11bS1zY2FsZScsIHZpZXdQb3J0Q29udGVudCkgfHwgMSlcbiAgY29uc3QgbWluaW11bVNjYWxlID0gKyhnZXRQYXJhbSgnbWluaW11bS1zY2FsZScsIHZpZXdQb3J0Q29udGVudCkgfHwgMSlcblxuICByZXR1cm4gMSAvIE1hdGgubWluKGluaXRpYWxTY2FsZSwgbWF4aW11bVNjYWxlLCBtaW5pbXVtU2NhbGUpXG59XG5cbi8qKlxuICogdHJhbnNmb3JtIGEgRnVuY3Rpb24gdG8gQmxvYiBVcmxcbiAqL1xuZXhwb3J0IGZ1bmN0aW9uIGZ1bmN0aW9uVG9VcmwoZm4pIHtcbiAgY29uc3QgYmxvYiA9IG5ldyBCbG9iKFtgKCR7Zm4udG9TdHJpbmcoKX0pKG51bGwpYF0sIHt0eXBlOiAnYXBwbGljYXRpb24vamF2YXNjcmlwdCd9KVxuICByZXR1cm4gVVJMLmNyZWF0ZU9iamVjdFVSTChibG9iKVxufVxuXG4vKipcbiAqIGdlbmVyYXRlIHJhbmRvbSBpZFxuICovXG5leHBvcnQgZnVuY3Rpb24gcmFuZG9tSWQocHJlZml4ID0gJycsIGxlbmd0aCA9IDgpIHtcbiAgcmV0dXJuIGAke3ByZWZpeH0tJHtwYXJzZUludChNYXRoLnJhbmRvbSgpICogMTAgKiogbGVuZ3RoKX1gXG59XG5cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL25vZGVfbW9kdWxlcy9tYW5kLW1vYmlsZS9jb21wb25lbnRzL191dGlsL2xhbmcuanNcbi8vIG1vZHVsZSBpZCA9IDI2N1xuLy8gbW9kdWxlIGNodW5rcyA9IDAiXSwibWFwcGluZ3MiOiJBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOyIsInNvdXJjZVJvb3QiOiIifQ==\n//# sourceURL=webpack-internal:///267\n");

**Comment by xu932045031** [comment]
@xxyan0205 webpack文件有三个，分别如下 
webpack.base.conf.js内容
`var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var PostCompilePlugin = require('webpack-post-compile-plugin')
var TransformModulesPlugin = require('webpack-transform-modules-plugin')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    modules: [
      resolve('src'),
      resolve('node_modules')
    ],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'src': resolve('src'),
      'assets': resolve('src/assets'),
      'components': resolve('src/components')
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/assets/images')]
      }
    ]
  },
  plugins: [
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: `index.html`,
      inject: true,
      title: config.title,
      subtitle: config.subtitle,
      logo:config.logo,
      chunksSortMode: 'dependency'
    }),
    new PostCompilePlugin(),
    new TransformModulesPlugin()
  ]
}`

webpack.dev.conf.js内容
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
const poststylus = require('poststylus')
const pxtorem = require('postcss-pxtorem')
var baseWebpackConfig = require('./webpack.base.conf')
var FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')

// add hot-reload related code to entry chunks
Object.keys(baseWebpackConfig.entry).forEach(function (name) {
  baseWebpackConfig.entry[name] = ['./build/dev-client'].concat(baseWebpackConfig.entry[name])
})

const pxtoremConfig = pxtorem({ rootValue: 100, propWhiteList: [] })

module.exports = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap })
  },
  // cheap-module-eval-source-map is faster for development
  devtool: '#cheap-module-eval-source-map',
  plugins: [
    new webpack.DefinePlugin({
      'process.env': config.dev.env
    }),/*
    new webpack.LoaderOptionsPlugin({
      options: {
        stylus: {
          use: [poststylus(pxtoremConfig)]
        }
      }
    }),*/
    // https://github.com/glenjamin/webpack-hot-middleware#installation--usage
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new FriendlyErrorsPlugin()
  ]
})

webpack.prod.conf.js内容
var path = require('path')
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')

var env = config.build.env

var webpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true
    })
  },
  devtool: config.build.productionSourceMap ? '#source-map' : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    // Compress extracted CSS. We are using this plugin so that possible
    // duplicated CSS from different components can be deduped.
    new OptimizeCSSPlugin({
        cssProcessorOptions:{
          safe:true
        }
    }
    ),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
    // split vendor js into its own file
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    }),
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
  ]
})

if (config.build.productionGzip) {
  var CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}
module.exports = webpackConf




编译时使用的mand-mobile是1.3.3的版本

**Comment by xxyan0205** [comment]
看下webpack的版本
`npm ls webpack`

**Comment by xu932045031** [comment]
@xxyan0205 
![image](https://user-images.githubusercontent.com/39111041/41895403-885068fc-7954-11e8-8392-fe2f319ec269.png)

**Comment by xxyan0205** [comment]
看配置没啥问题，但是看bundle问题出在这条注释被诡异的去掉了最左边的两个*
`\n\n/\n * Include external script dynamically\n */`
正常的应该是
`\n\n/**\n * Include external script dynamically\n */`

尝试升级下webpack或babel， 或者在你当前的电脑下使用[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)初始化一个新项目看有没有问题

**Comment by xu932045031** [comment]
@xxyan0205 嗯，我在试一下
