### ISSUE TITLE
mand-mobile 的 swiper 在 Android 无法响应点击事件

### ISSUE THREAD

**Issue by PLQin** [didi/mand-mobile#121]
#### **OS Version & Browser Version**

全Android系统, 微信浏览器6.6.0

#### **Node Version, Package Management Tool**

"mand-mobile": "^1.3.0",

#### **Recurring Links**

http://10.7.112.183:8082/#/?channelId=LKL_CLOUD_POS

#### **Recurring Steps**

- 点击顶部 banner 

#### **Expectant Behaviors**

- 会前往新的页面

#### **Actual Behaviors**

- Android机型下没有反应, 随机点击banner底部某一小块区域可能会触发

**Comment by xxyan0205** [comment]
试一下下面这个例子，点击能否跳转
[![Edit Mand Mobile Swiper 0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jz7p622ryv)

**Comment by PLQin** [comment]
[Lakala-CreditCard-Wx.zip](https://github.com/didi/mand-mobile/files/2136525/Lakala-CreditCard-Wx.zip)


------

手机和pc一直是 transpiling modules;
上面是我的测试包, 能否帮我看下, 我有注意你的demo写了`@click.native`, 但是我也一直是这样使用的, 没有效果;
`npm start` 后访问:
localhost:8080/#/?channelId=LKL_CLOUD_POS

**Comment by xxyan0205** [comment]
`is-prevent`是否设置为`false`

**Comment by PLQin** [comment]
@xxyan0205 果然是这个问题 , /赞
但是为什么`is-prevent` 未设置为 `false` 时, 在ios系统中, 可以被点击, 在pc开发者工具模拟时可以被点击, 
甚至于在Android底部某一块随机点击时也能触发

**Comment by PLQin** [comment]
目前官方文档的说明是: 

is-prevent | 是否阻止默认的事件，如页面滚动事件 | Boolean | true | true, false
-- | -- | -- | -- | --

---

个人认为这是不规范的, 
可以更新官方文档, 或者更新代码, 过滤掉用户绑定的点击事件
