### ISSUE TITLE
mand-mobile与cube-ui有什么联系与区别？

### ISSUE THREAD

**Issue by xesam** [didi/mand-mobile#122]
后续会考虑融合吗？或者有一个公共的基础库？是否方便混用。

**Comment by xxyan0205** [comment]
目前还没有直接联系，`cube-ui`提供基础通用组件面向所有场景，而`mand-mobile`专注金融场景。未来`mand-mobile`可能会将组件库的基础部分抽离交给第三方如`cube-ui`，使得我们可以把更多精力用在复杂的金融场景的业务逻辑处理上。

![image](https://user-images.githubusercontent.com/8409100/42018290-3a09c008-7ae4-11e8-8d3e-0a245dee88d1.png)
