### ISSUE TITLE
how to set component default font-size？

### ISSUE THREAD

**Issue by jsasdw1991** [didi/mand-mobile#123]
#### **Mand Mobile Version**
"mand-mobile": "^1.3.3"

#### **OS Version & Browser Version**
macbook pro 10.13.5
谷歌浏览器67.0.3396.99

#### **Node Version, Package Management Tool**
node: v10.5.0
npm: 6.1.0
"vue": "^2.5.16"
@vue/cli: 3.0-rc3

#### **question**
components font-size is error, so big! how to solve the problem, cover the css ?
![image](https://user-images.githubusercontent.com/6205001/42082898-cee61f28-7bbb-11e8-8b34-e8c709ac1999.png)

**Comment by xxyan0205** [comment]
Refer to [wiki - FAQ - 为什么组件尺寸很大/如何做响应式适配？](https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E5%B0%BA%E5%AF%B8%E5%BE%88%E5%A4%A7%E5%A6%82%E4%BD%95%E5%81%9A%E5%93%8D%E5%BA%94%E5%BC%8F%E9%80%82%E9%85%8D)

**Comment by jsasdw1991** [comment]
@xxyan0205 但是vue-cli 3.0版本的webpack的配置文件都被隐藏了。如何修改webpack配置？

**Comment by xxyan0205** [comment]
Refer to [mand-mobile-vue-cli3-example](https://github.com/mand-mobile/mand-mobile-vue-cli3-example)
