### ISSUE TITLE
radio单选框样式问题

### ISSUE THREAD

**Issue by xu932045031** [didi/mand-mobile#126]
#### **Mand Mobile Version**

版本1.4.1
#### **Expectant Behaviors**

最新版本的radio单选框如果使用icon后，内容与icon应该有间距

#### **Actual Behaviors**

最新版本的radio单选框如果使用icon后，内容会遮挡icon
![image](https://user-images.githubusercontent.com/39111041/42270498-99dec9a0-7fb3-11e8-84db-0fd47b511dd0.png)

**Comment by xxyan0205** [comment]
fixed@1.4.3
