### ISSUE TITLE
请教 picker 的 default-index 的使用方法

### ISSUE THREAD

**Issue by 1847211504** [didi/mand-mobile#134]
#### **Mand Mobile Version**

v 1.4.3
#### **OS Version & Browser Version**

windows chrome 67 64位

#### **Recurring Links**

https://codesandbox.io/s/zxj3voq4xx

#### **Recurring Steps**

引入 picker 组件后，方法中动态修改 deaultIndex

#### **Expectant Behaviors**

索引按设置改变

#### **Actual Behaviors**

未改变，无论是否调用了 refresh 方法

**Comment by xxyan0205** [comment]
因为第一次渲染完成后再动态修改`deaultIndex` picker并没有被重新渲染。
给picker增加一个`key`，每次`defaultIndex`改变的时候，通过更改`key`强制重新渲染。

```javascript
<md-picker
      ref="picker"
      :data="picker.data"
      :title="picker.title"
      :default-index="picker.defaultIndex"
      :key="picker.defaultIndex"
      v-model="picker.show"
    ></md-picker>
```

**Comment by 1847211504** [comment]
收到，测试已通过，多谢
