### ISSUE TITLE
快速上手 步骤的 Px to Rem 能写详细点吗？

### ISSUE THREAD

**Issue by sweida** [didi/mand-mobile#140]
快速上手 步骤的 Px to Rem 能写详细点吗？

步骤：用postcss-pxtorem把px单位转成rem
需要手动安装 npm install postcss-pxtorem 吗？

步骤：修改webpack配置
能写清楚是修改webpack的哪个文件吗？文件中的哪个方法

弄了半天，硬是没弄出来。

**Comment by xxyan0205** [comment]
这些属于具体实践的细节不便于写到文档中，因为不同的使用场景有不同的配置方法，对于通用的场景我们提供了vue cli2 模板和vue cli3的demo，方便初始化项目：
https://github.com/mand-mobile/mand-mobile-template
https://github.com/mand-mobile/mand-mobile-vue-cli3-example

**Comment by sweida** [comment]
你给出的是新项目的方案吧? 
我现在是在已有的项目上用mand-mobile，完成看不到文档px怎么转rem的

**Comment by banls** [comment]
傻逼UI 逼问题真多，死了妈的作者没办法

**Comment by banls** [comment]
还转你妈的像素， 你妈全家是狗妈
