### ISSUE TITLE
引入mand-mobile后，组件的样式十分巨大

### ISSUE THREAD

**Issue by txqcoder** [didi/mand-mobile#143]
我们引入mand-mobile后，组件的样式十分巨大，不得不覆盖样式来匹配我们的rem计算方式，
请问有什么好的处理办法吗? ☺

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E5%B0%BA%E5%AF%B8%E5%BE%88%E5%A4%A7%E5%A6%82%E4%BD%95%E5%81%9A%E5%93%8D%E5%BA%94%E5%BC%8F%E9%80%82%E9%85%8D

**Comment by xxyan0205** [comment]
如果是px与rem的转换比例与现有的项目有冲突（组件库是以750px为基准），可以考虑对mand-mobile单独加相关配置。 #103
