### ISSUE TITLE
[Selector] 组件滚动穿透

### ISSUE THREAD

**Issue by zouhangwithsweet** [didi/mand-mobile#157]
#### **Mand Mobile Version**
1.5.1-1.41.
#### **OS Version & Browser Version**

ios: 11.4.1
browser: wechat 内置浏览器，Safari， Chrome67(手机端)

#### **Node Version, Package Management Tool**

Node@8.11.2
vue-cli@3.rc3

#### **Recurring Links**

https://vjp3qyw6yy.codesandbox.io/

#### **Recurring Steps**

容器足够高出现滚动条，
selector的选项足够多，出现滚动条

#### **Expectant Behaviors**

滚动不穿透

#### **Actual Behaviors**

滚动穿透

**Comment by LiangNex** [comment]
同类滚动嵌套场景下，可否麻烦帮添加一个```md-scroll-view```的禁用滚动事件传播的功能，并可由```md-selector```传入一个属性以启用该功能。

现有需求在滚动嵌套的场景下， ```md-selector```的弹层开启后， 弹层内的内容滚动到底后不希望触发父页面的滚动事件

**Comment by xxyan0205** [comment]
> `md-selector`的弹层开启后， 弹层内的内容滚动到底后不希望触发父页面的滚动事件

滚动穿透的问题只存在于1.x，在最新的版本中嵌套了scrollview不存在这个问题
