### ISSUE TITLE
vue/cli@3.x下，mand-mobile官方文档提供的svg图标配置会导致其他文件夹下svg构建失败

### ISSUE THREAD

**Issue by qidaneix** [didi/mand-mobile#160]
mand-mobile@1.5.0

mac os high sierra / chrome@67

node@v8.11.3 / npm@6.2

https://github.com/qidaneix/mand-mobile-issue/tree/svg-config-issue
tag标签：svg-config-issue
尝试在sandboxcode上运行，但是没有运行成功，只能给github仓库，抱歉！

clone -> npm install -> npm run serve

`./src/chat-46.svg`被webpack成功构建

webpack构建失败：

![image](https://user-images.githubusercontent.com/13130795/43137003-102e0b1a-8f7d-11e8-8317-80f772aeb3a5.png)

按照mand-mobile官方文档提供的配置svg图标的教程配置了vue/cli@3.x版本的vue.config.js文件：
```javascript
  chainWebpack: config => {
    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()
    svgRule
      .include
        .add(resolve('./src/assets'))
        .end()
      .use('svg-sprite-loader')
        .loader('svg-sprite-loader')
  }
```
大概是因为`svgRule.uses.clear()`，导致不在`resolve('./src/assets')`中的svg文件的loader被清理，svg文件构建失败。
还是有实际场景需求的，比如我想在一个img标签中引入svg图片。

**Comment by qidaneix** [comment]
@xxyan0205 目测是没有用，还是会报相同的错误，只有把整段配置去除才能正常运行

**Comment by xxyan0205** [comment]
看下vue cli3有没有类似的issue把

**Comment by hatunet** [comment]
`const svgRule = config.module.rule('svg');
    svgRule.uses.clear();
    svgRule
      .use('file-loader')
      .loader('svg-sprite-loader')
      .options({ symbolId: 'icon-[name]' });`
