### ISSUE TITLE
使用Dialog时报错name属性不存在，vue cli 3.0 yarn build 报错

### ISSUE THREAD

**Issue by mt-ik** [didi/mand-mobile#169]
#### **Mand Mobile Version**

vue cli v3.0.0-rc.5;  mand mobile 1.5.2; typescript

#### **OS Version & Browser Version**

mac 、 chrome

#### **Node Version, Package Management Tool**

node v8.10.0; yarn v.1.7.0

#### **Actual Behaviors**

ts 检测 Dialog.name 不存在, 但是本地开发功能正常, 但是在vue cli3.0 yarn build 时 无法通过

**Comment by Wittawat2538** [comment]
5000
