### ISSUE TITLE
【BUG】DatePicker type="datetime" 设置了 minDate 为当前时间，造成后续每一日的时间起点都是从这一时刻开始的

### ISSUE THREAD

**Issue by dingyiming** [didi/mand-mobile#185]
【BUG】DatePicker type="datetime" 设置了 minDate 为当前时间，造成后续每一日的时间起点都是从这一时刻开始的，后面的日期都不是从 0:00 开始的

![](https://images-cdn.shimo.im/8Rs7lytQfbcOF6DL/image.png!thumbnail)

**Comment by xxyan0205** [comment]
minDate 设置详细指定`年月日时分秒` 不要直接Date.now()

**Comment by dingyiming** [comment]
minDate 不是 Date 类型吗？ 你写的 字符串没有用啊

minDate | 最小可选日期 | Date
-- | -- | --

**Comment by xxyan0205** [comment]
new Date(minDate), 另外没有明白从00开始掩盖了什么问题
