### ISSUE TITLE
滚动使用了transform ，fixed失效，但是内部怎么放个tab让他能吸顶呢

### ISSUE THREAD

**Issue by mlboy** [didi/mand-mobile#188]

**Comment by mlboy** [comment]
看这个实现不错
https://github.com/ustbhuangyi/better-scroll

**Comment by xxyan0205** [comment]
原理一样的都是transform模拟滚动，后面会在“滚动”的`scroll-view-container`外增加一个插槽。目前只能直接把需要吸顶的元素放到`scroll-view`外。
