### ISSUE TITLE
Tabs在属性`noslide`为`true`时，切换Tab项内容会被销毁，切回时内容会被重新创建

### ISSUE THREAD

**Issue by rickysang** [didi/mand-mobile#190]
#### **Mand Mobile Version**
v.1.5.6

#### **Recurring Links**
偷懒直接用了#189的链接[https://codesandbox.io/s/24z06oq1yp](https://codesandbox.io/s/24z06oq1yp)，请见谅

#### **Recurring Steps**
切换`noslide = true`的Tabs

#### **Expectant Behaviors**
建议考虑支持`keep-alive`特性或通过`display:none`实现解决这个问题？

#### **Actual Behaviors**
Tabs内容被销毁/重新创建

**Comment by moyus** [comment]
这是实现上有意的逻辑，源码中难以修改为隐藏/显示模式。会在2.0版本中重写此组件逻辑。
