### ISSUE TITLE
希望开发更多的组件！！

### ISSUE THREAD

**Issue by StriveTo** [didi/mand-mobile#193]

**Comment by xxyan0205** [comment]
目前2.0正在开发中，会新增部分组件，但是基本是面向金融业务。如果有相关的需求或场景欢迎可以提供。

**Comment by StriveTo** [comment]
嗯，面向金融类的很不错，但是也可以增加一些实用性比较强的组件，像一些评分功能，树形控件，可以做一些信用评分之类的，你们这个做的很不错，上次用了Picker 选择器 （地址选择）有bug，然后过了一段时间再次看的时候就修复了
