### ISSUE TITLE
radio控件初始数据为空且设置了default-index时报错

### ISSUE THREAD

**Issue by xu932045031** [didi/mand-mobile#194]
#### **Mand Mobile Version**

1.5.4

#### **Recurring Steps**

在使用radio控件时，数据是由后台传递的，同时默认选择哪个也是由后台传过来的，这个时候设置默认选项属性default-index时会报错
[Mand-Mobile]: radio option represented by the default-index is invalid

#### **Expectant Behaviors**

不会报错

**Comment by xxyan0205** [comment]
1. 检查一下`default-index `对应的数据是否为无效数据或者disabled是否被设置true
2. 如果需要动态修改`default-index`，给radio增加一个key，修改`default-index`时同步修改key

**Comment by xu932045031** [comment]
我现在是这样操作的，选项的数据为空，从后台获取。default-index设置默认选择第一个。这个时候会显示上面的那个错误

**Comment by xxyan0205** [comment]
如果时数据为空的话 把defaultIndex置为-1

**Comment by xu932045031** [comment]
好的，谢谢
