### ISSUE TITLE
InputITtem 清空内容的icon一直存在的问题

### ISSUE THREAD

**Issue by MickeyMouse623** [didi/mand-mobile#196]
### 解决：
在 mand-mobile/lib/input-item/index.js 文件 406 行
```javascript
_c('div',{directives:[{name:"show",rawName:"v-show",value:(!_vm.isInputEmpty)

// 修改为
_c('div',{directives:[{name:"show",rawName:"v-show",value:(!_vm.isInputEmpty && _vm.isInputFocus)
```
修改后的状态为：聚焦且有内容时显示clear，丢失焦点则display: none

**Comment by xxyan0205** [comment]
其实是一个交互的问题，本来想在2.0里修复，既然提了就提前改了

**Comment by MickeyMouse623** [comment]
那麻烦你们 InputItem 类型为 password时，增加 查看密码 的功能，这种普遍需求都没有。
尝试 <Filed> 配和 <md-icon slot="right"/> 使用时，icon居然没有 click事件向下传递。。。

没办法了，只有弃用，期待你们2.0

**Comment by MickeyMouse623** [comment]
你好，你们框架使用的是 rem 作为css单位。我现在通过 postcss 更改为 vw 了，但是根节点任然被加上了 100rem (iphone 6/7/8  375 * 675 配置)，这时通过 document.documentElement.clientHeight 获取到的高度为 675 * 2。
请问，根节点指定rem怎么去除？？？

**Comment by xxyan0205** [comment]
组件库中样式单位使用的是px，可根据使用情况选择是否转换rem，我们在产出包中也包含了一个vw的版本 https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E4%BA%A7%E5%87%BA%E5%8C%85%E7%9B%AE%E5%BD%95

**Comment by MickeyMouse623** [comment]
{
  "name": "mand-mobile",
  "version": "1.5.6",
  "description": "A Vue.js 2.0 Mobile UI Toolkit",
  "homepage": "https://github.com/didi/mand-mobile",
  "main": "lib/mand-mobile.umd.js",
  "style": "lib/mand-mobile.css",
  "module": "lib/mand-mobile.esm.js",
  "unpkg": "lib/index.js",
  "typings": "types/index.d.ts"

修改 package.json 中 main，type，module，unpkg 中的 lib 为 lib-vw 吗？？？

**Comment by xxyan0205** [comment]
如果全量引入，直接import `lib-vw/mand-mobile.umd.js` `lib-vw/mand-mobile.css`，如果是按需加载修改引入路径配置。
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E5%BC%95%E5%85%A5

**Comment by abozhang** [comment]
md-clear 这个icon不能显示，用demo中的例子代码也不能展示，但是别的icon可以显示


<template>
  <div class="md-example-child md-example-child-icon md-example-child-icon-0">
    <div
      class="md-example-item"
      v-for="icon in iconList"
      :key="icon"
    >
      <md-icon
        :name="icon.split('/')[0]"
        size="lg"
      ></md-icon>
      <p>{{ icon }}</p>
    </div>
  </div>
</template>

<script>
import {Icon} from 'mand-mobile'

export default {
  name: 'icon-demo',
  /* DELETE */
  title: '字体图标',
  titleEnUS: 'Icon Font',
  align: 'center',
  background: '#fff',
  /* DELETE */
  components: {
    [Icon.name]: Icon,
  },
  data() {
    return {
      iconList: [
        'rectangle',
        'right',
        'wrong',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'arrow-down',
        'invisible',
        'visible',
        'service',
        'setting',
        'close',
        'refresh',
        'edit',
        'sort',
        'info',
        'question',
        'security',
        'rmb',
        'wait',
        'check',
        'checked/success',
        'check-disabled',
        'clear/fail',
        'warn',
        'info-solid',
        'scan',
        'share',
        'back',
        'card-bag',
        'message',
        'order',
        'balance',
        'coupon',
        'address-book',
        'mobile-phone',
        'calendar',
        'home',
        'discovery',
        'switch',
        'time',
        'search',
        'user',
        'camera',
        'clock',
        'delete',
        'profession',
        'id-card',
        'authentication',
        'location',
        'filter',
        'motor-vehicle',
        'phone',
        'volumn',
      ],
    }
  },
}

</script>

**Comment by xxyan0205** [comment]
> clear 这个icon不能显示，用demo中的例子代码也不能展示，但是别的icon可以显示

需要用检查元素看下是否有其他样式覆盖或者干扰的问题，如果没有的话用[mand-mobile-issue-helper](https://mand-mobile.github.io/mand-mobile-issue-helper/)反馈下问题并提供下复现问题的demo
