### ISSUE TITLE
inputitem输入框使用金融数字键盘控件时，键盘会遮挡输入框

### ISSUE THREAD

**Issue by xu932045031** [didi/mand-mobile#197]
#### **Mand Mobile Version**

1.5.4
#### **OS Version & Browser Version**

所有浏览器
![image](https://user-images.githubusercontent.com/39111041/45133744-72f4f880-b1c9-11e8-9dcb-58abf9ec6911.png)
![image](https://user-images.githubusercontent.com/39111041/45133753-7daf8d80-b1c9-11e8-80ad-7ecc665325ff.png)

#### **Expectant Behaviors**

inputitem输入框使用金融数字键盘控件，如果输入框比较靠下时，键盘不会遮挡输入框

#### **Actual Behaviors**

inputitem输入框使用金融数字键盘控件时，如果输入框比较靠下，键盘会遮挡输入框

**Comment by xxyan0205** [comment]
组件目前不支持自动滚动页面出现在可视区域，可能会造成不可预知的副作用。可以在应用层实现这个功能，可以参考demo-表单控件

**Comment by xu932045031** [comment]
好的，谢谢
