### ISSUE TITLE
想问下，ios 下toast无效  安卓下是好的，是什么原因

### ISSUE THREAD

**Issue by xxyan0205** [didi/mand-mobile#198]
_Originally posted by @kai517 in https://github.com/didi/mand-mobile/issues/191#issuecomment-421711113_

**Comment by xxyan0205** [comment]
@kai517 请给下具体问题描述，以及复现问题需要的版本和环境等基本信息

**Comment by xyjwsj** [comment]
![image](https://user-images.githubusercontent.com/8518853/48128231-c7e3e680-e2c0-11e8-991e-f64de416044a.png)
IOS 版本 10.3.1
