### ISSUE TITLE
下拉刷新和上拉加载一起使用的问题

### ISSUE THREAD

**Issue by inTheSun** [didi/mand-mobile#199]
#### **Recurring Steps**

上拉加载，加载到底的时候会触发isEndReaching变为true，触发endReached的回调，但是因为finished为true，所以不会触发继续加载，之后回到顶部触发下拉刷新，刷新列表回第一页的状态，之后下拉无法加载
#### **Expectant Behaviors**

在触发下拉刷新，如果isEndReaching为true把参数isEndReaching重置为false
#### **Actual Behaviors**

下拉刷新不改变isEndReaching

**Comment by xxyan0205** [comment]
在组件内部**下拉刷新**和**上拉加载**应该视为两个无关联的动作，因为动作内容有用户决定(业务逻辑)，故无法确定下拉刷新一定是“刷新列表回第一页的状态”，所以无法直接在下拉刷新的时候控制`isEndReaching`。

对于上述问题可以抽象为`“下拉刷新”时需将“上拉加载”的状态重置`，可以在`refreshing`事件去手动重置：
(finishLoadMore这个方法在文档中没有充分介绍其作用，后面会补充)
```js
$_onRefresh() {
    // 重置列表数据
    this.list = 10
    this.$refs.scrollView.finishRefresh()
    // “上拉加载”的状态
    this.isFinished = false
    this.$refs.scrollView.finishLoadMore()
}
```

**Comment by penggangg** [comment]
我重置 isFinished 的状态 应该还是不行 我现在加了下面的代码
this.$refs.scrollView.scrollTo(0, 0, false)
 this.$refs.scrollView.isEndReaching = false
this.$refs.scrollView.isEndReachingStart = false

**Comment by xxyan0205** [comment]
> 我重置 isFinished 的状态 应该还是不行 我现在加了下面的代码

试一下 `this.$refs.scrollView.finishLoadMore()`

**Comment by penggangg** [comment]
chooseType (type) {
      this.messType = type
      this.current = 1
      this.isFinished = false
      this.$refs.listScroll.$_finishLoadMore()
      this.getList()
    },
这是项目代码 我这样写确实解决之前的问题， 现在出现的就是不重置滚动条了，比如说我第一加载到第2页，现在切换一下之后 如果 数据超过2页 会直接把第一页和第二页的数据都请求过来，相当于请求了两次

**Comment by xxyan0205** [comment]
> 直接把第一页和第二页的数据都请求过来，相当于请求了两次

这个问题不在这个issue里讨论了，去这里吧 #457
