### ISSUE TITLE
Swiper轮播加了切换动画效果fade后无法触摸滚动

### ISSUE THREAD

**Issue by LetHergo** [didi/mand-mobile#20]
另外文档中transition可选值中有两个fade

**Comment by LetHergo** [comment]
1.设备是iphone6plus Safari浏览器 以及PC端chrome浏览器
2."mand-mobile": "^1.0.4",
3.代码用的Swiper文档示例渐隐轮播的代码

**Comment by moyus** [comment]
当前swiper的fade模式不支持触摸滚动，这个特性需求会在1.1版本里加入

**Comment by LetHergo** [comment]
另外~ 文档中示例 Tabs 标签页 指定默认标签:default-index="2" 失效。
但是 TabBar  标签栏中示例是正常的。
@moyus

**Comment by moyus** [comment]
感谢指出，我们会及时修正文档示例及说明。
@LetHergo

**Comment by LetHergo** [comment]
@moyus    DropMenu 下拉菜单中   change事件时能否添加获取该项index值

**Comment by xxyan0205** [comment]
@LetHergo change事件会涉及BarItem和listItem的更改，所以既需要确定BarItem和ListItem的索引，又要ListItem的数据，所以目前可以在构造data时，将索引值添加到BarItem和Listitem中，这样就可以在数据中拿到，比如：

```
const data =[{
  text: 'bar-item-0',
  index: 0,
  options: [{
    text: 'list-item-0-0',
    index: 0,
  },{
    text: 'list-item-0-1',
    index: 1,
  }]
},{
  text: 'bar-item-1',
  index: 1,
  options: [{
    text: 'list-item-1-0',
    index: 0,
  },{
    text: 'list-item-1-1',
    index: 1,
  }]
}]
```

**Comment by LetHergo** [comment]
@moyus  @xxyan0205   能否给下拉菜单 DropMenu 遮罩  添加类似 Popup弹出层  是否禁止滚动穿透prevent-scroll类似的属性

**Comment by xxyan0205** [comment]
@LetHergo DropMenu的table滚动应该没有允许击穿的场景，所以这个地方当做一个bug处理， #29

**Comment by LetHergo** [comment]
@xxyan0205    TabPicker 多级联动选择器  示例点击没有反应

**Comment by xxyan0205** [comment]
@LetHergo 感谢反馈，站点构建的问题，已修复。
