### ISSUE TITLE
使用验证码框控件时，验证码长度为6位且弹窗显示时样式问题

### ISSUE THREAD

**Issue by xu932045031** [didi/mand-mobile#200]
#### **Mand Mobile Version**

1.6
#### **Recurring Steps**

在使用验证码窗控件时，验证码长度为6位且弹窗显示时验证码输入框超出dialog的宽度。
![image](https://user-images.githubusercontent.com/39111041/46060145-a0174400-c194-11e8-8533-68f290fd9680.png)

#### **Expectant Behaviors**

验证码长度6位时，验证码输入框不会超出弹框
#### **Actual Behaviors**

验证码长度6位时，验证码输入框会超出弹框

**Comment by yushi105** [comment]
按照 教程实例写的，Captcha   submit 函数不执行呀，怎么回事

**Comment by xxyan0205** [comment]
> Captcha submit 函数不执行呀

怎么用的？

**Comment by yushi105** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： Shawn Xu <notifications@github.com>日期： 2019年10月18日周五 16:54收件人： didi/mand-mobile <mand-mobile@noreply.github.com>抄送： 雨逝 <yushi105@163.com>, Comment <comment@noreply.github.com>主    题： Re: [didi/mand-mobile] 使用验证码框控件时，验证码长度为6位且弹窗显示时样式问题 (#200)

Captcha submit 函数不执行呀



怎么用的？

**Comment by yushi105** [comment]
通过浏览器引入的方式，<md-captcha
      ref="captcha"
      v-model="isShow"
      :title="title"
      maxlength="6"
      mask="true"
      @submit="onSub"
      @show="onShow"
      @hide="onHide"
      @send="onSend">
      {{content}}
    </md-captcha>

js 里面 onSub 的方法，onSub (val) {
  console.log(val)
  setTimout(() =>{
    // 执行自己的方发
  }, 300)
}
isShow 为true时，onSub 都没执行，第一行都没打印

**Comment by yushi105** [comment]
> Captcha submit 函数不执行呀
> 
> 怎么用的？

通过浏览器引入的方式，<md-captcha
      ref="captcha"
      v-model="isShow"
      :title="title"
      maxlength=6
      mask="true"
      @submit="onSub"
      @show="onShow"
      @hide="onHide"
      @send="onSend">
      {{content}}
    </md-captcha>

js 里面 onSub 的方法，onSub (val) {
  console.log(val)
  setTimout(() =>{
    // 执行自己的方发
  }, 300)
}
isShow 为true时，onSub 都没执行，第一行都没打印
maxlength 为-1时，点击键盘确定会执行，但是打印val 是undefined，那么怎么获取 输入的验证码呢

**Comment by supergaojian** [comment]
1、请确认您的mand-mobile版本号是否为v2.x
2、如果满足第一条，麻烦请提供可完整复现的最小代码
谢谢

**Comment by zouhangwithsweet** [comment]
http://jsbin.com 来个 demo 吧

**Comment by yushi105** [comment]
> 1、请确认您的mand-mobile版本号是否为v2.x
> 2、如果满足第一条，麻烦请提供可完整复现的最小代码
> 谢谢
版本为最新2.5.3
<!DOCTYPE html>
<html>
 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
   <meta content="telephone=no" name="format-detection" />
   <meta name="format-detection" content="email=no" />
   <meta http-equiv="Cache-Control" content="no-cache"/>
 <title>mand mobile 学习</title>
 <link rel="stylesheet" href="js/mand.min.css">
 <style>
 [v-clock]{
   display: none !important;
 }
 *{
   padding:0;
   margin: 0;
 }
 .btn{
   width: 100%;
   height: 40px;
 }
 </style>
 </head>
 <body>
  <div id="app">
    <p class="p-lr-15 p-tb-10">
      <button @click="isCaptcha=!isCaptcha" class="btn">Captcha</button>
    </p>
    <md-captcha ref="captcha"
      v-model="isCaptcha"
      title="输入验证码"
      maxlength=6
      @submit="onSub()"
      @show="onShow"
      @hide="onHide"
      @send="onSend">{{contentMsg}}
    </md-captcha>
  </div>
 </body>
 <script src="https://cdn.staticfile.org/vue/2.2.2/vue.min.js"></script>
 <script src="js/mand.min.js"></script>
<script>
var app = new Vue({
  el: '#app',
  data: {
    isCaptcha: false,
    contentMsg: '验证码已发送至 152 **** 0000',
  },
  created() {
  },
  methods: {
    onSub (val) {
      console.log('走入onSub函数------')
      setTimeout(() => {
        if (val.length === 6) {
          console.log(val)
          this.isCaptcha = false
        } else {
          console.log(val)
        }
      }, 300);
    },
    onShow () {console.log('onShow');},
    onHide () {console.log('onHide');},
    onSend () {console.log('onSend');},
  }
})
</script>
</html>

**Comment by supergaojian** [comment]
为了更好的方便您反馈描述问题，请添加mand mobile官方交流QQ群：493305323。我们会有人帮您解决问题

**Comment by supergaojian** [comment]
您好，经过您在QQ群反馈的demo，在 submit 回调中不要直接写 onSub() 而是应该写 onSub。因为你写的是 onSub() 所以它并不会执行（因为在组件初始化渲染template的时候已经执行完了，拿到了onSub的返回值 undefined ，所以当您使用组件回调时，真正调用的是 undefined 而不是您的期望 onSub）

**Comment by yushi105** [comment]
您好，不带括号，也是一样的发自我的华为手机-------- 原始邮件 --------发件人： supergaojian <notifications@github.com>日期： 2019年10月21日周一 18:11收件人： didi/mand-mobile <mand-mobile@noreply.github.com>抄送： 雨逝 <yushi105@163.com>, Comment <comment@noreply.github.com>主    题： Re: [didi/mand-mobile] 使用验证码框控件时，验证码长度为6位且弹窗显示时样式问题 (#200)您好，经过您在QQ群反馈的demo，在 submit 回调中不要直接写 onSub() 而是应该写 onSub。因为你写的是 onSub() 所以它并不会执行（因为在组件初始化渲染template的时候已经执行完了，拿到了onSub的返回值 undefined ，所以当您使用组件回调时，真正调用的是 undefined 而不是您的期望 onSub）

**Comment by supergaojian** [comment]
:maxlength="6" 您这里应该这样写的，而不是 maxlength=6

**Comment by yushi105** [comment]
好的，谢谢您，我稍后再试试发自我的华为手机-------- 原始邮件 --------发件人： supergaojian <notifications@github.com>日期： 2019年10月21日周一 18:51收件人： didi/mand-mobile <mand-mobile@noreply.github.com>抄送： 雨逝 <yushi105@163.com>, Comment <comment@noreply.github.com>主    题： Re: [didi/mand-mobile] 使用验证码框控件时，验证码长度为6位且弹窗显示时样式问题 (#200):maxlength="6" 您这里应该这样写的，而不是 maxlength=6
