### ISSUE TITLE
某些浏览器下打开一片空白

### ISSUE THREAD

**Issue by ShirlyChan** [didi/mand-mobile#203]
在vue项目中引入了mand-mobile，发现在钉钉，qq浏览器中页面都是一片空白，去除mand-mobile组件页面就能显示，有谁知道是什么原因吗

**Comment by xxyan0205** [comment]
请提供下一些版本信息，或者查看是否有报错信息，如果可能提供下可复现demo的链接，看下下面的官方demo集合是否有问题
https://didi.github.io/mand-mobile/examples

**Comment by sakuraLili** [comment]
我也遇到了相同的问题，不止是在钉钉里面打不开，在Android5.1中也是一片空白。我使用的是定制主题时，.babelrc配置如下：
"plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "import",
      {
        "libraryName": "mand-mobile",
        "libraryDirectory": "components"
      }
    ]
  ],

发现：
[
   "import",
   {
      "libraryName": "mand-mobile",
      "libraryDirectory": "components"
   }
]
页面才能显示，怎么在使用定制主题时，不是一片空白呢？

**Comment by xxyan0205** [comment]
使用自定义主题功能需要使用源码，所以按需加载的配置需指定`"libraryDirectory": "components"`

主题相关问题可以查看
https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E4%B8%BB%E9%A2%98%E5%AE%9A%E5%88%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88

主题相关文档可以查看
https://didi.github.io/mand-mobile/#/zh-CN/docs/theme

如果使用vue cli可以参考demo
https://github.com/mand-mobile/vue-cli3-example/tree/custom-theme

**Comment by xxyan0205** [comment]
@sakuraLili 如果方便的话 可以在github创建个工程，用最少的代码复现下问题

**Comment by tzz722** [comment]
@xxyan0205 https://github.com/tzz722/webpack-multiple 使用定制主题时在企鹅系浏览器空白

**Comment by supergaojian** [comment]
> @xxyan0205 https://github.com/tzz722/webpack-multiple 使用定制主题时在企鹅系浏览器空白

按照提供的仓库调试看到您使用的是服务端渲染，mand-mobileV1.x暂时不支持服务端渲染，我们会在2.0中支持服务端渲染
