### ISSUE TITLE
浏览器引入方式

### ISSUE THREAD

**Issue by zxk175** [didi/mand-mobile#205]
如何使用Dialog组件

已解决 
```
 Vue.use(window['mand-mobile']);
```

**Comment by zxk175** [comment]
![image](https://user-images.githubusercontent.com/10259995/46596618-d26b5e80-cb0f-11e8-9a75-610eb4c68856.png)
样式不兼容移动端

**Comment by xxyan0205** [comment]
默认lib下为px单位，如果没做相应的缩放适配就是这种问题，你可以对`view-port`进行相应的缩放，或者使用lib-vw（单位为vw/vh）下的bundle
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=产出包目录
