### ISSUE TITLE
ScrollView组件在页面刷新后无法下拉到底

### ISSUE THREAD

**Issue by CeraceLee** [didi/mand-mobile#207]
#### **Mand Mobile Version**

1.6.1

#### **OS Version & Browser Version**

win10 chrome/ android 8.0 

#### **Recurring Links**

官方示例，粘性标题&配合TabBar能明显看见

#### **Recurring Steps**

刷新页面，再向下滑动列表

#### **Expectant Behaviors**

正确滑动到底部

#### **Actual Behaviors**

无法拉至底，还有很长一段距离才到底部，就会发生弹回效果

**Comment by CeraceLee** [comment]
> demo中`padding-top`加到了.scroll-view上导致`.scroll-view-container`整个被挤下去了，`padding-top`加到`.scroll-view-container`上就可以了



> demo中`padding-top`加到了.scroll-view上导致`.scroll-view-container`整个被挤下去了，`padding-top`加到`.scroll-view-container`上就可以了

就拿最后一个demo来说，未刷新前能下拉到4-2的位置，刷新后只能拉到2-2的位置

**Comment by xxyan0205** [comment]
> > demo中`padding-top`加到了.scroll-view上导致`.scroll-view-container`整个被挤下去了，`padding-top`加到`.scroll-view-container`上就可以了
> 
> 就拿最后一个demo来说，未刷新前能下拉到4-2的位置，刷新后只能拉到2-2的位置

具体哪些机型可以复现？

**Comment by CeraceLee** [comment]
> > > demo中`padding-top`加到了.scroll-view上导致`.scroll-view-container`整个被挤下去了，`padding-top`加到`.scroll-view-container`上就可以了
> > 
> > 
> > 就拿最后一个demo来说，未刷新前能下拉到4-2的位置，刷新后只能拉到2-2的位置
> 
> 具体哪些机型可以复现？
我尝试了一下，这边win10 chrome（69）以手机模式浏览，所有的型号都能出现这个问题

**Comment by xxyan0205** [comment]
ios/android 上是否能复现？

**Comment by xxyan0205** [comment]
> > 具体哪些机型可以复现？
> > 我尝试了一下，这边win10 chrome（69）以手机模式浏览，所有的型号都能出现这个问题
ios/android 上是否能复现？

**Comment by CeraceLee** [comment]
> ios/android 上是否能复现？

手边没有ios的机器，安卓是能复现这个问题的，反馈信息的OS Version & Browser Version有提及

**Comment by xxyan0205** [comment]
> > ios/android 上是否能复现？
> 
> 手边没有ios的机器，安卓是能复现这个问题的，反馈信息的OS Version & Browser Version有提及

需要提供手机机型和使用的浏览器，我试了下安卓8.0的小米mix，华为p20 pro没有复现

**Comment by CeraceLee** [comment]
> > > ios/android 上是否能复现？
> > 
> > 
> > 手边没有ios的机器，安卓是能复现这个问题的，反馈信息的OS Version & Browser Version有提及
> 
> 需要提供手机机型和使用的浏览器，我试了下安卓8.0的小米mix，华为p20 pro没有复现

一加3t via浏览器 Android 8.0

**Comment by xxyan0205** [comment]
> > demo中`padding-top`加到了.scroll-view上导致`.scroll-view-container`整个被挤下去了，`padding-top`加到`.scroll-view-container`上就可以了
> 
> 就拿最后一个demo来说，未刷新前能下拉到4-2的位置，刷新后只能拉到2-2的位置

`刷新后只能拉到2-2的位置`也是示例中的问题，rollup构建示例时异步加载页面存在问题，dom元素的尺寸获取有误导致scroller滚动异常。所以从目录页进入没有问题，直接加载（刷新）当前页就有问题。

**Comment by ChineseDon** [comment]
我在用这个ui框架的scrollview，页面使用浏览器刷新后，就无法滚动到底部 ，只能滚动回弹部分

**Comment by xxyan0205** [comment]
> 我在用这个ui框架的scrollview，页面使用浏览器刷新后，就无法滚动到底部 ，只能滚动回弹部分

`auto-reflow`打开了么？

**Comment by ChineseDon** [comment]
没有使用vue-cli3-example，mand-mobile-template初始化项目，直接用的是vue-cli，然后把mand-mobile作为组件使用，已经使用了px2rem。

**Comment by ChineseDon** [comment]
尺寸是正常的，没有类似responsive.js的操作，但就是滚动不了，在mounted查了scrollview的高度，clientHeight是大于视窗高度的。

**Comment by xxyan0205** [comment]
> 尺寸是正常的，没有类似responsive.js的操作，但就是滚动不了，在mounted查了scrollview的高度，clientHeight是大于视窗高度的。

方便的话，提供一个可复现问题的代码仓库或者用codesandbox

**Comment by ChineseDon** [comment]
我现在写了个demo，搞不懂为什么会没用。https://github.com/ChineseDon/mandmobile/tree/master/mandmobile里面的components文件夹下的scroll.vue文件

**Comment by mylesshie** [comment]
这个问题是否给予解决了？目前使用到这个组件也出现这个问题，只有回弹效果，无法滑动到最底部

**Comment by mylesshie** [comment]
使用方法错误，已ok

**Comment by Vector-SMG** [comment]
@mylesshie 请问下怎么解决的呢？

**Comment by dream110120** [comment]
同发现这个问题，scrollView滚动，第一次使用正常，后面浏览器刷新后，出现异常，只能滚动一小部分就会回弹。

**Comment by chuangdao** [comment]
现在这个问题还存在，无法滚动到底，放开后 就反弹到顶。
