### ISSUE TITLE
小程序的支持

### ISSUE THREAD

**Issue by weihongyu12** [didi/mand-mobile#220]
现在很多UI框架都支持**微信小程序**的开发，我希望mand-mobile也能出一个

除了微信小程序，在金融场景，我认为也应该对**支付宝小程序**做相应的支持

不知道mand-mobile是否有这样的计划？

**Comment by xxyan0205** [comment]
目前的UI框架大多都是同一套视觉用小程序原生重新实现，因为人力和成本官方目前还没法直接完全重新做其他平台的实现。当然，mand-mobile有支持微信小程序的计划并且之前也已经开始，但是因为一些技术原因被阻塞（原计划是2.0，目前只能放到3.0中了），后期技术方案还需重新评估。

**Comment by weihongyu12** [comment]
值得期待

**Comment by xxyan0205** [comment]
> 值得期待

如果有好的方案可欢迎提建议。

**Comment by shiny** [comment]
现在 2021 年了，3 还没出来
