### ISSUE TITLE
能不能与cube-ui等其他组件混用？

### ISSUE THREAD

**Issue by chenweiyj** [didi/mand-mobile#222]
#### **Mand Mobile Version**

1.6.1
#### **OS Version & Browser Version**

macos 10.13.6
chrome 69

#### **Node Version, Package Management Tool**

node 8.11
npm 5.6

#### **Expectant Behaviors**

能与cube-ui混用吗？我需要使用一些通用组件，如TabBar、NavBar等

**Comment by xxyan0205** [comment]
理论上可以，但是需注意部分工程化配置的相互独立，比如`rem`转换比例，stylus的一些配置等，配置可能会比较复杂。
