### ISSUE TITLE
this.$refs.scrollView.finishLoadMore() 找不到property `finishLoadMore`

### ISSUE THREAD

**Issue by chenweiyj** [didi/mand-mobile#231]
#### **Mand Mobile Version**

1.6.1
#### **OS Version & Browser Version**

macos 10.13.6
chrome 69

#### **Node Version, Package Management Tool**

npm 8

#### **Recurring Steps**

用的typescript，代码中`this.$refs.scrollView.finishLoadMore()` 编译报错
```
Property 'finishLoadMore' does not exist on type 'Element | Element[] | Vue | Vue[]'.

Property 'finishLoadMore' does not exist on type 'Element'.
```
types/index.d.ts没导出这个方法

**Comment by xxyan0205** [comment]
types/index.d.ts 无法导出$refs下的成员类型

(this.$refs. scrollView as any). finishLoadMore()
