### ISSUE TITLE
button组件绑定点击事件，事件内容为触发另一个按钮的点击事件，结果无法触发（测试机ios10 iphone6s），并且该组件只能结合fastclick来使用

### ISSUE THREAD

**Issue by StriveTo** [didi/mand-mobile#233]

**Comment by xxyan0205** [comment]
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=FastClick
https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile

**Comment by StriveTo** [comment]
目前，只有6s测试机出现这种问题，解决方法已试，不改变元素情况下，没有解决问题，示例代码（vue）
<template>
<input ref="file"> // 没有触发
<md-button @click='click' >点击</md-buton>
</template>
<script>
click() {
   this.$refs.file.click()
}
</script>

**Comment by xxyan0205** [comment]
mand-mobile的版本是什么？

**Comment by StriveTo** [comment]
最新的

**Comment by StriveTo** [comment]
我这边是今天上午更新的，因为我看了button组件你们提交解决了一些浏览器兼容问题，跟fastclick版本有关系吗？

**Comment by xxyan0205** [comment]
https://didi.github.io/mand-mobile/examples/#cashier

麻烦试下上面示例中的一些按钮点击正常么？

**Comment by StriveTo** [comment]
正常的

**Comment by xxyan0205** [comment]
确认下mand-mobile是否最新版本，fastclick的版本，如果可以使用codesandbox创建一个复现问题的demo
