### ISSUE TITLE
scroll view 没有设置高度的时候无法触发endReached

### ISSUE THREAD

**Issue by chenweiyj** [didi/mand-mobile#234]
#### **Mand Mobile Version**

1.6.2

#### **OS Version & Browser Version**

macos 10.13 
chrome 69

#### **Node Version, Package Management Tool**

node8
yarn 1.9.4

#### **Actual Behaviors**

scroll view 没有设置高度的时候无法触发endReached。
我需要除去nav bar，剩下的都是给scroll view，不同设备高度不可知，而且我又是用px2rem自动转换的。
这种情况怎么用scroll view？

**Comment by xxyan0205** [comment]
使用flex布局

**Comment by chenweiyj** [comment]
@xxyan0205 有没有示例

**Comment by xxyan0205** [comment]
> @xxyan0205 有没有示例

这个本身与Scrollview组件没有直接关系，是如何实现除去NavBar以外的正文区域的高度自适应，然后Scrollview高度只要充满正文区域即可。

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oo1yzpvqn6)

**Comment by chenweiyj** [comment]
> > @xxyan0205 有没有示例
> 
> 这个本身与Scrollview组件没有直接关系，是如何实现除去NavBar以外的正文区域的高度自适应，然后Scrollview高度只要充满正文区域即可。
> 
> [![Edit Vue Template](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/oo1yzpvqn6)

你这样写loadmore是无法执行的，scroll-view检测不到到底了

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/34xly66lzq)

**Comment by xxyan0205** [comment]
之前漏写了overflow:hidden
