### ISSUE TITLE
ImageReader

### ISSUE THREAD

**Issue by isMyShell** [didi/mand-mobile#235]
#### **Actual Behaviors**

ImageReader 组件 无法多选

**Comment by xxyan0205** [comment]
请按模板问题提供基本信息，谢谢。

**Comment by isMyShell** [comment]
安卓手机是否无法进行多选？

**Comment by xxyan0205** [comment]
> 安卓手机是否无法进行多选？

部分安卓机不支持 https://caniuse.com/#feat=input-file-multiple

**Comment by isMyShell** [comment]
好的 谢谢
