### ISSUE TITLE
对于scoped scss定制无效

### ISSUE THREAD

**Issue by chenweiyj** [didi/mand-mobile#236]
#### **Mand Mobile Version**

1.6.3
#### **OS Version & Browser Version**

macos 10.13 chrome 69

#### **Node Version, Package Management Tool**

node8

#### **Expectant Behaviors**

组件内样式覆盖无效。
如 ..md-input-item.is-title-latent .md-input-item-title的字体颜色无法覆盖。因为我不同的vue页面都有用到input item，不同页面的颜色会不一样，不能用全局样式。

**Comment by xxyan0205** [comment]
```vue
<template>
  <md-input-item class="custom-input-item0"></md-input-item>
  <md-input-item class="custom-input-item1"></md-input-item>
</template>

<style lang="scss">
.md-input-item{
  &.custom-input-item0{
    // ...
  }
  &.custom-input-item1{
    // ...
  }
}
</style>
```

**Comment by chenweiyj** [comment]
> ```
> <template>
>   <md-input-item class="custom-input-item0"></md-input-item>
>   <md-input-item class="custom-input-item1"></md-input-item>
> </template>
> 
> <style lang="scss">
> .md-input-item{
>   &.custom-input-item0{
>     // ...
>   }
>   &.custom-input-item1{
>     // ...
>   }
> }
> </style>
> ```

如果是伪代码的自定义呢？比如:placeholder, :before等的颜色

**Comment by gebilaoxiong** [comment]
@chenweiyj 
看看是这个吗

https://vue-loader-v14.vuejs.org/zh-cn/features/scoped-css.html#%E6%B7%B1%E5%BA%A6%E4%BD%9C%E7%94%A8%E9%80%89%E6%8B%A9%E5%99%A8
