### ISSUE TITLE
[Toast] call Toast.hide immediately after Toast.loading is useless

### ISSUE THREAD

**Issue by Akimyou** [didi/mand-mobile#242]
Toast.hide 的行为有些异常，例如调用 Toast.loading 之后立即调用 Toast.hide 无效。

https://github.com/didi/mand-mobile/blob/master/components/popup/index.vue

在这里发现， `this.isPopupBoxShow = true` 在 hide 和 show 的处理不一致。
可能在 hide 函数中，也需要把 `this.isPopupBoxShow = true` 包在 nextTick 中。

#### **Mand Mobile Version**
1.5.2

#### **OS Version & Browser Version**
macOS 10.13.4 (17E199) & Chrome 70

#### **Recurring Steps**

```js
this.$toast.loading('loading...')
this.$toast.hide()
setTimeout(() => {
  this.$toast.hide()
}, 1000)
```

#### **Expectant Behaviors**
toast is hide by `this.$toast.hide()`

#### **Actual Behaviors**
toast is hide util setTimeout

https://github.com/didi/mand-mobile/blob/master/components/popup/index.vue

```js
    // MARK: private methods
    $_showPopupBox() {
      this.isPopupShow = true
      this.isAnimation = true
      // popup box enter the animation after popup show
      this.$nextTick(() => {
        this.isPopupBoxShow = true 
        /* istanbul ignore if */
        if (process.env.NODE_ENV === 'testing') {
          this.$_onPopupTransitionEnd()
        }
      })
      this.preventScroll && this.$_preventScroll(true)
    },
    $_hidePopupBox() {
      this.isAnimation = true
      this.isPopupBoxShow = false  // HERE: may be need wrap by this.$nextTick()
      this.preventScroll && this.$_preventScroll(false)
      this.$emit('input', false)
      /* istanbul ignore if */
      if (process.env.NODE_ENV === 'testing') {
        this.$_onPopupTransitionEnd()
      }
    },
```

**Comment by Akimyou** [comment]
这个问题打算什么时候发布呢，它正困扰着我们。

**Comment by duxinxiao** [comment]
@xxyan0205 你这个 commit 没有解决本质问题啊，出问题的组件是 popup，你只把 toast 改了

**Comment by xxyan0205** [comment]
> 这个问题打算什么时候发布呢，它正困扰着我们。

争取周一前
