### ISSUE TITLE
[DatePicker] changed default-date prop not update picker default select

### ISSUE THREAD

**Issue by moonou** [didi/mand-mobile#243]
#### **Mand Mobile Version**
1.6.3  
#### **OS Version & Browser Version**

iOS 12

#### **Node Version, Package Management Tool**
Node 10.13.0, Yarn

#### **Recurring Links**
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7r3x98y0q)

#### **Recurring Steps**

DatePicker组件default-date prop设置为2018-11-26，点击选择时间唤起DatePicker，选择器默认选择到2018-11-26，在confirm事件中变更default-date的值为2018-11-30之后，再次唤起DatePicker。

#### **Expectant Behaviors**

更新默认选择值之后，组件的默认选择应该进行更新

#### **Actual Behaviors**
更新默认选择值之后，组件没有更新选择，而是默认最初设置的默认值。如果不更新默认值，那么下次唤起picker会是上次的选择的。

**Comment by xxyan0205** [comment]
给DatePicker加个key，当更改`default-date`的同时更改下key值
