### ISSUE TITLE
[Button] Click feedback cause some error in old Safari (IOS10)

### ISSUE THREAD

**Issue by Akimyou** [didi/mand-mobile#244]
IOS 10 的 Button 有兼容性问题，表现为无法点击，点击反馈无效

#### **Mand Mobile Version**
1.6.4

#### **OS Version & Browser Version**
macOS 10.13.4 (17E199) & Chrome 70

#### **Recurring Steps**

Use `md-button ` in IOS 10 simulator.

#### **Expectant Behaviors**
Button work fine

#### **Actual Behaviors**
Button no work and can't see the feedback effect.

---

https://github.com/didi/mand-mobile/blob/master/components/button/index.vue

Old safari `:active` behavior have some problem.
https://stackoverflow.com/questions/3885018/active-pseudo-class-doesnt-work-in-mobile-safari

May need add the `ontouchstart=""` at `button`

```html
<template>
  <button
    type="button"
    class="md-button"
    :class="[type, size, icon ? 'with-icon' : '']"
    :disabled="disabled"
    v-on="$listeners"
    ontouchstart="" // here
  >
    <div class="md-button-inner">
      <md-icon v-if="icon" :name="icon"></md-icon>
      <slot></slot>
    </div>
  </button>
</template>
```

The click feedback layer will eat click event, may need add `pointer-events none`

```css
  &::before
    absolute-pos()
    display none
    content ''
    position absolute
    box-sizing border-box
    pointer-events none // here
  &:active::before
    display block
```

**Comment by xxyan0205** [comment]
pointer-events none 会击穿点击，建议使用fastclick

**Comment by Akimyou** [comment]
300ms 的问题好像可以这么解决，我们不太想要 fastclick，文档里面也没有写需要依赖 fastclick 吧

https://thx.github.io/mobile/300ms-click-delay
