### ISSUE TITLE
关于drop-menu的bug

### ISSUE THREAD

**Issue by cnTomato** [didi/mand-mobile#251]
#### **Mand Mobile Version**

最新版本 v1.6.5

#### **Recurring Links**

[https://codesandbox.io/s/myq87vkzv9](https://codesandbox.io/s/myq87vkzv9)

#### **Recurring Steps**

多列下拉选择，初始化仅设置一个item为default-value，先点击未设置default-value列没问题，然后点击已设置default-value列，再看未设置default-value，就存在了selected选项，不知道这样描述问题有没说清楚
![image](https://user-images.githubusercontent.com/12791216/49721601-a00be800-fc9d-11e8-9f05-02e9defd0953.png)

#### **Expectant Behaviors**

设置一列default-value，其他不受影响

**Comment by supergaojian** [comment]
问题原因：drop-menu内部依赖了radio组件，是由于radio组件在更新options之后并没有重置内部的selectedIndex导致问题出现

**Comment by maozhenzhong** [comment]
@supergaojian 你是怎么解决的。我现在遇到这个问题，不能初始化
