### ISSUE TITLE
样式按需加载, stylus-loader配置

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#26]
参考有赞vant，支持css按需加载  [https://www.youzanyun.com/zanui/vant#/zh-CN/quickstart](https://www.youzanyun.com/zanui/vant#/zh-CN/quickstart)

``` 
"plugins": [
    ["import", {
      "libraryName": "vant",
      "libraryDirectory": "es",
      "style": true
    }]
  ]
```

### 项目版本
1.0.4

### 操作系统版本/浏览器版本
chrome

### Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
9.0

### 重现链接(尽量以CodeSandbox重现)
无

### 重现步骤
无

### 期待行为
无

### 实际行为
无

**Comment by lucker2046** [comment]
感谢issue，但css按需加载我们已经支持。用户只需要在代码中配置css-loader即可。

**Comment by zlab** [comment]
如何配置呢，我增加了styles-loader，并没有生效

**Comment by lucker2046** [comment]
我添加了个例子

**Comment by lucker2046** [comment]
我们的按需加载和有赞的思路不太一样，我们会在lib/xxx_components/index.js 文件中自动的引入该组件自身所用到的css依赖，当然，这需要构建工具(webpack，rollup...)提供对模块化引入css的支持，比如webpack就需要配置css-loader，我们尽量减少了对依赖的分析环节，保证js和css是天然存在依赖层级关系的。对于配置了babel-plugin-import的用户而言，这种改动是透明的，你可以放心使用，不过我们还是建议把babel-plugin-import的style属性设置为false，用来屏蔽不同构建工具分析依赖时行为的差异

**Comment by zlab** [comment]
```
error An unexpected error occurred: "http://artifactory.intra.xiaojukeji.com:80/artifactory/api/npm/npm/globby/download/globby-7.1.1.tgz: getaddrinfo ENOTFOUND artifactory.intra.xiaojuke
ji.com artifactory.intra.xiaojukeji.com:80".
```

**Comment by zlab** [comment]
这样写会有问题
``` js
import Vue from 'vue'
import App from './App'

import { Button } from 'mand-mobile'
Vue.component(Button.name, Button);

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  components: { App },
  template: '<App/>'
})
```


错误如下
```
autoprefixer: D:\Web\mand-mobile-demos\css-load-indemend\node_modules\
mand-mobile\lib\button\style\index.css:148:3: You should write display: flex by final spec instead of display: bo
```

**Comment by lucker2046** [comment]
我按照你说的重新修改了demo，并没有出现你说的问题
https://github.com/lucker2046/mand-mobile-demos/tree/master/css-load-indemend
是否可以帮忙看下这个demo和你的有什么差异吗

**Comment by zlab** [comment]
我什么也没改，更新了你的代码，我是windows电脑
![image](https://user-images.githubusercontent.com/2288630/38978367-c31c8a6a-43e9-11e8-89db-038e8c11f18f.png)

**Comment by lucker2046** [comment]
@zlab 
这个问题是由于mand-mobile/XXX_component/style/index.css 已经是通过postcss插件autoprefixer处理过一遍的了，vue-cli会默认对所有.vue文件下引入的css都使用postcss-loader处理一遍。你可以在自己工程中通过配置webpack避免这个warning，或许我们可以在lib中放入未经postcss处理过的css，这两种做法各有什么收益和缺点，我们可以讨论一下
@xxyan0205 @moyus @remote-star
