### ISSUE TITLE
[REM布局] activity-indicator, selector 与 picker 组件中没有必要使用 style 属性设置宽高吧

### ISSUE THREAD

**Issue by Akimyou** [didi/mand-mobile#260]
**Mand Mobile Version**
1.6.5

**Expectant Behaviors**

部分组件会使用 px 计算宽高，并添加到 style 属性上
比如

https://github.com/didi/mand-mobile/blob/2.0/components/activity-indicator/carousel.vue

```html
    <svg
      xmlns="http://www.w3.org/2000/svg"
      :viewBox="viewBox"
      :fill="color"
      :style="{width: `${viewWidth}px`, height: `${size}px`}"
      class="md-activity-indicator-svg carouseling"
    >
      <md-activity-indicator-carousel-circle
        v-for="(value, index) in circleAnimateValues"
        :key="`carousel-circle-${index}`"
        :size="size"
        :index="index"
        :animate-values="value"
      ></md-activity-indicator-carousel-circle>
    </svg>
```
selector 与 picker 组件中也有类似的情况

https://github.com/didi/mand-mobile/blob/master/components/selector/index.vue
https://github.com/didi/mand-mobile/blob/master/components/picker/picker-column.vue

这种 style px 设置宽高在 rem 布局下存在问题。其实可以完全不提供类似的接口，不默认设置 style px 宽高。用户可以方便地覆盖样式即可。

感谢，😊

**Comment by xxyan0205** [comment]
有两种原因会用到内联样式，第一种是样式影响多个元素，用户覆盖样式成本较高。第二种是依赖scroller的元素，需js计算相关尺寸和偏移量。
第一种对于高阶用户依然可以样式覆盖，第二种是不希望用户自定义样式。
