### ISSUE TITLE
date picker 显示错误

### ISSUE THREAD

**Issue by zouhangwithsweet** [didi/mand-mobile#262]
#### **Mand Mobile Version**

1.6.0

#### **OS Version & Browser Version**

all

#### **Node Version, Package Management Tool**

all

#### **Recurring Links**

https://codesandbox.io/s/03mq851y0w

#### **Recurring Steps**

maxDate 选 “2019-06-01”（可以改不同的月份）
custom-types="['MM', 'yyyy']"

#### **Expectant Behaviors**

正常渲染2019年之前的 1 - 12 月

#### **Actual Behaviors**

2019及其以前的所有年都只能渲染 1 - 6 月

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/50580719-28407000-0e8d-11e9-9421-f810cb6238a0.png)
如图所示

**Comment by xxyan0205** [comment]
目前还不支持右序排列，只支持”年月日时分“的左序
