### ISSUE TITLE
input-item type=email 在微信浏览器报错

### ISSUE THREAD

**Issue by luotingv1** [didi/mand-mobile#265]
#### **Mand Mobile Version**

 "mand-mobile": "^2.0.0-rc.4",

#### **OS Version & Browser Version**

微信浏览器

#### **Node Version, Package Management Tool**

npm 
#### **Recurring Links**

不需要复现  一个input-item的组件 然后v-model 就报错了

#### **Expectant Behaviors**

修复bug

**Comment by xxyan0205** [comment]
Duplicate of #268
