### ISSUE TITLE
Picker 错位

### ISSUE THREAD

**Issue by liuzhaowei55** [didi/mand-mobile#266]
#### **OS Version & Browser Version**

Chrome，及常用手机浏览器都可复现

#### **Node Version, Package Management Tool**

node：v11.1.0

#### **Recurring Links**

https://codesandbox.io/s/xvq93q302p

#### **Expectant Behaviors**

Picker 组件在使用中存在错位的情况，在第一个选项上方出现了一个空白选项

#### **Actual Behaviors**

https://ws1.sinaimg.cn/large/4f4f9ba7gy1fyy1eq852lj20bg08rglm.jpg

**Comment by xxyan0205** [comment]
浏览器默认的margin， padding是否已去掉？如：
```
*{margin:0;padding:0;}
```

**Comment by liuzhaowei55** [comment]
> 浏览器默认的margin， padding是否已去掉？如：
> 
> ```
> *{margin:0;padding:0;}
> ```

谢谢，有效。

基础项目我是使用 `vue-cli-plugin-mand`生成的，我看到在项目中已经使用了 `normalize.css` ，那这个清除浏览器默认样式的 css 是不是可以在后续开发中去掉？

**Comment by liuzhaowei55** [comment]
> > 基础项目我是使用 `vue-cli-plugin-mand`生成的，我看到在项目中已经使用了 `normalize.css` ，那这个清除浏览器默认样式的 css 是不是可以在后续开发中去掉？
> 
> 这个得看你的项目的具体需求，以及需考虑的兼容范围等。

谢谢。
