### ISSUE TITLE
设计资源，组件库设计源文件，是两倍大小

### ISSUE THREAD

**Issue by shenxiang11** [didi/mand-mobile#267]
现在版本的sketch是1x的的大小，使用设计组件是2倍，十分不方便使用，是否考虑更新为1倍大小

**Comment by xxyan0205** [comment]
在1倍和2倍图之间各有各的好处，选择2倍的原因：
1随着屏幕的越来越大，1倍图逐渐不太用，2倍便于直接导出
2设计效果在手机上更好的显示还原
3设计时减少0.5像素的出现（sketch对齐不太灵敏）
4和研发沟通，ios 安卓端均用2倍图

然后如果实在需要1倍图，、设计稿无论文字还是间距都尽可能的做到是4的倍数，可以再sketch里运用“缩放”功能快速更改

**Comment by PLQin** [comment]
我怎么找不到设计稿的下载地址, 就是 mand-mobile 的设计资源, psd或者sketch都可以

**Comment by PLQin** [comment]
我找到了, 地址在 ; https://didi.github.io/mand-mobile/#/zh-CN/design/other/resource
