### ISSUE TITLE
InputItem type=number 在安卓QQ内置浏览器 v-model 绑定无效

### ISSUE THREAD

**Issue by LLwanran** [didi/mand-mobile#268]
mand-mobile version
1.6.7
Browsers version
安卓 QQ（最新版） X5内核浏览器
Vue version
2.5.17
questions：
InputItem 输入框 type=number时，v-model不会更新值（取值一直为空）

**Comment by xxyan0205** [comment]
在处理原生类型时存在兼容问题，目前可先使用用类型 `digit`
