### ISSUE TITLE
官方模板还是1x，升级到2x后run dev会报错

### ISSUE THREAD

**Issue by bossietech** [didi/mand-mobile#271]

**Comment by xxyan0205** [comment]
目前请参考 https://github.com/mand-mobile/vue-cli3-example

**Comment by yingtianlee** [comment]
Module build failed: Error: D:/solution/flight/ticket/src/styles/theme.styl:2:9
   1| @import '~mand-mobile/components/_style/mixin/util'
   2| @import '~mand-mobile/components/_style/mixin/theme'
--------------^
升级后，定制主题颜色  这是不认识~

**Comment by xxyan0205** [comment]
@import '~mand-mobile/components/_style/global'
@import '~mand-mobile/components/_style/mixin/util'
@import '~mand-mobile/components/_style/mixin/theme.components'
@import '~mand-mobile/components/_style/mixin/theme.basic'
