### ISSUE TITLE
Popup和DatePicker组合使用导致默认日期错误，滑动选择日期只能滚动3个索引，包括会报错

### ISSUE THREAD

**Issue by abj3ct10n** [didi/mand-mobile#272]
#### **OS Version & Browser Version**
MacOS 10.14/Chrome 71.0.3578.98

#### **Recurring Links**
复现链接：[https://codesandbox.io/s/812389k368](https://codesandbox.io/s/812389k368)

#### **Recurring Steps**
使用Popup组件内嵌DatePicker会导致滑动不能超过3个索引。如默认日期是2019-01-11会显示到2015-01-03。

我本来是想在Popup中放两个DatePicker用作时间区间选择的，但是无奈滑动的时候有问题以及默认日期都有问题。
不用Popup自己做一个fixed元素包裹DatePicker是可以的。

**Comment by xxyan0205** [comment]
`DatePicker`内部已经内置了`Popup`，只需将`is-view`设置为false，不太建议外部再套`Popup`，而是建议将多个`DatePicker`拆开使用。

因为在组件初始化时`Popup`是隐藏的，所以`DatePicker`内部的[scroller](https://github.com/didi/mand-mobile/blob/master/components/picker/picker-column.vue#L167)无法正常初始化，需将其初始化[“延迟”到`Popup`展示之后](https://github.com/didi/mand-mobile/blob/master/components/picker/index.vue#L285)。如果以上述复现链接中的代码为例，需做如下改动（省略无关代码，其实相同的逻辑内部已实现了，所以不建议再以这种方式使用）：

```vue
<md-popup v-model="show" position="bottom" @before-show="onPickerShow">
  <md-date-picker
    ref="datePicker"
    is-view
  ></md-date-picker>
</md-popup>
```

```js
export default {
  // ...
  data() {
    return {
      initialed: false
    }
  },
  methods: {
    onPickerShow() {
      if (this.initialed) return
      this.$refs.datePicker.refresh(() => {
        this.initialed = true
      })
    }
  }
}
```

**Comment by abj3ct10n** [comment]
> `DatePicker`内部已经内置了`Popup`，将只需`is-view`设置为假，不太建议外部再套`Popup`，建议而是将多个`DatePicker`拆开使用。
> 
> 在因为组件初始化时`Popup`的英文隐藏的，所以`DatePicker`内部的[滚轮](https://github.com/didi/mand-mobile/blob/master/components/picker/picker-column.vue#L167)无法正常初始化，需将其初始化[“延迟”到`Popup`展示之后](https://github.com/didi/mand-mobile/blob/master/components/picker/index.vue#L285)，如果以上述复现链接中的代码为例，需做如下改动（省略无关代码，其实相同的逻辑内部已实现了，所以不建议再以这种方式使用）：
> 
> ```
> < md-popup  v-model = “ show ”  position = “ bottom ” @ before-show = “ onPickerShow ” >
>   < md-date- 
>     picker ref = “ datePicker ”
>      is-view 
>   > </ md-date- picker >
> </ md-popup >
> ```
> 
> ```js
> export  default {
>    // ... 
>   data（）{
>      return {
>       初始化： 错误
>     }
>   }，
>   方法： {
>      onPickerShow（）{
>        如果（这个。草签）返回
>       此。$ refs。datePicker。刷新（（）=> {
>          此。草签 =  真
>       }）
>     }
>   }
> }
> ```

多谢，主要目前是想做一个时间区间选择，datePicker内置了Popup也只能显示一个，所以我就套了个Popup。
