### ISSUE TITLE
为啥css导出包只有px和vw，怎么没有rem

### ISSUE THREAD

**Issue by liunewshine** [didi/mand-mobile#273]
官网给的方案是使用postcss-pxtorem插件把px转成rem。
但是有个疑问：为啥不直接提供rem包，这样不是就不用转了。

**Comment by xxyan0205** [comment]
rem与适配方案有关，如px与rem的转换比例，设计的是1x, 2x等等，无法统一，所以需要开发者根据自己的适配方案做相关的转换
