### ISSUE TITLE
scrollview 无法水平滚动

### ISSUE THREAD

**Issue by abj3ct10n** [didi/mand-mobile#279]
scrolling-x="true"
autoReflow="true"

scrollView 的contentW(1000)宽度超过containerH(667)的宽度 但是可以垂直滚动，无法水平滚动。。

用 $refs.scrollView.scrollTo(10, 0, true) 也没有作用

**Comment by xxyan0205** [comment]
[![Edit Mand Mobile ScrollView Horizontal](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8200qj049l?autoresize=1&hidenavigation=1&module=%2Fsrc%2FApp.vue)

**Comment by abj3ct10n** [comment]
多谢，查过资料测试解决方法也是给scroll-view-container加了个 display: inline-block; 解决了水平滚动
