### ISSUE TITLE
2.0版的ActionSheet无法控制高度，手动限制高度后也内容无法滚动

### ISSUE THREAD

**Issue by Roachard** [didi/mand-mobile#282]
#### **Mand Mobile Version**

2.0.0-rc.5
#### **OS Version & Browser Version**

Win10 17134, Chrome 70.0.3538.102

#### **Recurring Steps**

1. 令ActionSheet的options初始值为多条数据。
2. 展开ActionSheet。

#### **Expectant Behaviors**

展开后的ActionSheet 高度得以限制，内容可以触摸滚动。

#### **Actual Behaviors**

展开后的ActionSheet 高度没有限制，手动限制后无法用触摸移动（但可以用鼠标滚轮滚动，但这没啥意义）。直接调用静态方法`create`生成的实例也一样。

看了一下[action-sheet.vue源码](https://github.com/didi/mand-mobile/blob/2.0/components/action-sheet/action-sheet.vue)

```HTML
 <md-popup
      v-model="isActionSheetShow"
      position="bottom"
      prevent-scroll
      @show="$_onShow"
      @hide="$_onHide"
    >...
 </md-popup>
```
相比1.6.6版本，这里popup子组件没有`prevent-scroll-exclude` ，ActionSheet组件的props中也没有接收maxHeight。

**Comment by xxyan0205** [comment]
原来的prevent-scroll-exclude再一些情况下也是存在问题，并不完善。另外，设计同学对ActionSheet和Selector在交互和功能层面做了界定，ActionSheet用于展示少数重要的具体动作列表，如登录/登出，删除，列表条目不易超过5条，且不能滚动需全部展示，否则会遮盖住某些重要动作。对于列表条目比较多且需要限制高度的场景，建议使用Selector。

**Comment by Roachard** [comment]
@xxyan0205 好的，谢谢

**Comment by yinxiaorong** [comment]
今天也遇到了这个问题，在浏览器的手机模拟器上面能够正常滚动，但是在手机上就是无法滚动~，文档里面要是有这个体现就更好了

**Comment by liulunlun** [comment]
目前mand-mobile2.5.20,的md-action-sheet还是没有办法在手机上touchmove.尽管我已经使用静态方法创建组件和配置了maxHeight.但是查看源码发现maxHeight根本没有被用到组件里面
```html
  <md-popup
      class="inner-popup large-radius"
      v-model="isActionSheetShow"
      position="bottom"
      prevent-scroll
      @show="$_onShow"
      @hide="$_onHide"
    >
.........
</md-popup>
```
能把prevent-scroll配置成组件的propData可能灵活性更高.
