### ISSUE TITLE
picker多级联动

### ISSUE THREAD

**Issue by I-Liyang** [didi/mand-mobile#283]
#### **Recurring Links**

无

#### **Recurring Steps**

多级联动时我的数据是从后台请求的，已经获取到数据（json有值），但是不刷新数据，需要重新弹出来选择器才有数据

#### **Expectant Behaviors**

获取到数据时刷新队列

#### **Actual Behaviors**

获取到数据不刷新队列

**Comment by xxyan0205** [comment]
哪个版本？

**Comment by xxyan0205** [comment]
https://mand-mobile.github.io/2x-doc/#/zh-CN/docs/components/feedback/picker?anchor=refresh%28callback,%20startColumnIndex%29

**Comment by I-Liyang** [comment]
就是最新的版本，可能是我写法有问题，我的操作是给数组重新赋值，请问还需要进行什么操作吗，我的数据模仿的是https://github.com/didi/mand-mobile/blob/master/components/picker/demo/data/district.js这个js的数据

**Comment by xxyan0205** [comment]
赋值完后要调用refresh方法重新初始化，或给picker增加[key](https://vuejs.org/v2/api/#key)赋值完后修改key值。
```
this.$nextTick(() => {
   this.$refs.picker.refresh()
})
```

**Comment by I-Liyang** [comment]
调用refresh方法初始化的时候会一直默认选中第一条数据，增加key的方法会出现选择框一直重新弹出的问题

**Comment by xxyan0205** [comment]
refresh方法和改变key都是重新初始化组件，包括数据源和默认选中，但是这个得根据你的具体情况加一些状态锁，在合适的时机调用
