### ISSUE TITLE
DetailItem content props

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#285]
#### **Mand Mobile Version**

2.0.0-rc.5

#### **OS Version & Browser Version**

win10 chrome

#### **Expectant Behaviors**

DetailItem content props 支持String,Number
#### **Actual Behaviors**

DetailItem content props 只支持String, 实际情况可能会传入一些Number类型
https://mand-mobile.github.io/2x-doc/#/zh-CN/docs/components/basic/detail-item

**Comment by supergaojian** [comment]
DetailItem主要是展示列表信息的，所以我们最初认为传入的都是文本，后续我们会考虑加入Number

**Comment by supergaojian** [comment]
我们会在后面的版本迭代中加上，感谢您的建议
