### ISSUE TITLE
ActivityIndicator v-model 

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#288]
#### **Expectant Behaviors**

提供显示隐藏api
我是通过v-show处理
#### **Actual Behaviors**

https://mand-mobile.github.io/2x-doc/#/zh-CN/docs/components/basic/activity-indicator?anchor=API

**Comment by xxyan0205** [comment]
内部没有任何操作能够隐藏，不需要提供v-model，v-if/v-show就可以

**Comment by de1ck** [comment]
> 内部没有任何操作能够隐藏，不需要提供v-model，v-if/v-show就可以
我就是是这么处理的
