### ISSUE TITLE
Selector mask 

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#290]
#### **Actual Behaviors**

在children 组件中使用Selector 
![image](https://user-images.githubusercontent.com/26627486/51587262-36792d80-1f1b-11e9-975d-0e00e133b65d.png)

**Comment by xxyan0205** [comment]
在谁的children？从现象上来看是fixed的元素被包在了“absolute元素”里，如果是这种情况，这个组件需要被插入到“absolute元素”外

**Comment by de1ck** [comment]
> 在谁的children？从现象上来看是fixed的元素被包在了“absolute元素”里，如果是这种情况，这个组件需要被插入到“absolute元素”外
之前没有设置max-height 现在设置max-height后的效果 data LIst 是有数据的
![image](https://user-images.githubusercontent.com/26627486/51587988-8d800200-1f1d-11e9-88e1-5bdee9936072.png)
