### ISSUE TITLE
InputItem  type textarea

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#294]
#### **Expectant Behaviors**

希望可以提供一个支持输入多行文本输入框组件

**Comment by xiaozhouwu** [comment]
我也有这种需求😄，希望加上

**Comment by xxyan0205** [comment]
可具体描述下使用场景或者原生textarea不满足的地方，另外如果有必要会新增组件`TextareaItem`，不会再`InputItem`增加textarea类型。

**Comment by de1ck** [comment]
> 可具体描述下使用场景或者原生textarea不满足的地方，另外如果有必要会新增组件`TextareaItem`，不会再`InputItem`增加textarea类型。

@xxyan0205 使用场景：表单提交。原生textarea不满足的地方，功能不够丰富（如：数字统计,适应文本高度, 行数限制等），样式交互问题

**Comment by supergaojian** [comment]
字数统计应该由用户自己去实现，不应该是组件库去做的；
行数限制原生方法就有；
至于适应文本高度可以动态调整行数即可；

**Comment by de1ck** [comment]
> 字数统计应该由用户自己去实现，不应该是组件库去做的；
> 行数限制原生方法就有；
> 至于适应文本高度可以动态调整行数即可；

@supergaojian 
1. 有些组件库本身有实现。如：fusion design 在设置maxLength的时候会显示，当然我还是同意你的说法。
2. 原生属性确实有默认显示的高度（rows）
3. 自适应确实可以通过动态调整行数（监听enter keyword改变rows的值），但这不是原生textarea本身就有的
在自己实现textarea和使用组件库的textarea,我会更倾向于使用组件库的textarea组件。
这个issue对我而言主要想要一个结果，mand-mobile是否会在近期内实现，然后我会有明确的选择。

**Comment by xxyan0205** [comment]
> 3\. 这个issue对我而言主要想要一个结果，mand-mobile是否会在近期内实现，然后我会有明确的选择

相关的功能我们会考虑，也会与UI和交互的同学讨论，是否有金融场景下的使用方式。但从优先级上可能不会是最高，因为我们对于高优基础组件引入的原则是要服务于金融类组件或它本身就可以成为一个金融类组件。
