### ISSUE TITLE
Selector Support Multiple Select

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#296]
#### **Mand Mobile Version**

2.0.0-rc.5

#### **Expectant Behaviors**

Sector 实现 Popup + CheckBox 实现多选

#### **Actual Behaviors**

Selectot 是 Popup + Radio实现 ，不支持多选
目前在Selector中要实现多选只能通过 Popup + CheckBox 实现多选

**Comment by lonelyWalkor** [comment]
很有用，现在的项目中遇到了，需要用，只好自己去实现了一个
