### ISSUE TITLE
2.0版本文档中的链接失效

### ISSUE THREAD

**Issue by chen8ih** [didi/mand-mobile#300]
https://mand-mobile.github.io/2x-doc/#/zh-CN/docs/theme 该文档中的部分链接地址失效，点击查看显示404，如下图所示链接：
![image](https://user-images.githubusercontent.com/12611993/51899088-4a2a0580-23ed-11e9-8966-ba0352bb822b.png)

**Comment by xxyan0205** [comment]
已修复
