### ISSUE TITLE
ImageReader Selector

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#301]
#### **Mand Mobile Version**

2.0.0-rc.5

#### **OS Version & Browser Version**

Android8.1.0 EMUI 8.1.0 huawei P20 & 微信7.0.0

#### **Expectant Behaviors**

支持图片选择

#### **Actual Behaviors**

图片选中后没有效果

**Comment by xxyan0205** [comment]
Android 8.1.0 EMUI 8.1.0 huawei P20， 微信 v7.0.0 未复现上述问题

**Comment by de1ck** [comment]
@xxyan0205 P20微信开启应用分身会出现这问题。

**Comment by xxyan0205** [comment]
在分身微信中，原生的input[type="file"]的change事件没有触发，导致后续无法继续读取图片，可能是系统级的限制。同类的组件都有这个问题。
