### ISSUE TITLE
vue cli3+mand2.0如何引入svg图标

### ISSUE THREAD

**Issue by maows** [didi/mand-mobile#302]
https://github.com/mand-mobile/vue-cli3-example/tree/custom-theme
按照上面的示例配置，svg依然无法正常显示，请帮忙解决一下

**Comment by xxyan0205** [comment]
svg属性加上了么？

**Comment by supergaojian** [comment]
确定是2.0版本么？请先npm list mand-mobile验证

**Comment by maows** [comment]
确认是2.0，

> svg属性加上了么？
![image](https://user-images.githubusercontent.com/6415952/51960616-b3188880-2494-11e9-80dd-01f58f6142af.png)

这个属性是指什么呢，配置就是按照上述示例做的

**Comment by maows** [comment]
问题解决了，没有加上svg属性，谢谢了，例子里面是1.X的版本

**Comment by xxyan0205** [comment]
2.0种新增svg用来标识svg图标,否则默认是字体图标。具体参考文档。
