### ISSUE TITLE
是否能添加左滑删除呢 & NumberKeyboard 数字键盘的小bug

### ISSUE THREAD

**Issue by jokerxm0611** [didi/mand-mobile#303]
·bug
NumberKeyboard 数字键盘 键盘弹出时 遮罩层并没有显示[md-popup-mask]
· 产品业务场景
左滑修改&删除： 数据列表左滑点击对数据进行操作
· 痛点
此控件在数据列表中使用率非常高，希望能添加此功能模块！感谢~

**Comment by xxyan0205** [comment]
> NumberKeyboard 数字键盘 键盘弹出时 遮罩层并没有显示[md-popup-mask]

这不是bug，数字键盘弹出时，就不能有遮罩层，因为要做input的相关交互。
