### ISSUE TITLE
如何 才能使用你们例子里面的样式

### ISSUE THREAD

**Issue by leida1983** [didi/mand-mobile#307]
https://didi.github.io/mand-mobile/#/zh-CN/docs/components/basic/button

这里面的样式  不知道要怎么套用   通过 mand-mobile-template  创建的项目  样式 和你们的不一样 

你比如 button  里面  type 为 primary, warning, disabled, link

压根就没有样式

**Comment by xxyan0205** [comment]
目前mand-mobile-template还没有适配2.x，默认安装的是1.x。如果要使用2.x需要手动修改package.json，重新安装依赖。

**Comment by leida1983** [comment]
OK  解决了 只是有些小问题  不知道 原因  

![image](https://user-images.githubusercontent.com/3463204/52515425-52d4d400-2c56-11e9-9be3-c64dc7e7d51c.png)

**Comment by xxyan0205** [comment]
需要引入reset.css, normalize.css之类的，去除浏览器的默认样式

**Comment by leida1983** [comment]
么么哒   果然搞定  默认的 normalize.css  不行  install  了 reset  就可以了

**Comment by leida1983** [comment]
有没有啥 好点的  适合你们风格的 个人中心的 界面 推荐啊
