### ISSUE TITLE
期望popup可以添加append-to属性

### ISSUE THREAD

**Issue by bossietech** [didi/mand-mobile#309]
官方推荐在popup中使用scrollView，但是再在其中嵌套popup、selector等，内容会被限制在底层的scrollView中

**Comment by xxyan0205** [comment]
selector中是popup + scrollview + radio的结构，为什么外面还要再套popup?

**Comment by bossietech** [comment]
我遇到一个使用场景，提交工作流弹出一个popup1，其中使用嵌套scrollview。
在popup1中，有单选列表选到需要提交的角色，再有一个下拉，来选择提交意见，
这时候selector就嵌套在popup1的scrollview中。

> selector中是popup + scrollview + radio的结构，为什么外面还要再套popup?

**Comment by xxyan0205** [comment]
`append-to`不需要组件提供接口，直接在mounted时`this.$el.appendTo(xxx)`即可。

关于这种交互还是不太建议用这种负责的循环嵌套，建议popup1 与 selector 平级

关于这种交互也建议TabPicker，看是否满足需求
