### ISSUE TITLE
ScrollView 内容少的时候不显示全部加载完成 

### ISSUE THREAD

**Issue by shouwangshe** [didi/mand-mobile#312]
如题
![_20190214180333](https://user-images.githubusercontent.com/26875279/52779333-e22d1d80-3082-11e9-8ea4-5c8de1a11e36.jpg)
在下拉刷新和上拉加载一起使用是，如果下拉刷新后的数据是一条，小于设定的滚动区域高度，也不会显示全部加载完成

**Comment by shouwangshe** [comment]
感谢回复。希望能快点跟新。也不犀利，帮不上忙。目前做项目在使用这块。

**Comment by xxyan0205** [comment]
目前可在这种情况下，手动更改部分字段

```
this.isFinished = true
this.$refs.scrollview.isEndReaching = true
```

**Comment by shouwangshe** [comment]
> 目前可在这种情况下，手动更改部分字段
> 
> ```js
> this.isFinished = true
> this.$refs.scrollview.isEndReaching = true
> ```
哦哦好的。我试试。还有个问题，首次加载，加载的内容太少，就触发不了下拉加载，实际上还有内容，没加载完，这个应该怎么办？我现在是请求的内容大于滚动高度。

**Comment by xxyan0205** [comment]
> 首次加载，加载的内容太少，就触发不了下拉加载

正常情况下拉加载是不受内容和容器尺寸影响的，示例中的“下拉刷新”就是初始内容不足一屏

**Comment by shouwangshe** [comment]
> > 首次加载，加载的内容太少，就触发不了下拉加载
> 
> 正常情况下拉加载是不受内容和容器尺寸影响的，示例中的“下拉刷新”就是初始内容不足一屏

嗯。。没理解你说的。我现在测试是滚动区域得给定一个高度，要不然不会触发下拉加载更多事件。首次请求的内容低于给定高度，下拉也不会加载更多，也是没有触发下拉加载更多事件。实际还有更多内容。我现在就是首次请求的内容设置的条数很大，超过滚动区域高度，好像可以。可能在你提的trigger endReaching event when the content is less than one screen应该会解决吧。

**Comment by shouwangshe** [comment]
> 目前可在这种情况下，手动更改部分字段
> 
> ```js
> this.isFinished = true
> this.$refs.scrollview.isEndReaching = true
> ```

试了一下，引用不到ref.  this.$refs.scrollview是undefined

**Comment by skyshirt** [comment]
> > 首次加载，加载的内容太少，就触发不了下拉加载
> 
> 正常情况下拉加载是不受内容和容器尺寸影响的，示例中的“下拉刷新”就是初始内容不足一屏

上拉加载。内容少的时候不会触发@endReached()

**Comment by MangliZeng** [comment]
> 上拉加载。内容未渲染到屏幕底部时不会触发@endReached()

同问，上拉加载。内容未渲染到屏幕底部时不会触发@endReached()
