### ISSUE TITLE
Icon图片不显示

### ISSUE THREAD

**Issue by songjintao** [didi/mand-mobile#314]
#### **OS Version & Browser Version**

windos 10
chrome 72

#### **Node Version, Package Management Tool**

node 8.11.4

#### **Recurring Steps**

使用vuecli3 
安装vuerouter
安装 vuex
安装 amd moble
复制官方 Icon 例子

#### **Expectant Behaviors**

显示icon

#### **Actual Behaviors**

不显示icon

**Comment by songjintao** [comment]
节点实际默认就是 svg  和api介绍中的默认行为不一致

**Comment by xxyan0205** [comment]
安装的mand-mobile与查看的文档是否版本是一致的？

**Comment by songjintao** [comment]
果然vuecli3的版本是0.1的 谢谢  不过希望能及时更新
