### ISSUE TITLE
对typescript支持问题

### ISSUE THREAD

**Issue by quany** [didi/mand-mobile#316]
#### **Mand Mobile Version**
2.0.0

#### **OS Version & Browser Version**
Mac OS/chrome

#### **Recurring Links**

![image](https://user-images.githubusercontent.com/758700/52848735-6b5b5780-314a-11e9-92a9-e556c37be948.png)

#### **Expectant Behaviors**

typescript 编译不报错误

#### **Actual Behaviors**

typescript 编译错误

**Comment by xxyan0205** [comment]
ts版本是什么？
