### ISSUE TITLE
突然这样了  怎么个整

### ISSUE THREAD

**Issue by leida1983** [didi/mand-mobile#318]
![image](https://user-images.githubusercontent.com/3463204/52916772-ad3cf700-331e-11e9-8dfe-9a9bda77bebf.png)
![image](https://user-images.githubusercontent.com/3463204/52916775-b332d800-331e-11e9-9611-5cfaec1e21e9.png)

**Comment by leida1983** [comment]
全部 都变的很大了

**Comment by supergaojian** [comment]
请确定已经正确配置好响应式，是否引入mand-mobile中的responsive.js

**Comment by supergaojian** [comment]
具体操作请参照 https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87

**Comment by leida1983** [comment]
如果我要和其他的项目兼容在一起呢  怎么操作呢

**Comment by leida1983** [comment]
![image](https://user-images.githubusercontent.com/3463204/52966033-374d9400-33e1-11e9-9244-3c6bd6385f50.png)

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/issues/103

**Comment by leida1983** [comment]
和别的控件发生了冲突，现在用了蠢办法 在你们的控件外面加了一个 class   直接用了 zoom 0.5  解决问题
