### ISSUE TITLE
在新项目中应用了mand-mobile，出现字体和内容区域大一倍问题

### ISSUE THREAD

**Issue by shuxinyun** [didi/mand-mobile#32]
> mand-mobile version/项目版本
1.0.6
> os version & browser version/操作系统版本&浏览器版本
windows10，Opera
> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
node,npm
> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤
我按照官网指示，把mand-mobile引入新项目，按钮可以显示，点击出现预期窗体，但是按钮大一倍，显示内容窗体也大一倍，查看官网例子有zoom:.6,但我的网页中没有，不知道这个是如何设置控制的
> expectant behaviors/期待行为

> actual behaviors/实际行为

**Comment by shuxinyun** [comment]
我是按需引入的

**Comment by xxyan0205** [comment]
官网的demo是为了将移动端的页面在pc端展示进行了固定比例的缩放。mand-mobile产出包样式单位是px，可根据实际的需要做响应式适配(转换rem)，具体可以参考[px to rem](https://didi.github.io/mand-mobile/#/docs/started?anchor=%3Ccode%3Epx%3C%2Fcode%3E%20to%20%3Ccode%3Erem%3C%2Fcode%3E)

**Comment by shuxinyun** [comment]
我按如下设置了webpack.dev.conf.js
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
const poststylus = require('poststylus')
const pxtorem = require('postcss-pxtorem')
var baseWebpackConfig = require('./webpack.base.conf')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')

// add hot-reload related code to entry chunks
Object.keys(baseWebpackConfig.entry).forEach(function (name) {
  baseWebpackConfig.entry[name] = ['./build/dev-client'].concat(baseWebpackConfig.entry[name])
})

**const pxtoremConfig = pxtorem({ rootValue: 100, propWhiteList: [] })**

module.exports = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap })
  },
  // cheap-module-eval-source-map is faster for development
  devtool: '#cheap-module-eval-source-map',
  plugins: [
    new webpack.DefinePlugin({
      'process.env': config.dev.env
    }),
    **new webpack.LoaderOptionsPlugin({
      options: {
        stylus: {
          use: [poststylus(pxtoremConfig)]
        }
      }
    }),**
    // https://github.com/glenjamin/webpack-hot-middleware#installation--usage
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true
    }),
    new FriendlyErrorsPlugin()
  ]
})

**Comment by shuxinyun** [comment]
按您的设置了后，界面有变化，然来顶部md按钮，只显示一半了，但大小不变，页面非mand-mobile控件的顶部栏消失了，好像top=-30的样子！点击按钮显示内容框大小没有变，还是两倍

**Comment by xxyan0205** [comment]
页面有做响应式适配么？

**Comment by shuxinyun** [comment]
项目在没有加mand-mobile之前都很正常，适配的非常好，就是加了后，用了md控件，只有md控件出现问题！

**Comment by xxyan0205** [comment]
之前的适配是怎么做的，方便的话可以贴下简要代码么？另外，之前样式是否使用的是css，是否可能会受到刚才postcss的影响？

**Comment by shuxinyun** [comment]
方便给我一个邮箱，我把项目发给你吧，不大的项目！

**Comment by xxyan0205** [comment]
xuxiaoyan@didichuxing.com

**Comment by shuxinyun** [comment]
邮件已发
