### ISSUE TITLE
[Picker]有没有 调整 picker  的 height  和 line-height  的方法

### ISSUE THREAD

**Issue by leida1983** [didi/mand-mobile#323]
![image](https://user-images.githubusercontent.com/3463204/53062750-d0bd9880-34fc-11e9-8a26-967aeefbb1b4.png)

**Comment by xxyan0205** [comment]
目前还没有相关接口，后边的版本计划增加prop lineHeight，可用于设置选项行高

**Comment by leida1983** [comment]
大概什么时候会发布呢  这个增加这个属性的功能

**Comment by xxyan0205** [comment]
> 大概什么时候会发布呢 这个增加这个属性的功能

计划是本周五(02.22)
