### ISSUE TITLE
源码包能不能包含DINPro-Medium.ttf这个字体文件进来？

### ISSUE THREAD

**Issue by mkanako** [didi/mand-mobile#325]
你们代码直接写死引用你们的cdn地址
但我不想这样，我想放自己本地

目前我只能手动下载这个字体文件，放进自己项目目录去引用，但是这样不优雅，这样文件不是我自己的文件我不想去维护他，希望能直接引用源码里面的

**Comment by artiely** [comment]
我们项目有白名单，非自己的cnd无法加载，同样希望打包到本地。

**Comment by xxyan0205** [comment]
在尽量控制bundle体积的前提下，我们可以讨论并评估是否已base64方式集成，或者是否有其他更好的方案

> 非自己的cnd无法加载

即使金融字体集成进来，图标字体暂时无法集成，体积太大

**Comment by mkanako** [comment]
@xxyan0205 你可能误解我的意思啊，不是集成，无需考虑体积问题，我是说源码提供DINPro-Medium.ttf这个文件，因为我不想去手动下载他回来放进自己项目里面

**Comment by xxyan0205** [comment]
> 源码提供DINPro-Medium.ttf这个文件

可以

**Comment by xxyan0205** [comment]
源码里已包含，但仅用于demo演示，组件内部还是默认使用系统字体。
