### ISSUE TITLE
[DatePicker]月份都是一样的

### ISSUE THREAD

**Issue by shuyanzi** [didi/mand-mobile#328]
#### **Actual Behaviors**

cancel     Date of Birth  ok
1918        Nov               1
1919        Nov               2
1920        Nov               3
1921        Nov               4

**Comment by xxyan0205** [comment]
请提供Vue 版本，以及复现问题的示例 https://codesandbox.io

**Comment by shuyanzi** [comment]
sorry, 是text-render修改了，我拿到的参数格式变了，导致月份替换错误～
