### ISSUE TITLE
如何在@vue/cli3初始化的项目里配置按需引入呢? 

### ISSUE THREAD

**Issue by Andy-Sunbin** [didi/mand-mobile#33]
> mand-mobile version/项目版本
1.0.6
> os version & browser version/操作系统版本&浏览器版本
Mac OS 10.13 Google Chrome 66
> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
npm 9.11
> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤

> expectant behaviors/期待行为
在@vue/cli3初始化的项目里能按需引入, px to rem 配置运行
> actual behaviors/实际行为

**Comment by moyus** [comment]
会在本周末出vue-cli3的demo

**Comment by moyus** [comment]
@Andy-Sunbin 还没开发完

**Comment by xxyan0205** [comment]
https://github.com/mand-mobile/mand-mobile-vue-cli3-example
