### ISSUE TITLE
更新到 2.1.0 报错

### ISSUE THREAD

**Issue by leida1983** [didi/mand-mobile#331]
![image](https://user-images.githubusercontent.com/3463204/53256784-adb10580-3703-11e9-9584-36de53ea1e19.png)

**Comment by xxyan0205** [comment]
抱歉，升级了[rollup-plugin-vue](https://github.com/vuejs/rollup-plugin-vue)之后导致postcss-url失效，css bundle中的图片未被转成inline url，我们正在修复，问题仅影响全量引入的mand-mobile.css，不影响按需加载的部分。
