### ISSUE TITLE
用到H5端，在ios上显示都是正常的，在Android上显示都会大好几倍，请问为什么呢？

### ISSUE THREAD

**Issue by BirchesChen** [didi/mand-mobile#340]

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E5%B0%BA%E5%AF%B8%E5%BE%88%E5%A4%A7%E5%A6%82%E4%BD%95%E5%81%9A%E5%93%8D%E5%BA%94%E5%BC%8F%E9%80%82%E9%85%8D
