### ISSUE TITLE
Toast.hide doesn't work properly

### ISSUE THREAD

**Issue by meijie93** [didi/mand-mobile#341]
场景：请求后台接口时使用Toast.loading展示"加载中"，请求完成后调用Toast.hide隐藏
问题：如果调用方式形如

```javascript
call_api1().then((res) => {
  call_api2()
})
```

就会出现第二个请求的Toast.loading无法被Toast.hide关闭的问题（即使多次调用也无法关闭）

#### **Mand Mobile Version**
出现问题时版本：1.6.0
尝试升级到1.6.8，没有解决

#### **OS Version & Browser Version**

Win10 17134 & Chrome 72

#### **Recurring Steps**

```javascript
// 创建axios实例
const service = axios.create({
  ...
})

// request拦截器
service.interceptors.request.use(config => {
    Toast.loading('加载中')
})

// respone拦截器
service.interceptors.response.use(
  response => {
    Toast.hide()
    return response
  }
)

call_api1().then((res) => {
  call_api2()
})
```

#### **Expectant Behaviors**

Toast提示能够被Toast.hide关闭

#### **Actual Behaviors**

Toast提示无法被Toast.hide关闭

**Comment by xxyan0205** [comment]
请确保call_api2的loading在call_api1的hide之后
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14rqznm4m4?fontsize=14)

**Comment by meijie93** [comment]
@xxyan0205 你好

1. 感谢你的demo。我现在理解无法关闭的原因是因为loading后hide太快导致的？比如
    ```javascript
    Toast.loading('message');
    Toast.hide();
    ```
    就会出现关闭不了的情况
    可是这个https://github.com/didi/mand-mobile/issues/242#issue-384639922 表示已经解决了，有点疑问

2. 目前我的解决方法是在loading时记录下loading的时间，如果请求响应太快（不足100ms）就等待100ms后再调用hide
    ```javascript
    // loading
    localStorage.setItem('toastTime', new Date().getTime())
    Toast.loading('message');
    
    // hide
    let toastTime= localStorage.getItem('toastTime')
    if (new Date().getTime() - toastTime< 100) {
      setTimeout(() => {
        Toast.hide()
      }, 100)
    } else {
      Toast.hide()
    }
    ```

**Comment by xxyan0205** [comment]
> 1. 我现在理解无法关闭的原因是因为loading后hide太快导致的？

目前toast的show和hide是无法同步调用的，因为show内部存在异步逻辑（为了支持内部popup box的动画，需要等待最外层容器展示后再开始执行动画，否则动画无法执行。ps: 目前vue的版本可以同步了），所以当同步调用hide时，popup box还未展示，所以产生关不掉的效果。

当时的那个issue修复后来引发了其他问题，后来又被去掉了。

**Comment by meijie93** [comment]
明白了，谢谢
