### ISSUE TITLE
Mand Mobile 2 sdn来使用需要导入哪些脚本样式呢

### ISSUE THREAD

**Issue by jokerxm0611** [didi/mand-mobile#345]
项目需加新模块 但是之前是用php绑定的数据 想用sdn的方式使用该组件库
具体需要导入哪些文件呢?
文档中只说了 mand-mobile/lib 目录下的 js&css

**Comment by xxyan0205** [comment]
CDN?

**Comment by jokerxm0611** [comment]
<link href=''>
<script src=''>

**Comment by xxyan0205** [comment]
可参考[浏览器引入](https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%3Cstrong%3E%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5%3C%2Fstrong%3E)下载js和css bundle后

```html
<link rel="stylesheet" href="./mand-mobile.css">
<script src="./mand-mobile.umd.js"></script>
```

**Comment by Meqn** [comment]
@xxyan0205 
请问下结合 webpak  externals 如何使用。

```
config.externals = {
        'mand-mobile': 'exports'
      }
```

这样最后 build 运行报错
