### ISSUE TITLE
扫描识别银行卡

### ISSUE THREAD

**Issue by yccq** [didi/mand-mobile#347]
https://didi.github.io/mand-mobile/#/zh-CN/design/principle/intuition
官网这个扫描识别银行卡号的 有实际做吗，没找着。

**Comment by xxyan0205** [comment]
目前H5的还没法实现，只是在native app上有应用。

**Comment by yccq** [comment]
好的 谢谢

我是想找找有没有 H5调浏览器 识别类的。
https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
这个是可以扫描识别二维码。

**Comment by yccq** [comment]
好的 谢谢

我是想找找有没有 H5调摄像头 识别类的。
https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
这个是可以扫描识别二维码。
