### ISSUE TITLE
[Codebox.name]: Codebox 这样引入样式不渲染,所有组件 import Button from 'mand-mobile/lib/button' 这样就可以

### ISSUE THREAD

**Issue by Andy-Sunbin** [didi/mand-mobile#35]
> mand-mobile version/项目版本
1.06
> os version & browser version/操作系统版本&浏览器版本
Mac OS
> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
npm 8.9.7
> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤

> expectant behaviors/期待行为

> actual behaviors/实际行为

**Comment by moyus** [comment]
请详细描述下你的问题

**Comment by zlab** [comment]
@moyus 

所有的组件都是

### 样式会加载
`import Toast from 'mand-mobile/lib/toast';` 

### 样式不会加载
`import {Toast} from 'mand-mobile;`

**Comment by xxyan0205** [comment]
@zlab 如果没有配置`按需加载`，就是全量引入，这种方式需要手动引入css文件，[全量引入](https://didi.github.io/mand-mobile/#/docs/started?anchor=%E5%85%A8%E9%87%8F%E5%BC%95%E5%85%A5)
