### ISSUE TITLE
iPhone 的字体出了问题  其他的 都没问题

### ISSUE THREAD

**Issue by leida1983** [didi/mand-mobile#353]
![image](https://user-images.githubusercontent.com/3463204/54082731-2a272380-4355-11e9-86c2-67a0337e3374.png)

其他的  正常的 

![image](https://user-images.githubusercontent.com/3463204/54082732-2e534100-4355-11e9-8366-acd4094c720d.png)

要怎么解决

**Comment by xxyan0205** [comment]
首先确认下应用方案内是否使用rem单位，且出现问题的手机是否更改过系统字体大小。

组件库提供的是px和vw/vh两种单位（[产出包目录](https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E4%BA%A7%E5%87%BA%E5%8C%85%E7%9B%AE%E5%BD%95)）
