### ISSUE TITLE
virtual-keyboard-vm自定义金融键盘无效

### ISSUE THREAD

**Issue by bwqgithub** [didi/mand-mobile#355]
版本2.0.0
使用virtual-keyboard-vm设置自定义键盘为无小数点键盘，可是调出来的依然是默认键盘。如图。
![QQ截图20190312111627](https://user-images.githubusercontent.com/11193687/54172222-51e2cc80-44b8-11e9-8632-13af3214556c.png)

**Comment by bwqgithub** [comment]
vue 2.6.6

**Comment by xxyan0205** [comment]
我在本地试了下没有付现，请用https://codesandbox.io 提供一个复现问题的示例

**Comment by bwqgithub** [comment]
https://codesandbox.io/s/vqpq1lzz30

**Comment by xxyan0205** [comment]
在`InputItem`初始化时有概率父组件`$refs`还我完成挂载，挂载后也无法触发`InputItem` props更新，所以内部使用的是内置键盘。后面会让`virtualKeyboardVm`支持传递自定义键盘的`ref`信息，避免直接传递引用。

**Comment by xxyan0205** [comment]
fixed@2.1.5
