### ISSUE TITLE
Landscape 开放 mask-closable 属性，点蒙层关闭

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#36]
> mand-mobile version/项目版本
1.0.6
> os version & browser version/操作系统版本&浏览器版本
ios10
> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
yarn1.6
> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤

> expectant behaviors/期待行为
Landscape压缩窗 可以点蒙层关闭
> actual behaviors/实际行为

**Comment by remote-star** [comment]
在1.0.7中已提供该功能
