### ISSUE TITLE
ScrollView组件无法上拉加载更多。附Sandboxes

### ISSUE THREAD

**Issue by gongph** [didi/mand-mobile#360]
#### **Mand Mobile Version**

`"mand-mobile": "1.6.4"`

#### **OS Version & Browser Version**

在手机和 win7 系统都有问题

#### **Node Version, Package Management Tool**

1. Vue@2.5.22
2. Node@8.9.4

#### **Recurring Links**

沙箱地址戳这里 -> https://codesandbox.io/embed/21yy0880op?fontsize=14

#### **Recurring Steps**

鼠标上拉

#### **Expectant Behaviors**

鼠标上拉触发 `@endReached` 事件，实现上拉刷新效果

#### **Actual Behaviors**

鼠标上拉不触发 `@endReached` 事件

**Comment by xxyan0205** [comment]
上述示例中使用的是[全量引入](https://mand-mobile.github.io/1x-doc/#/zh-CN/docs/started?anchor=%E5%85%A8%E9%87%8F%E5%BC%95%E5%85%A5)方式，但并未引入组件库样式，导致`scrollview`容器的高度未设置，造成滑动异常。

**Comment by gongph** [comment]
@xxyan0205  Thanks for help !

**Comment by gongph** [comment]
@xxyan0205 你好，我发现一个奇怪的现象。就是 `@endReached` 事件会执行多次。我的代码：

```html
<md-scroll-view
  ref="scrollView"
  :scrolling-x="false"
  @endReached="handleEndReached"
>
  <div
    v-for="(item, $index) of tabData['PENDINGREVIEW']"
    :key="$index"
    class="scroll-view-item"
  >
    <order-item :data="item"/>
  </div>
  <!-- 加载更多 loading -->
  <md-scroll-view-more
    slot="more"
    :is-finished="isLoadFinished"
  />
</md-scroll-view>
```

```js
export default {
  ...
  methods: {
    handleEndReached() {
      if (this.isLoadFinished) return
      console.log('coming....')
      // -> 这里会输出三遍 coming
      // 输出次数是根据 setTimeout 延时长短
      // 时间越长输出次数越少。不知道为什么?
      // 但是上面的沙箱就没有问题！
      setTimeout(() {
        this.$refs.scrollView.finishLoadMore()
      })
    }
  }
}
```

**Comment by xxyan0205** [comment]
> ```js
> -> 这里会输出三遍 coming
> ```

1.x的`ScrollView`没有内置`endReached`防抖，所以你需要自己对其handler做[debounce](https://www.lodashjs.com/docs/4.17.5.html#debounce)处理。

**Comment by gongph** [comment]
> > ```js
> > -> 这里会输出三遍 coming
> > ```
> 
> 1.x的`ScrollView`没有内置`endReached`防抖，所以你需要自己对其handler做[debounce](https://www.lodashjs.com/docs/4.17.5.html#debounce)处理。

哦，谢谢您的回答！(*￣︶￣)
