### ISSUE TITLE
赞，但是要提个建议，使用通用样式表。否则使用例子中的代码的时候还要自己配config。更通用使用范围才会更广。支持桔厂开源！

### ISSUE THREAD

**Issue by LtHelo** [didi/mand-mobile#363]

**Comment by xxyan0205** [comment]
感谢建议，辛苦再详细说一下“通用样式表”和使用例子是需要配置的config具体是指？

**Comment by LtHelo** [comment]
现在不是使用stylus来预处理css么，更希望的是利用原生css来写例子。

Shawn Xu <notifications@github.com> 于2019年3月16日周六 下午10:21写道：

**Comment by xxyan0205** [comment]
> 更希望的是利用原生css来写例子

好的，之前demo中的stylus仅仅作为示例，可完全替换成css，我们也会逐渐的将demo中的stylus替换成css。

**Comment by GrootWanggg** [comment]
> > 更希望的是利用原生css来写例子
> 
> 好的，之前demo中的stylus仅仅作为示例，可完全替换成css，我们也会逐渐的将demo中的stylus替换成css。

确实是哦，stylus很难去维护，修改，demo里的样式copy到自己项目里头大~市面上还没有stylus转css或者less的工具哎
