### ISSUE TITLE
Swiper's goto function does not go the correct index

### ISSUE THREAD

**Issue by qq1037305420** [didi/mand-mobile#366]
Mand Mobile 2.1.6
![image](https://user-images.githubusercontent.com/28857867/54585237-81fc1380-4a54-11e9-9b40-0d7c1240254c.png)

sampleData = ['0', '1', '2', '3', '4', '5', '6', '7']
this.$refs.swiper.goto(0) => 7
this.$refs.swiper.goto(1) => 1
this.$refs.swiper.goto(2) => 1 (nothing happens)
this.$refs.swiper.goto(3) => 3

### for more details
[新建文本文档.txt](https://github.com/didi/mand-mobile/files/2981849/default.txt)

**Comment by yccq** [comment]
我也遇到这个问题 goto 0的时候 去的是最后一个，然后中间间隔数的偶尔触发不了goto。

一共有0~4 ，下面是我打印的值 如果 k 1 from 0 to 1 是正常的，下面的数值有一些不正常响应。

k 0
Forex.vue?00e8:62 from 4
Forex.vue?00e8:63 to 4
Forex.vue?00e8:67 k 1
Forex.vue?00e8:62 from 0
Forex.vue?00e8:63 to 1
Forex.vue?00e8:67 k 2
Forex.vue?00e8:67 k 3
Forex.vue?00e8:62 from 2
Forex.vue?00e8:63 to 3
3Forex.vue?00e8:67 k 4
Forex.vue?00e8:67 k 2
Forex.vue?00e8:62 from 1
Forex.vue?00e8:63 to 2
