### ISSUE TITLE
期望后续的版本中可以加入模态页组件

### ISSUE THREAD

**Issue by zwq8299174** [didi/mand-mobile#37]
> mand-mobile version/项目版本
V1.0.9
> os version & browser version/操作系统版本&浏览器版本
macOs 10.13.4
> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
NPM 5.8
> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)
[DEMO](https://ionicframework.com/docs/components/#modals)
> recurring steps/复现步骤

> expectant behaviors/期待行为
期望后续的版本中可以加入模态页，类似ionic的modals这样的组件，因为实际开发中很多弹框需要整个页面弹出，类似登录的拦截。还有就是模态页最好可以直接传入组件，可以接收参数，然后有打开和关闭这样的回调方法。[DEMO](https://ionicframework.com/docs/components/#modals)
> actual behaviors/实际行为

**Comment by remote-star** [comment]
可以尝试使用Popup实现类似功能
