### ISSUE TITLE
增加纯CSS Header组件

### ISSUE THREAD

**Issue by dingangang** [didi/mand-mobile#377]
#### **Mand Mobile Version**

v2.1.7
#### **OS Version & Browser Version**

ubuntu 16.04 chrome73

#### **Recurring Links**

建议增加一个Header组件。

#### **Recurring Steps**

组件库缺乏Header组件

#### **Expectant Behaviors**

增加Header组件。大部分到项目中应该都会用到Header组件。虽然也可以自己来写，但是考虑到组件的一致性还是希望能增加一个Header组件。

#### **Actual Behaviors**

缺失Header组件。

**Comment by xxyan0205** [comment]
Duplicate of #256
