### ISSUE TITLE
scrollview返回后再进入无法滑动

### ISSUE THREAD

**Issue by daniyyer** [didi/mand-mobile#378]
#### **Mand Mobile Version**

2.1.4
#### **OS Version & Browser Version**

ios10.3.3 safari/chrome

#### **Node Version, Package Management Tool**

vue-cli3

#### **Recurring Links**

官网例子

#### **Recurring Steps**

第一次进入scrollview加载更多可以获取数据，返回后再进入scrollview后无法滑动

#### **Expectant Behaviors**

返回后再进入scrollview后可以正常滑动

**Comment by Tsite2007** [comment]
解决了吗  我貌似遇到了同样的问题，  进入页面后无法乡下滑动查看更多内容  会直接回弹  不清楚是不是rem布局和框架的js冲突了

**Comment by xxyan0205** [comment]
> 进入页面后无法乡下滑动查看更多内容 会直接回弹

一个可能是容器高度设置不正确导致的，可检查元素查看容器高度是否正确，比如`.md-scroll-view`。
或者可能初始化后内容发生变化，可开启`auto-reflow`

如果以上都没问题，可以用提供复现问题的示例，我们看一下。

**Comment by qq1037305420** [comment]
auto-reflow 应该是这个没开
