### ISSUE TITLE
安装完在chrome显示有问题

### ISSUE THREAD

**Issue by cdwmhcc** [didi/mand-mobile#379]
安装完后显示异常大，用的cli3，按照文档加入了px转rem的代码也不行

**Comment by supergaojian** [comment]
https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E5%B0%BA%E5%AF%B8%E5%BE%88%E5%A4%A7%E5%A6%82%E4%BD%95%E5%81%9A%E5%93%8D%E5%BA%94%E5%BC%8F%E9%80%82%E9%85%8D

**Comment by cdwmhcc** [comment]
> https://github.com/didi/mand-mobile/wiki/FAQ---%E4%B8%AD%E6%96%87#%E4%B8%BA%E4%BB%80%E4%B9%88%E7%BB%84%E4%BB%B6%E5%B0%BA%E5%AF%B8%E5%BE%88%E5%A4%A7%E5%A6%82%E4%BD%95%E5%81%9A%E5%93%8D%E5%BA%94%E5%BC%8F%E9%80%82%E9%85%8D

谢谢，用官方的cli3 demo可以了
