### ISSUE TITLE
vw适合方案时root font-size是否应该去掉？

### ISSUE THREAD

**Issue by 531431988** [didi/mand-mobile#380]

**Comment by xxyan0205** [comment]
`root font-size`不是css中设置的，如果你使用了[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)或者[vue-cli3-example](https://github.com/mand-mobile/vue-cli3-example)，把`responsive.js`引入去掉即可。

**Comment by 531431988** [comment]
> `root font-size`不是css中设置的，如果你使用了[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)或者[vue-cli3-example](https://github.com/mand-mobile/vue-cli3-example)，把`responsive.js`引入去掉即可。

在哪引入的？没找到

**Comment by 531431988** [comment]
找到了，感谢

**Comment by 531431988** [comment]
template index.html 行内js
