### ISSUE TITLE
Progress进度组件进度为0或100时出现小圆点

### ISSUE THREAD

**Issue by zhixinpeng** [didi/mand-mobile#381]
#### **Recurring Steps**

将Progress组件的value设置为0或1

#### **Expectant Behaviors**

0%时只显示borderColor进度条颜色，color高亮进度不应该显示
100%时高亮颜色完整显示，圆环为完美圆形

#### **Actual Behaviors**

0%会出现一个圆点的高亮颜色，会让用户误认为有进度产生。
100%时仔细看能发现与起始点的重叠区域会有一个小圆点的凸起，圆环并非完美的圆形

**Comment by xxyan0205** [comment]
上述期待行为需将 linecap设置为butt

**Comment by zhixinpeng** [comment]
但是我确实需要round的linecap，这样说的话，圆形进度条只能使用butt的linecap，不能设置为round。这样是不是有点问题？
