### ISSUE TITLE
期待改进DropMenu

### ISSUE THREAD

**Issue by skyshirt** [didi/mand-mobile#384]
#### **Expectant Behaviors**

期待改进DropMenu
1、支持二或三层横向级联，可以设置高度，显示可控制的垂直滚动条
2、菜单纵向位置可以任意，否则不置顶会从头上飞下来
3、点击已弹出层之外时，自动隐藏；如果存在二个或以上顶层选项，点击切换下拉菜单

**Comment by supergaojian** [comment]
1、关于集联选择推荐使用 https://didi.github.io/mand-mobile/#/zh-CN/docs/components/feedback/tab-picker
2、请在组件父级增加相对定位即可

**Comment by skyshirt** [comment]
1好像有些不合理，可以在下窗中自定义内容吗，给个slot插槽也可以，对应的事件就OK
2确实有这个问题，父级相对定位也没用，即使将css都写好，刚加载进入页面是对的，如果页面滚动，还是会串的
.md-popup position fixed，改成 absolute可以解决问题

![image](https://user-images.githubusercontent.com/18375810/55295578-42183180-5441-11e9-810e-e9c91195efa8.png)
![image](https://user-images.githubusercontent.com/18375810/55295626-e306ec80-5441-11e9-9347-ed457d58f90c.png)
