### ISSUE TITLE
求mand-mobile-example.js的未压缩文件

### ISSUE THREAD

**Issue by Nemo1986** [didi/mand-mobile#386]
正在学习中，能否提供一份mand-mobile-example.js的未压缩文件。

**Comment by supergaojian** [comment]
https://github.com/mand-mobile

**Comment by xxyan0205** [comment]
* 里面的各个示例来源于 /components/**/demo
* 如果有需要可以fork工程，将[rollup-plugin-example-config.js](https://github.com/didi/mand-mobile/blob/master/build/rollup/rollup-plugin-example-config.js)中uglify插件注释掉，执行`npm run build:example`
