### ISSUE TITLE
swiper

### ISSUE THREAD

**Issue by SmartaFox** [didi/mand-mobile#388]

**Comment by SmartaFox** [comment]
里面的item点击a标签无效    android机子无法跳转

**Comment by supergaojian** [comment]
请详细说明您的问题，或者使用codesandbox提交可复现问题代码，或者加入我们QQ群反馈

**Comment by SmartaFox** [comment]
swiper-item里面嵌入a元素，点击a标签不能跳转，无反应，，，，iphone可以触发

**Comment by xxyan0205** [comment]
`is-prevent` 设置为 `false`
