### ISSUE TITLE
期望所有组件不使用@click.native修饰符

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#39]
## 基本上现有开源Vue UI组件库都不需要加native修饰符

> mand-mobile version/项目版本
1.0.6 

``` js
export default {
  template: '<div @click="onClick"></div>',
 methods: {
    onClick() {
         this.$emit('click');  
    }
  }
}
```

**Comment by moyus** [comment]
如果要给组件添加click事件，是必须要有`native`修饰的。只有`functional`组件或者 `HTML` 原生标签是不需要修饰的。

**Comment by zlab** [comment]
# 以下库都是不需要加native的
## 有赞 https://www.youzanyun.com/zanui/vant
## 饿了么 http://element-cn.eleme.io/#/zh-CN/component/installation
## iview https://www.iviewui.com/

**Comment by moyus** [comment]
**v1.0.8**中`Button`组件已去掉了`.native`修饰符。

**Comment by zlab** [comment]
还有 md-icon
