### ISSUE TITLE
ImageReader 图片选择器 在OPPO R17选择文件无反应

### ISSUE THREAD

**Issue by sunjunvue** [didi/mand-mobile#394]
ImageReader 图片选择器 在OPPO R17选择文件无反应，拍照可以

**Comment by supergaojian** [comment]
请问是在微信浏览器中无效么？

**Comment by sunjunvue** [comment]
是的微信扫描打开的

**Comment by sunjunvue** [comment]
> 请问是在微信浏览器中无效么？

是的微信浏览器

**Comment by supergaojian** [comment]
微信浏览器中推荐使用微信的JS-SDK进行文件选取、拍照的功能，某些机型下使用原生js操作在微信浏览器下无法正常运行
