### ISSUE TITLE
input 的clearable oppo手机不生效

### ISSUE THREAD

**Issue by Adele0** [didi/mand-mobile#396]
#### **Mand Mobile Version**

版本 1.2.1
#### **OS Version & Browser Version**

oppo

#### **Recurring Links**

官网的的示例（PC端--Chrome）也不能清除内容。
https://didi.github.io/mand-mobile/#/en-US/docs/components/form/input-item

#### **Expectant Behaviors**

点击关闭标签，清除内容

#### **Actual Behaviors**

需要双击关闭标签才能清除内容。

**Comment by supergaojian** [comment]
1.您使用的是mand-mobie1.2.1?
2.请确定您使用的vue版本号是多少？
