### ISSUE TITLE
ScrollViewRefresh组件的默认loading样式颜色无法修改

### ISSUE THREAD

**Issue by jameszzX** [didi/mand-mobile#399]
#### **Actual Behaviors**

在自定义主题的变量中没看到可以定义该变量

**Comment by supergaojian** [comment]
请问是使用的哪个版本的mand-mobile？

**Comment by xxyan0205** [comment]
loading样式颜色是`ScrollViewRefresh`内部的`roller`组件决定的，需要通过prop透传，目前`ScrollViewRefresh`还没有这个prop。这个无法通过自定义主题的变量控制。

**Comment by jameszzX** [comment]
回复速度好快！ 对啊。我查看了源码看到是套用了另外一个组件。refresh组件的样式还是挺好看的，就想着改个颜色拿来用。谢谢回复
