### ISSUE TITLE
组件很多确缺失  textarea也没有  indexlist也没有

### ISSUE THREAD

**Issue by Tsite2007** [didi/mand-mobile#401]

**Comment by xxyan0205** [comment]
Mand Mobile是聚焦金融场景的组件库，因此我们会高优解决金融类组件。标题中提到的组件我们也在讨论，讨论的内容是这些组件在金融场景下的一些使用方式和功能。如果有明确的需求，可以直接提。

**Comment by Tsite2007** [comment]
金融组件很多  也很好用   希望内容以后越来越丰富

**Comment by ljh5566** [comment]
textarea建议加上，最基本的组件哦

**Comment by somsne** [comment]
textarea确实建议加上，使用场景还是挺多的。目前项目就碰到了需要textarea的情况，主要集中在需要大量文字输入和查看的地方。

**Comment by xxyan0205** [comment]
Duplicate of #294
