### ISSUE TITLE
Icon图标在微信浏览器里，有时候页面加载完，都是正方形框框

### ISSUE THREAD

**Issue by sunjunvue** [didi/mand-mobile#403]
在微信浏览器里，有时候加载完，字体图标都是框框， 多刷新几次有时候会好，有时候不行。

**Comment by xxyan0205** [comment]
说的是 https://didi.github.io/mand-mobile/examples ?

**Comment by sunjunvue** [comment]
> 说的是https://didi.github.io/mand-mobile/examples？
 就是只要涉及到md-icon 这种的，有时候刷新就会变成框框 “口”（左边是个正方形）

**Comment by xxyan0205** [comment]
首先，那个框框是因为图标字体文件没有被成功加载导致的。有几个问题可以确认下:
什么机型？如果是安卓机，是否有安全软件拦截字体文件加载？或者尝试换个手机时候能够复现同样问题。或者在你自己的项目里也能复现同样问题？

**Comment by sunjunvue** [comment]
> 机型？如果是安卓机，是否有安全软件拦截字体文件加载？或者尝试换个手机时候能够复现同样问题。或者在你自己的项目里也能复现同样问题？

真机上安卓和ios都有时候会出现，在开发者工具里面不会出现。

**Comment by xxyan0205** [comment]
> 真机上安卓和ios都有时候会出现

你运行自己的项目 也会这样么？

**Comment by moyus** [comment]
图标字体采用的是https的资源地址，如果你的项目地址是http协议的，在部分机型上的确会导致载入不同协议资源失败的问题。

**Comment by sunjunvue** [comment]
> 图标字体采用的是HTTPS的资源地址，如果你的项目地址是HTTP协议的，在部分机型上的确会导致载入不同协议资源失败的问题。

应该不是 https的问题，我们线上环境配置的都是https,只有手机刷新的时候会出现，时不时的。有时候能加载出来，有时候出来都是框框
