### ISSUE TITLE
Steps 如何自定义全部的图标

### ISSUE THREAD

**Issue by GodStream** [didi/mand-mobile#405]
#### **Mand Mobile Version**

2.1.7
#### **Expectant Behaviors**

希望可以统一自定义全部步骤的图标

#### **Actual Behaviors**

目前文档只支持当前步骤与已完成步骤的图标自定义，那未完成的步骤如何自定义？

**Comment by xxyan0205** [comment]
目前不支持未完成的步骤的自定义，设计规范中未完成样式固定

**Comment by GodStream** [comment]
目前感觉比较束缚，比如若是有一个需求，需要将图标替换成头像，这个时候就没办法搞了，有计划优化一下吗？

**Comment by xxyan0205** [comment]
可以优化
