### ISSUE TITLE
自己安装的 mand-mobile 没有.postcssrc.js这个文件，手动创建后没有加载。。

### ISSUE THREAD

**Issue by Jackfinal** [didi/mand-mobile#406]
#### **Mand Mobile Version**

` "mand-mobile": "^2.1.7"`
#### **OS Version & Browser Version**

chrome

#### **Node Version, Package Management Tool**

v11.6.0

#### **Recurring Steps**

我先是直接安装的mand-mobile，然后发现页面单位是px，然后查看文档想转换为rem
又安装postcss-pxtorem,完成后发现没有.postcssrc.js文件
于是创建文件.postcssrc.js，并按照mand-mobile-vue-cli3-example 模版写入内容
最后发现文件没有加载执行。。。不知道还需要进行什么操作

**Comment by supergaojian** [comment]
https://cli.vuejs.org/zh/guide/css.html#postcss

**Comment by Jackfinal** [comment]
这个文档我也看了，但是不知道 具体怎么把这段代码加进去。。麻烦能否给一个列子
`module.exports = {
  plugins: {
    'autoprefixer': {},
    'postcss-pxtorem': {
      'rootValue': 100,
      'propWhiteList': []
    }
  }
}`

**Comment by xxyan0205** [comment]
https://github.com/mand-mobile/vue-cli3-example

**Comment by Jackfinal** [comment]
我用了这个例子，是可以的，就是想不明白我自己安装创建为什么不能加载.postcssrc.js文件

**Comment by xxyan0205** [comment]
> 不能加载.postcssrc.js文件

如果你引入的是mand-mobile的源码(components)，配置postcss是没用的，你用更实用poststylus

**Comment by Jackfinal** [comment]
@xxyan0205 能给写一个例子吗？我用的是vue cli3 写在vue.config.js 配置里，写不好。。。

**Comment by Jackfinal** [comment]
我使用的是按需引入

**Comment by supergaojian** [comment]
您好，详细的问题请加入我们的Mand mobile官方交流QQ群493305323咨询
