### ISSUE TITLE
Tabs组件的Pane建议支持滑动切换

### ISSUE THREAD

**Issue by jameszzX** [didi/mand-mobile#407]
#### **Mand Mobile Version**

v2.1.7

#### **OS Version & Browser Version**

chrome

#### **Expectant Behaviors**

Tabs组件的Pane建议支持滑动切换

**Comment by xxyan0205** [comment]
https://codesandbox.io/s/z69yp7my9x?fontsize=14

**Comment by jameszzX** [comment]
对哦这是一个办法哈哈我太蠢了
