### ISSUE TITLE
swiper 初始化

### ISSUE THREAD

**Issue by MangliZeng** [didi/mand-mobile#410]
wiper和弹窗一起使用时，出现bug，如何初始化呢
wiper used with components of landscape,how to initalize? what's the interface

**Comment by supergaojian** [comment]
请详细描述您的问题？您是指在popup中使用了swiper组件么？或者您有可复现的代码么？

**Comment by MangliZeng** [comment]
> 请详细描述您的问题？您是指在popup中使用了swiper组件么？或者您有可复现的代码么？

我结合了Landscape一起使用，md-swiper-item高度为0，我怀疑是初始化问题，但是如果我不跟Landscape一起使用的时候是正常的

**Comment by supergaojian** [comment]
您好，推荐您使用popup结合swiper使用

**Comment by MangliZeng** [comment]
> 您好，推荐您使用popup结合swiper使用
好的，谢谢，我尝试一下，swiper没有暴露出来初始化的接口么

**Comment by xxyan0205** [comment]
> swiper没有暴露出来初始化的接口么

可以在popup show的时候调用一下`this.$refs.swiper.$_resize()`重新初始化swiper尺寸

**Comment by MangliZeng** [comment]
> > swiper没有暴露出来初始化的接口么
> 
> 可以在popup show的时候调用一下`this.$refs.swiper.$_resize()`重新初始化swiper尺寸meiyou

> > swiper没有暴露出来初始化的接口么
> 
> 可以在popup show的时候调用一下`this.$refs.swiper.$_resize()`重新初始化swiper尺寸

没有这个函数$_resize()

**Comment by MangliZeng** [comment]
有谁可以帮帮我这个问题吗？swiper放在弹窗里面会有宽度或者高度为0的问题，swiper这个组件没有暴露重置或者刷新size或者初始化的接口，我要怎么做呢

**Comment by xxyan0205** [comment]
> 没有这个函数$_resize()

你是怎么调用的？

**Comment by MangliZeng** [comment]
> > 没有这个函数$_resize()
> 
> 你是怎么调用的？Swiper上加ref属性了么？
```
<md-popup v-model="isShow">
      <div class="dailogPopup" style="height:300px;">
        <md-swiper ref="swiper"
          :default-index="1"
          :autoplay="0"
          transition="slideY">
          <md-swiper-item :key="$index" v-for="(item, $index) in simple">
            <div
              class="banner-item"
              :style="{'background': `${item.color}`}">{{item.text}}</div>
          </md-swiper-item>
        </md-swiper>
      </div>
    </md-popup>
```
在 mounted勾子里面调用
```
setTimeout(() => {
      console.log(that.$refs.swiper.$_resize())
    }, 20)
```
我打印过this.$refs.swiper的内容，没有$_resize()这个函数

**Comment by xxyan0205** [comment]
> 我打印过this.$refs.swiper的内容，没有$_resize()这个函数

我没猜错的话，你是想写`console.log(that.$refs.swiper.$_resize)`吧 。。。

**Comment by MangliZeng** [comment]
> > 我打印过this.$refs.swiper的内容，没有$_resize()这个函数
> 
> 我没猜错的话，你是想写`console.log(that.$refs.swiper.$_resize)`吧 。。。

of course not!!!

**Comment by xxyan0205** [comment]
> of course not!!!

另外不是在 mounted勾子里面调用，因为此时swiper还被隐藏，无法获取各种尺寸。实在popup的事件show的时候再调用`that.$refs.swiper.$_resize()`

**Comment by MangliZeng** [comment]
> > of course not!!!
> 
> 另外不是在 mounted勾子里面调用，因为此时swiper还被隐藏，无法获取各种尺寸。实在popup的事件show的时候再调用`that.$refs.swiper.$_resize()`，如果你用的是1.x版本，调用`$_reInitItems()`

谢谢指导，学习了
