### ISSUE TITLE
如何动态自定义主题？根据用户的id加载不同的theme.styl文件

### ISSUE THREAD

**Issue by bwqgithub** [didi/mand-mobile#412]
是否有办法动态自定义主题，目前的主题修改方案是项目运行前配置。

**Comment by supergaojian** [comment]
您好，您可以在运行前预设好多个css样式，然后根据用户进入页面后，动态加载不同的css

**Comment by bwqgithub** [comment]
> 您好，您可以在运行前预设好多个CSS样式，然后根据用户进入页面后，动态加载不同的CSS

我想修改styl的颜色变量然后改变整个框架的主题色

**Comment by xxyan0205** [comment]
> 是否有办法动态自定义主题

可以参考我们的调色板，https://github.com/mand-mobile/palette  使用的是css variable方案

**Comment by LiangNex** [comment]
我这边有个类似的情景， 主题参数由服务层动态返回， 页面层根据返回的参数通过js设置主题复写。
看了下好像目前Mand 没提供UI复写的支持，Vuetify有提供这个， 见：
[Vuetify Custom Theme](https://vuetifyjs.com/en/customization/theme#customizing)
麻烦问下这边近期有打算提供这方面的支持吗？
