### ISSUE TITLE
官方demo的picker地区选择，直辖市下的区不显示

### ISSUE THREAD

**Issue by dev-kxy** [didi/mand-mobile#416]
如题，如何修改

**Comment by dev-kxy** [comment]
现在是直辖市下的区不显示，想要显示的话如何修改

**Comment by supergaojian** [comment]
请确定您的mand-mobile版本

**Comment by dev-kxy** [comment]
2.2.0

**Comment by dev-kxy** [comment]
> 请确定您的mand-mobile版本

2.2.0

**Comment by supergaojian** [comment]
我们的demo只是举例，数据并不全面的

**Comment by dev-kxy** [comment]
> 我们的demo只是举例，数据并不全面的

demo中的数据有直辖市下的区的数据，但就是不显示，似乎是哪里有设置了不显示直辖市范围内的区

**Comment by dev-kxy** [comment]
而且我有全部省市区的数据源，传入组件后还是不显示直辖市下的区

> 我们的demo只是举例，数据并不全面的

**Comment by dev-kxy** [comment]
> 我们的demo只是举例，数据并不全面的

只有直辖市下的区不显示，其他市下面的区都正常显示

**Comment by supergaojian** [comment]
1、请问demo中哪一个直辖市下的没有战术区
2、针对您的数据源请确认是否为picker可识别正确的结构

**Comment by dev-kxy** [comment]
> 1、请问demo中哪一个直辖市下的没有战术区
> 2、针对您的数据源请确认是否为picker可识别正确的结构

北京，天津，重庆等直辖市下的区都不显示，数据源是正确结构

**Comment by dev-kxy** [comment]
> 1、请问demo中哪一个直辖市下的没有战术区
> 2、针对您的数据源请确认是否为picker可识别正确的结构

官网的demo中的数据源也是有北京市下的区的数据的，但同样不显示

**Comment by dev-kxy** [comment]
@ supergaojian 请问如何解决呢

**Comment by dev-kxy** [comment]
> 1、请问demo中哪一个直辖市下的没有战术区
> 2、针对您的数据源请确认是否为picker可识别正确的结构

请问如何解决呢？？？

**Comment by supergaojian** [comment]
请问您的vue版本是多少？

**Comment by dev-kxy** [comment]
> 请问您的vue版本是多少？

2.6.10

**Comment by supergaojian** [comment]
您好，和您确认一下，您是直接copy的demo是吧，有多个picker，且其中有设置defaultIndex

**Comment by dev-kxy** [comment]
> 您好，和您确认一下，您是直接copy的demo是吧，有多个picker，且其中有设置defaultIndex

是的，直接copy的demo，然后把opstions替换成我自己的完整的省市区json。defaultIndex也有设置，但是直辖市下的三级不显示，一级二级都正常显示

**Comment by supergaojian** [comment]
你可以为每一个picker加上专属key值

**Comment by dev-kxy** [comment]
emmm.没明白，我现在是不知道问题出在哪，而且也不报错，就是单纯的不展示直辖市下的3级区域

**Comment by dev-kxy** [comment]
> 你可以为每一个picker加上专属key值

emmm.没明白，我现在是不知道问题出在哪，而且也不报错，就是单纯的不展示直辖市下的3级区域

**Comment by supergaojian** [comment]
是的，我得意思是您为每一个picker绑定一个v-key

**Comment by dev-kxy** [comment]
> 是的，我得意思是您为每一个picker绑定一个v-key

emmm,怎么设置呢，please show me the code , i`m a new driver -.-

**Comment by supergaojian** [comment]
<md-picker
      ref="picker0"
      v-model="isPickerShow0"
      :key=“这里设置唯一值”
      :data="pickerData0"
      @confirm="onPickerConfirm(0)"
      title="选择年份"
    ></md-picker>
相关参考：https://cn.vuejs.org/v2/api/#key

**Comment by dev-kxy** [comment]
问题奇迹般地解决了，吼吼。
PickerTrigger5（）中的
pickerDefaultValue设置为[]就好了，官网demo中的pickerDefaultValue也改一下吧，否则 有bug

**Comment by supergaojian** [comment]
这个确实是我们官网demo的bug，不过不是pickerDefaultValue导致的，而是我们没有这是v-key导致的，已经在修复中了

**Comment by dev-kxy** [comment]
> 这个确实是我们官网demo的bug，不过不是pickerDefaultValue导致的，而是我们没有这是v-key导致的，已经在修复中了
噢，原来是这样。非常感谢您的讲解，祝好

**Comment by supergaojian** [comment]
再有问题可以加入我们的官方QQ群

**Comment by dev-kxy** [comment]
> 再有问题可以加入我们的官方QQ群

qq群号是？

**Comment by supergaojian** [comment]
Mand Mobile官方交流群，群号:493305323

**Comment by supergaojian** [comment]
已经找到该问题所在：
由于picker组件中的cascader.js的getDefaultIndex返回了一个不正确的索引值导致了issue问题的出现。

**Comment by xxyan0205** [comment]
fixed @2.2.1
