### ISSUE TITLE
mand mobile 1.x  npm run dev:rollup 编译异常

### ISSUE THREAD

**Issue by Rhain** [didi/mand-mobile#417]
#### **Mand Mobile Version**

mand mobile 1.x

#### **OS Version & Browser Version**

OSX & windows 都可以重现

#### **Node Version, Package Management Tool**

最新版本node.js npm

#### **Recurring Steps**

git clone mand-mobile 
切换到1.x 分支
npm install
npm run dev:rollup

#### **Expectant Behaviors**

正常编译，可以进入example页面

#### **Actual Behaviors**

报错
code:'Plugin_ERROR',
plugin: 'vue',
id: 'home.indemand.vue'

经排查发现依赖的vue-template-es2015-compiler 的版本升级到了最新的1.9x，编译失败。
如果手动指定vue-template-es2015-compiler 版本降到1.6.0 则可以正常编译。

期望可以修复这个bug。

**Comment by xxyan0205** [comment]
不要使用rollup开发，这个只是我们为了测试保留的一个script。建议使用npm run dev

**Comment by Rhain** [comment]
ok， 正式是用webpack来开发么？

**Comment by xxyan0205** [comment]
是的
