### ISSUE TITLE
DatePicker custom-types 中使用“HH”校验错误，提示：Invalid prop: custom validator check failed for prop "customTypes"

### ISSUE THREAD

**Issue by xianyuxmu** [didi/mand-mobile#418]
**问题描述**：DatePicker custom-types 中使用“HH”校验错误，提示：Invalid prop: custom validator check failed for prop "customTypes"

正常数据： :custom-types="["yyyy", "MM", "dd", "HH", "mm"]"

异常数据： :custom-types="["yyyy", "MM", "dd", "hh", "mm"]"

> 请尽快解决！！！

**Comment by supergaojian** [comment]
您好，并不是我们校验错误，是因我们并没有内置‘HH’

**Comment by xianyuxmu** [comment]
@supergaojian  建议可以实现标准的时间格式，以支持"HH"

**Comment by xxyan0205** [comment]
supported @v2.2.2
