### ISSUE TITLE
ScrollView 当第一次加载内容高度没有填充满滚动区时，无法出发下拉加载函数endReached

### ISSUE THREAD

**Issue by MangliZeng** [didi/mand-mobile#421]
内容未渲染到屏幕底部时不会触发@endReached()
我设置了滚动区域的高度是满屏的，如果我第一次加载给了10条数据，刚刚好填充整个滚动区，那我可以下拉继续加载更多触发endReached函数。如果我加载10条数据，没有填充满屏。我下拉刷新时就无法触发下拉加载的函数，怎么办呢？
这个bug在不同手机上出现的就看手机分辨率了，貌似真的不太友好

**Comment by xxyan0205** [comment]
1.x 中的设计不支持在未满一屏时触发`endReached `，2.x 中是支持的。

**Comment by MangliZeng** [comment]
> 1.x 中的设计不支持在未满一屏时触发`endReached `，2.x 中是支持的。
我使用的是"mand-mobile": "^2.0.0-rc.4"这个版本的，也确实存在这个问题

**Comment by xxyan0205** [comment]
> "mand-mobile": "^2.0.0-rc.4"这

需要升级到2.1.0+以上，建议直接升级到最新版
