### ISSUE TITLE
Check复选框功能与样式

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#424]
#### **Expectant Behaviors**

1. 勾选样式 为什么是圆形而不是方框？
2. 支持横纵向排列

**Comment by xxyan0205** [comment]
1. 在金融设计规范中是圆形图标，如有必要可自定义图标
2. 横纵向排列可样式自定义

Check系列的组件重点在交互逻辑，因为样式多样无法完全覆盖。
