### ISSUE TITLE
mand-mobile/components/swiper/index.vue,isPrevent属性设置无法阻止父元素冒泡

### ISSUE THREAD

**Issue by Vector-SMG** [didi/mand-mobile#426]
#### **Mand Mobile Version**
暂无

#### **OS Version & Browser Version**
暂无

#### **Node Version, Package Management Tool**
暂无

#### **Recurring Links**
暂无

#### **Recurring Steps**
暂无

#### **Expectant Behaviors**

mand-mobile/components/swiper/index.vue，
 if (this.isPrevent) {
        e.preventDefault()
        e.stopPropagation();
}

#### **Actual Behaviors**

mand-mobile/components/swiper/index.vue
  if (this.isPrevent) {
        e.preventDefault()
}

**Comment by xxyan0205** [comment]
它的作用只是阻止元素默认行为，并不阻止冒泡，如果想阻止冒泡，也直接在swiperItem上绑定的事件增加`stop`修饰符

**Comment by Vector-SMG** [comment]
了解了。

**Comment by Vector-SMG** [comment]
场景是这样的：我有一个左右滑动的tabbar,其中的一个tab有一个左右滑动的swiper，我是想让swiper的视图范围可以滑动，tabbar不能左右滑动。貌似这个左右滑动的阻止应该放在swiper上面吧，不是放在swiperitem里面。这样我swiper都不不能滑动了。所以是不是应该暴露个isStop属性形如isPrevent给上层使用者。

**Comment by Vector-SMG** [comment]
> 它的作用只是阻止元素默认行为，并不阻止冒泡，如果想阻止冒泡，也直接在swiperItem上绑定的事件增加`stop`修饰符

场景是这样的：我有一个左右滑动的tabbar,其中的一个tab有一个左右滑动的swiper，我是想让swiper的视图范围可以滑动，tabbar不能左右滑动。貌似这个左右滑动的阻止应该放在swiper上面吧，不是放在swiperitem里面。这样我swiper都不能滑动了。所以是不是应该暴露个isStop属性形如isPrevent给上层使用者。
if (this.isPrevent) {
e.preventDefault()
}
if(this.isStop){
e.stopPropagation();
}

**Comment by Vector-SMG** [comment]
我重新提个issue吧，可能我没描述清楚。

**Comment by xxyan0205** [comment]
https://codesandbox.io/embed/z69yp7my9x?fontsize=14

**Comment by Vector-SMG** [comment]
> https://codesandbox.io/embed/z69yp7my9x?fontsize=14
我访问不了这个网址。尴尬
