### ISSUE TITLE
Filed FieldItem InputItem 表单校验提示功能

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#428]
#### **Expectant Behaviors**

最近在做表单校验相关功能，发现mand-mobile不能达到场景使用标准
功能：
1. FieldItem 能否提供类似InputItem error属性，用于表单错误提示信息
2. FiledItem InputItem 提供title插槽已获取更灵活的title，如必填项的红色星号
3. FiledItem InputItem 与 vee-validate 深度定制，根据required validator 来自动显示红色星号（代表必填项）与 error message（错误提示）
1,2项挺有必要的，3可能会加大项目体积，可以个人定制化。

疑惑：
1. FieldItem 与 CellItem 使用区别在哪？

以上

**Comment by xxyan0205** [comment]
1. InputItem 是基于 `FieldItem`的拓展， `FieldItem`作为列表项，它只需要为各个位置不能类别的信息预留插槽，而没有错误提示这种概念。理论上`InputItem`有的， 使用`FieldItem`都可自定义。
2. 在讨论增加红星提示的功能。
3. 可以个人定制化。

疑惑
1. `CellItem`用于展现并列层级的信息内容，承载功能入口、功能操作、信息展示，这些信息是静态的。`FieldItem`用于展示用户的一些特定交互产生的信息，如选择器，输入框等，这些信息是动态的。前者一般用于入口列表，后者一般是表单区域。

**Comment by de1ck** [comment]
@xxyan0205 ok,多谢
