### ISSUE TITLE
站点一些功能问题

### ISSUE THREAD

**Issue by de1ck** [didi/mand-mobile#429]
#### **Actual Behaviors**

1. 英文首页语言切换问题
  a: 是否有必要每次进入首页自动切换语言,这个设计很不合理，不应该是从缓存中直接获取吗？
https://didi.github.io/mand-mobile/
  b. 更不合理的是切换语言后，在点击右上角切换语言再点击开始使用后切换的语言并没有效果
https://github.com/didi/mand-mobile/blob/685d8655bc3abe8b534e19ff04b35b5747589920/site/theme/default/components/Header.vue

2. 搜索框
 a: 部分组件搜索后并没有快捷导航 如 InputItem
 b: 中文站点下搜索 imageviewer 第一项进入的是Landscape

3. 左侧菜单栏
  点击后偶尔有明显的延迟>3s，原因未知

**Comment by xxyan0205** [comment]
问题中1.a, 1.b 是疑似bug，只是还没具体定位问题，如果有线索也欢迎提供。2.a和2.b是第三方工具algolia提供的搜索结果。

**Comment by de1ck** [comment]
> 问题中1.a, 1.b 是疑似bug，只是还没具体定位问题，如果有线索也欢迎提供。2.a和2.b是第三方工具algolia提供的搜索结果。

2. 有些组件搜索不到，有些组件搜索出来的快捷链接是有问题的
