### ISSUE TITLE
Toast content 属性不支持数字

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#43]
> mand-mobile version/项目版本
1.08

> recurring steps/复现步骤
Toast.info(123)

> expectant behaviors/期待行为
提示123

> actual behaviors/实际行为
```
[Vue warn]: Invalid prop: type check failed for prop "content". Expected String, got Number.

(found in <Root>)
```

**Comment by moyus** [comment]
只支持传字符串内容
