### ISSUE TITLE
mandmobile框架下载本地运行，为何表单控件中还会去下载远程的字体https://manhattan.didistatic.com/static/manhattan/mand-mobile/icon/2.0.2/iconfont.woff这个字体文件

### ISSUE THREAD

**Issue by lizhongxue** [didi/mand-mobile#430]
框架npm下载后本地开发运行，实际使用过程中发现表单中会远程去下载这个字体文件https://manhattan.didistatic.com/static/manhattan/mand-mobile/icon/2.0.2/iconfont.woff。
可是本地开发，无网络的情况下，这个文件根本就下载不下来，着手手动下载之后，修改主题变量
icon-font-family，url指导本机的绝对网络地址，控制台出现错误。。。
Failed to decode download font: http://localhost:8080/static/fonts/mand-mobile/iconfont.woff
OTS parsing error: Unable to instantiate font face from font data.

怎么解决？？？
这个文件包含了很多表单里面的icon样式，如果没有，样式会不正常

**Comment by de1ck** [comment]
我建议你把标题改的简洁一些

**Comment by xxyan0205** [comment]
因为不想把字体打到产出的bundle中，目前只能通过重置 icon-font-family，只不过问题里反馈的路径并无法访问，你可以设置项目内的相对路径，可选择转成base64，如果写绝对路径就需要提供可访问的路径。

**Comment by lizhongxue** [comment]
> 因为不想把字体打到产出的bundle中，目前只能通过重置 icon-font-family，只不过问题里反馈的路径并无法访问，你可以设置项目内的相对路径，可选择转成base64，如果写绝对路径就需要提供可访问的路径。之前在mand-mobile qq群里也有一些开发者使用uni-app遇到类似问题，可以加群后咨询解决方案。


我就是通过重置icon-font-family，重置路径是本机下的iconfont.woff的绝对路径，因为本地开发，用的vue-cli3构建，我把下载下来的字体文件放到了public/static/fonts/mand-mobile/iconfont.woff路径下，可通过浏览器直接访问并且下载。不知道是这个字体文件有问题还是什么原因，控制台报这个错误，相应的图标也无法显示，google上也没有找到关于此的解决办法

**Comment by lizhongxue** [comment]
> 因为不想把字体打到产出的bundle中，目前只能通过重置 icon-font-family，只不过问题里反馈的路径并无法访问，你可以设置项目内的相对路径，可选择转成base64，如果写绝对路径就需要提供可访问的路径。之前在mand-mobile qq群里也有一些开发者使用uni-app遇到类似问题，可以加群后咨询解决方案。

另外请问qq群号码是多少，感谢

**Comment by xxyan0205** [comment]
> 另外请问qq群号码是多少，感谢

493305323
