### ISSUE TITLE
TabBar标签较多时，v-model绑定最后一个标签，里面scroll-view未滚动到最右边

### ISSUE THREAD

**Issue by kevin611003** [didi/mand-mobile#434]
#### **Mand Mobile Version**
`^2.2.0`

#### **OS Version & Browser Version**
`win 10 & chrome v72`

#### **Recurring Links**
https://codesandbox.io/s/qvxky1xym9

#### **Recurring Steps**
当标签个数较多，tabbar宽度大于当前屏幕宽度，设置当前current为最后一个标签

#### **Expectant Behaviors**
tabbar会滚动到最右边

#### **Actual Behaviors**
tabbar未滚动到最右边

初步检查是`components\tab-bar\index.vue`213行的问题

**Comment by xxyan0205** [comment]
fixed@2.2.3

**Comment by kevin611003** [comment]
@xxyan0205 我这边升级到 `2.2.3` 后还是有bug，当 items 个数为11，label 长度6位，tabbar 位置没有滚动到最右边
Recurring Link: https://codesandbox.io/s/7zvs9

**Comment by xxyan0205** [comment]
> 当 items 个数为11，label 长度6位，tabbar 位置没有滚动到最右边

试下2.2.4

**Comment by kevin611003** [comment]
测试正常，大神辛苦了 :thumbsup:
