### ISSUE TITLE
tab-picker组建希望可以通过solt自定义头部

### ISSUE THREAD

**Issue by lonelyWalkor** [didi/mand-mobile#435]
#### **Mand Mobile Version**
2.2.0

#### **OS Version & Browser Version**
win7 chrome

#### **Expectant Behaviors**
tab-picker组建希望可以通过solt自定义头部，希望多频道选择器能够自定义头部，以实现用户不一定得选择到最后一级才可结束，用户选择到任意级别也可结束选择

#### **Actual Behaviors**
用户必须选择到最后一级才能结束选择。

**Comment by xxyan0205** [comment]
add event select @2.2.2
