### ISSUE TITLE
支持 ssr

### ISSUE THREAD

**Issue by Amorites** [didi/mand-mobile#438]
#### **Mand Mobile Version**
2.2.0

#### **Node Version, Package Management Tool**
node 11.7.0

#### **Recurring Steps**

目前编译后的代码中会 requrie css，导致 ssr 失败，如`lib/scroll-view/more.js` 中的 line 6:
```
factory(exports, require('../_style/global.css'), require('./style/more.css'));
```

require css 的工作应该交给 babel-plugin-import 之类的插件来解决，在 node 里直接 require css 会报错

#### **Expectant Behaviors**

修改构建 config, 去掉组件里 require css 的部分

#### **Actual Behaviors**

ssr 时试图 require css

**Comment by xxyan0205** [comment]
在js中直接引入css是最早在工程化设计的时候，期望减少在client侧引入时的负担，即使没有插件，也可以方便使用，但同时的确是给ssr带来了不便。可以尝试一下[mand-mobile/nuxt-example](https://github.com/mand-mobile/nuxt-example/blob/master/nuxt.config.js#L6)中的方案来避免报错：

```
// Avoid css files being executed
require.extensions['.css'] = () => {
  return
}
```

**Comment by Amorites** [comment]
> 在js中直接引入css是最早在工程化设计的时候，期望减少在client侧引入时的负担，即使没有插件，也可以方便使用，但同时的确是给ssr带来了不便。可以尝试一下[mand-mobile/nuxt-example](https://github.com/mand-mobile/nuxt-example/blob/master/nuxt.config.js#L6)中的方案来避免报错：
> 
> ```
> // Avoid css files being executed
> require.extensions['.css'] = () => {
>   return
> }
> ```

这里的 require 是 node 的 require 吗？node 的 require. extensions应该已经废弃了吧？

一个临时的 workaround 是在 nodeExternal 的白名单里加上 mand-mobile……

**Comment by xxyan0205** [comment]
> node 的 require. extensions应该已经废弃了吧

是废弃了，不过只是覆盖的方式避免报错，能用但的确有风险，也可以参考[require-hacker](https://github.com/catamphetamine/require-hacker)

**Comment by Amorites** [comment]
加油👍
