### ISSUE TITLE
希望能在vue模板的基础上，提供mand-mobile的模板工程，方便初学者。

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#44]
命令行工具 (CLI)
Vue 提供一个官方命令行工具，可用于快速搭建大型单页应用。该工具为现代化的前端开发工作流提供了开箱即用的构建配置。只需几分钟即可创建并启动一个带热重载、保存时静态检查以及可用于生产环境的构建配置的项目：
```
# 全局安装 vue-cli
$ npm install --global vue-cli
# 创建一个基于 webpack 模板的新项目
$ vue init webpack my-project
# 安装依赖，走你
$ cd my-project
$ npm run dev
```

**Comment by xxyan0205** [comment]
vue-cli template 和 基于@vue/cli 3.0的demo 正在开发中，预计本周可以完成。
