### ISSUE TITLE
watermark组件在Tabs中使用content指定水印文字时不显示水印

### ISSUE THREAD

**Issue by shazha** [didi/mand-mobile#441]
#### **Mand Mobile Version**
2.2.2

下面这样使用content属性的时候不显示水印文字了，只有使用`watermark`的slot指定水印文字才能正常显示。之前的版本是好使的，我是从2.2.0版本发现这个问题的，升级到2.2.2还是有这问题。官网的文档中也有这问题。
```
<md-water-mark content="MAND MOBILE" spacing="10vw" opacity="0.2">
</md-water-mark>
```

```
 <md-water-mark spacing="10vw" opacity="0.2">
      <div slot="watermark">
        <span>MAND MOBILE</span>
      </div>
</md-water-mark>

**Comment by supergaojian** [comment]
2.2我们将水印使用content时改为用canvas渲染，在canvas中您使用的spacing过大导致了看起来是不显示水印的问题，通过修改spacing就可以了

**Comment by shazha** [comment]
@supergaojian 我使用的spacing就是10vw，不过在你的提醒下我发现使用`content`指定水印文字却不显示水印的情况只在`Tabs`中使用`Watermark`时才会出现，这种情况下`Watermark`组件的canvas的width和height都是0.

**Comment by supergaojian** [comment]
起因：
1、water-mark在挂载的时候会计算自身宽高之后，才初始化canvas。
2、tabs组件值展示当前显示的tab，其它tab不展示的时候display: none。
导致：
当water-mark在tabs中不是第一个展示的时候（已挂载），因为父级标签不展示（display: none），所以计算的宽高均为0，就导致了水印不展示。
解决：
为water-mark加v-key，通过tabs的change事件更新绑定的v-key触发重新渲染即可
