### ISSUE TITLE
ScrollView

### ISSUE THREAD

**Issue by bihongbin3027** [didi/mand-mobile#444]
ScrollView, ScrollViewMore, ScrollViewRefresh，同时使用下拉刷新和加载更多，加载更多出问题了，第一次使用没问题，当我加载更多数据分页加载完成以后，去点了下拉刷新，数据数量变为10条，在去滚动加载更多，加载更多就不起作用了

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/issues/199

**Comment by bihongbin3027** [comment]
多谢
