### ISSUE TITLE
Toast.loading 可以支持更多样式吗

### ISSUE THREAD

**Issue by jameszzX** [didi/mand-mobile#445]
#### **Expectant Behaviors**

Toast.loading是否考虑像ActivityIndicator之类的样式设置参数开放。

**Comment by jameszzX** [comment]
并且Toast.hide()能否扩展成指定关闭某个，而不是只能关闭全部

**Comment by xxyan0205** [comment]
1. 目前只能以图标的形式自定义，是否需要设置插槽我们再讨论下。
2. `Toast.hide`是单例使用模式，所有的变更都在同一个toast实例下，不错在多个toast，只有一个。
