### ISSUE TITLE
datePicker 的若干问题

### ISSUE THREAD

**Issue by dev-kxy** [didi/mand-mobile#449]
title,ok-text,cancel-text, describe等属性设置后没有效果
sdk版本——"version": "2.2.0",

**Comment by xxyan0205** [comment]
请展示一下相关代码

**Comment by dev-kxy** [comment]
官网demo直接粘贴复制的




| |
孔祥宇
邮箱：13511070436@163.com
|

签名由 网易邮箱大师 定制

在2019年05月22日 21:16，Shawn Xu 写道：

请展示一下相关代码

**Comment by xxyan0205** [comment]
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-w6cly?fontsize=14)
