### ISSUE TITLE
mand-mobile结合cordova使用，在ios模拟器中button大小异常

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#45]
> mand-mobile 1.0.8

> os version & browser version  macos 10.13.4

> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)

> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤
![simulator screen shot - iphone x - 2018-04-25 at 11 30 29](https://user-images.githubusercontent.com/737958/39228450-de1484b6-4890-11e8-96df-6111df59417d.png)

> expectant behaviors/期待行为
如何调整控件大小？

> actual behaviors/实际行为

**Comment by moyus** [comment]
请先查看[快速上手文档](https://didi.github.io/mand-mobile/#/docs/started?anchor=%E4%BD%BF%E7%94%A8%E5%89%8D%E5%87%86%E5%A4%87)，是否是由尺寸单位引起的异常。

**Comment by snowdream** [comment]
.postcssrc.js

```
// https://github.com/michael-ciniawsky/postcss-load-config

module.exports = {
  "plugins": {
    "postcss-import": {},
    "postcss-url": {},
    // to edit target browsers: use "browserslist" field in package.json
    "autoprefixer": {},
    "postcss-pxtorem": {
      rootValue: 100,
      propWhiteList: []
    }
  }
}
```

**Comment by snowdream** [comment]
参考 http://www.alloyteam.com/2016/03/mobile-web-adaptation-tool-rem/ 
目前设置 37.5，取得较好的效果。

```
// https://github.com/michael-ciniawsky/postcss-load-config

module.exports = {
  "plugins": {
    "postcss-import": {},
    "postcss-url": {},
    // to edit target browsers: use "browserslist" field in package.json
    "autoprefixer": {},
    "postcss-pxtorem": {
      rootValue: 37.5,
      propWhiteList: []
    }
  }
}
```
