### ISSUE TITLE
scroll-view横向滚动区域问题

### ISSUE THREAD

**Issue by dev-kxy** [didi/mand-mobile#454]
![scroll-view](https://user-images.githubusercontent.com/38744990/58403745-017e1280-8096-11e9-8665-632c9e9bcf59.jpg)
组件定义为横向滚动时，手指放在组件区域内上滑，页面无法滚动。这是个bug还是故意设计成这样的？很反人类呀，如何解决呢

**Comment by supergaojian** [comment]
您主动把scrolling-y（纵向滚动）置为false的

**Comment by dev-kxy** [comment]
我把scrolling-y这行代码删掉了，也不会触发页面滚动，而是触发组件区域的上下滚动

**Comment by dev-kxy** [comment]
我写scrolling-y="false"的本意是不让组件在y轴上滑动。但问题是现在手指放在组件区域内上下滑动，页面都不动。。。

**Comment by supergaojian** [comment]
1、我们在scroll-view中将touchmove的默认行为禁止了
2、这个行为并不反人类，设想一下，如果您在横向滚动，同时发现页面上下会出现抖动（因为放开的话会计算横向和纵向）是不是用户体验更差呢

**Comment by dev-kxy** [comment]
好吧，那如何解决我目前的需求呢？我希望组件内的上下滑动可以触发页面的滚动

**Comment by xxyan0205** [comment]
> 我希望组件内的上下滑动可以触发页面的滚动

目前的版本还无法触发页面原生的滚动，因为之前对所有的touch相关事件都做了`preventDefault`，针对这个case 我们需要讨论下优化方案

**Comment by dev-kxy** [comment]
好吧，那我先手动恢复一下touchmove事件。
