### ISSUE TITLE
滚动问题

### ISSUE THREAD

**Issue by penggangg** [didi/mand-mobile#457]
当有筛选的时候滚动会出现问题 第一次加载完所有数据 我滚动到底部，现在显示加载完成，当时当我筛选条件之后只有部分数据之后 触发不了加载更多的那个函数 看了一下参数 isEndReaching，isEndReachingStart都为true 现在理论上都要为fales 才能触发加载更多的方法。我用了auto-reflow这些属性也不管用 是不是还有其他使用方法呢

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/issues/199

**Comment by xxyan0205** [comment]
提供一个复现的问题的示例吧 我们查一下 https://codesandbox.io

**Comment by wywuyou** [comment]
你好，目前我也遇到了这个问题，是在tab第一项上拉加载后，切换tab，会自动触发我的上拉加载事件，请求两次，请问这个问题有解决方法了吗

**Comment by xxyan0205** [comment]
> 你好，目前我也遇到了这个问题，是在tab第一项上拉加载后，切换tab，会自动触发我的上拉加载事件，请求两次，请问这个问题有解决方法了吗

你是在一个scrollview里嵌套了tabbar?

**Comment by wywuyou** [comment]
> > 你好，目前我也遇到了这个问题，是在tab第一项上拉加载后，切换tab，会自动触发我的上拉加载事件，请求两次，请问这个问题有解决方法了吗
> 
> 你是在一个scrollview里嵌套了tabbar?

没有嵌套呢，只是同时使用，会在加载完一次再切换状态后，自动触发我的加载事件，导致请求了两次

**Comment by xxyan0205** [comment]
> 没有嵌套呢，只是同时使用，会在加载完一次再切换状态后，自动触发我的加载事件，导致请求了两次

提供一个复现的问题的示例 https://codesandbox.io
