### ISSUE TITLE
纵向scrollview中的横向滚动问题

### ISSUE THREAD

**Issue by bart1989** [didi/mand-mobile#459]
纵向scrollview中加入横向滚动样式，在iPhone6s 11.4中 无法横向滚动
https://codesandbox.io/s/vue-template-feqc3

**Comment by supergaojian** [comment]
因为在scrollview中我们阻止了touchmove的默认行为，而且当您只配置scrolling-y时，横向滑动是被阻止了，所以出现了您所反馈的情况，您的场景推荐内部再使用一个scrolling-x的scroll-view

**Comment by bart1989** [comment]
> 因为在scrollview中我们阻止了touchmove的默认行为，而且当您只配置scrolling-y时，横向滑动是被阻止了，所以出现了您所反馈的情况，您的场景推荐内部再使用一个scrolling-x的scroll-view

我按您的说法写了，还是不行，横向scrollview需要如何设置？
