### ISSUE TITLE
InputItem金融数字键盘显示问题

### ISSUE THREAD

**Issue by raynerluo** [didi/mand-mobile#462]
Mand Mobile Version 2.2.4     浏览器： Google  Chrome 和  Safari  
![image](https://user-images.githubusercontent.com/46154601/58846740-effac300-86b2-11e9-90f9-0a100287f1f6.png)

**Comment by raynerluo** [comment]
代码：
![image](https://user-images.githubusercontent.com/46154601/58846932-92b34180-86b3-11e9-8c3c-b7da31cd643a.png)

**Comment by xxyan0205** [comment]
浏览器默认的间距是否清除过，引入[reset.css](https://meyerweb.com/eric/tools/css/reset/)或
```css
*{margin:0;padding:0;}
```

**Comment by raynerluo** [comment]
就是这个浏览器默认间距的问题哈，谢谢，问题解决了。

**Comment by gongph** [comment]
@raynerluo @xxyan0205 有什么技巧可以隐藏系统键盘吗？

**Comment by xxyan0205** [comment]
> 有什么技巧可以隐藏系统键盘吗

没有太好的办法，所以我们做了金融数字键盘
