### ISSUE TITLE
Cannot read property 'imgInit' of undefined

### ISSUE THREAD

**Issue by kongwm** [didi/mand-mobile#463]

**Comment by supergaojian** [comment]
哪个组件？
什么情况？
如何复现？
全文搜不到imgInit这个参数，是您自己加的吧

**Comment by kongwm** [comment]
> 哪个组件？
> 什么情况？
> 如何复现？
> 全文搜不到imgInit这个参数，是您自己加的吧

ImageReander 这个组件， 在页面刚进的时候偶然出现的， 现在我无法复现了，不是我自己加的，我也搜索了下没有搜索到。
