### ISSUE TITLE
Android 调起输入法会影响swiper样式

### ISSUE THREAD

**Issue by wczhang3** [didi/mand-mobile#467]
#### **Mand Mobile Version**

mand-mobile 2.2.2
#### **OS Version & Browser Version**

android系统，webview

#### **Node Version, Package Management Tool**

node version=8.11.1 npm 

#### **Recurring Steps**

同一个页面引用swiper，transition="slideY",和input输入框。正常情况下swiper样式没问题。但是点击输入框调起输入法会挤压swiper样式，退出输入法swiper样式依然是挤压状态，页面必须刷新一次swiper样式才能恢复

#### **Expectant Behaviors**

调起输入法不影响swiper样式

**Comment by supergaojian** [comment]
请按照格式准确告诉我们具体的情况，如何复现，谢谢。或者使用https://codesandbox.io复现

**Comment by supergaojian** [comment]
原因是这样的：swiper内部监听了window.resize事件，每次resize都会重新计算宽高，然后因为部分手机在键盘弹出时，会修改当前窗高度，导致了触发window.resize事件，所以样式出现了问题，但是键盘收起时可能没有再次触发window.resize，就导致了问题出现，推荐固定好swiper的宽高
