### ISSUE TITLE
关于scroll-view中的isEndReaching设置问题

### ISSUE THREAD

**Issue by PHenryy** [didi/mand-mobile#470]
#### **Mand Mobile Version**
^2.0.0

#### **OS Version & Browser Version**
windows7 & chrome 75.0.3770.80（正式版本） （64 位）

#### **Recurring Steps**
下拉到底，scroll-view 的 endReachedHandler 触发后，会将 isEndReaching 设置为 true，
问题是，我的项目中有多个标签页，当我切换标签后，$_checkScrollerEnd 中的 `this.endReachedHandler()` 将不会触发，因为源码中
有判断 `top >= 0 && !this.isEndReaching && endOffset <= 0 && this.endReachedHandler`,
因此我只能在 @endReached 的处理行数中写成下面这种形式
`if (this.isLoadingMoreFinished) {
        this.$refs.strategies.finishLoadMore();
        return;
      }`
但是这样导致 md-scroll-view-more 组件隐藏，我不知道是我哪里做的有问题，还是源码需要改善
，因为是公司项目，所以不便贴出来

**Comment by xxyan0205** [comment]
在`切换标签`里干了什么？如果有滚动内容调整导致，且此时ScrollView未被`reflow`可能会导致无法触底，须确保`finishLoadMore`在滚动内容调整完成之后再调用，或者直接加`auto-reflow`属性。

**Comment by PHenryy** [comment]
@xxyan0205 不好意思回复晚了，在切换标签里 重新请求了列表数据并赋值给data的属性，我知道 finishLoadMore里面会调用 reflowScroller，所以我在获取数据后，`this.$nextTick().then(() => { this.$refs.xxx.finishLoadMore() })`, 但是好像并没有用，我甚至将 $nextTick 换成 setTimeout。
![QQ截图20190613181127](https://user-images.githubusercontent.com/21993802/59424561-c5251300-8e06-11e9-853f-5b182873666b.png)，切换标签后一直是正在加载中，且无法再触发 @endReached

**Comment by PHenryy** [comment]
@xxyan0205 写了个重现的项目
https://codesandbox.io/s/vue-template-iup9v?fontsize=14
让我奇怪的是这个项目如果不断的下拉，很容易触发多次触底事件，导致写的3页的限制被跳过，可能是另一个问题？

**Comment by PHenryy** [comment]
问题解决和，和这个 [issue](https://github.com/didi/mand-mobile/issues/199#issuecomment-422633735)应该是同一个问题，在刷新的处理函数中 finishLoadMore.
