### ISSUE TITLE
slider组件的barstyle中width计算有误

### ISSUE THREAD

**Issue by myweal** [didi/mand-mobile#472]
项目版本：mand-mobile2.3.0
复现步骤及解决方案如下：
1、range使用默认值false，设置min为50 max为100
2、滑动滑块，发现默认的蓝色进度条所在百分比不对
3、原因：由于在**/components/slider/index.vue 获得barStyle值 计算width有误，
4、解决方法：
可将**/components/slider/index.vue 的126行
    width: this.values[0] / (this.max - this.min) * 100 + '%',
修改为如下即可
    width: (this.values[0] - this.min) / (this.max - this.min) * 100 + '%'

**Comment by supergaojian** [comment]
已复现，我们会尽快修复
