### ISSUE TITLE
ScrollView在移动端不能滑动

### ISSUE THREAD

**Issue by yujianquan** [didi/mand-mobile#482]

**Comment by yujianquan** [comment]
我在页面开发中，在chrome浏览器中能滑动加载更多，但是在移动端的滑动事件失效了，而且整个页面卡住，不知道是什么问题导致的

**Comment by supergaojian** [comment]
可以使用codesandbox复现您的问题么？

**Comment by yujianquan** [comment]
> 可以使用codesandbox复现您的问题么？

太麻烦了，问题是这样的，我使用scrollView，在电脑上能够使用，在电脑的debug模式下也能使用，到了手机上，你的scorllView不是要滑动过后弹回去吗，然后就是一直弹回去，用户拉不到底部，先执行的弹回去那个方法

**Comment by xxyan0205** [comment]
> 你的scorllView不是要滑动过后弹回去吗，然后就是一直弹回去，用户拉不到底部

从问题描述来看，基本是`.md-scroll-view`高度无效导致，可以参考同类的其他issue

**Comment by wulichenyang** [comment]
同样的问题 ，.md-scroll-view设置固定高度，且overflow:hidden，内部列表内容超出后，在电脑上可以正确加载更多。

但到手机上第一次加载时下滚加载更多，添加数据后无法继续下滚，会回弹，点进子路由页面后返回可以继续下滚加载。

手机型号iPhoneXR，猜测手机缓存机制导致内部列表高度没更新？很奇怪的bug，不知道作者有没有具体解决？
