### ISSUE TITLE
ios内-webkit-overflow-scrolling引起的popup组件显示问题

### ISSUE THREAD

**Issue by mangoooooo** [didi/mand-mobile#483]
#### **Mand Mobile Version**

1.6.9

#### **OS Version & Browser Version**

iphone xs max  ios12.2， iphone 6 ios 11.2.1，华为p10

#### **Recurring Steps**

左边手机是iphone 右边是安卓
设置了-webkit-overflow-scrolling touch时 footer没有被遮住（见图一），去掉之后就正常了（见图二）

![图一](https://ws1.sinaimg.cn/large/005wMh0ngy1g4gplnx5h7j32ao3284qq.jpg)
![图二](https://ws1.sinaimg.cn/large/005wMh0ngy1g4gpmyzesvj33282ao4qq.jpg)

不管是微信浏览器还是原生自带浏览器都有同样的问题，用了两台iphone机也有同样的问题。actionSheet也有同样问题

#### **代码**
template:

    <div id="app">
        <div class="app-inner">
            <md-button plain @click="value = true">open popup</md-button>
            <md-popup v-model="value">
                <div class="md-example-popup md-example-popup-center">
                    Popup Center
                </div>
            </md-popup>
        </div>
        <div class="footer">footer</div>
    </div>

style:

    .md-popup .md-popup-mask
        background-color rgba(0,0,0,0.8)

    body, html
        overflow hidden
        height 100%
    #app
        position: relative
        height: 100%
        width: 100%

    .app-inner
        position absolute
        top 0
        left 0
        width 100%
        bottom 1rem
        background-color indianred
        overflow-x hidden
        overflow-y auto
        -webkit-overflow-scrolling touch

        .md-example-popup
            background-color #ffffff

    .footer
        position absolute
        bottom 0
        left 0
        width 100%
        height 1rem
        background-color #ffffff
        text-align center
        color #000000

**Comment by supergaojian** [comment]
请正确设置z-index，您在未指定z-index导致浏览器自身判断添加z-index判断层级，有可能出现问题

**Comment by mangoooooo** [comment]
知道啥问题了：-webkit-overflow-scrolling: touch会导致苹果上z-index属性失效
