### ISSUE TITLE
UI toast bug in android 4.4.4

### ISSUE THREAD

**Issue by mlzk** [didi/mand-mobile#485]
#### **Mand Mobile Version**
2.31

#### **OS Version & Browser Version**
android 4.4.4 

Toast 自定义位置为bottom是 toastUI位置在X轴方向有位移偏差 使用的是官方提供的在线demo

![1 (1)](https://user-images.githubusercontent.com/9440172/60697427-ce446400-9f1c-11e9-8968-8f921c10b021.png)

**Comment by xxyan0205** [comment]
使用的是模拟器么？还是什么机型？

**Comment by mlzk** [comment]
> 使用的是模拟器么？还是什么机型？

模拟器

**Comment by supergaojian** [comment]
请确定4.4.4中对css flex布局的兼容性

**Comment by mlzk** [comment]
![image](https://user-images.githubusercontent.com/9440172/60963092-735aa480-a342-11e9-8f12-82080e91c1c2.png)
![image](https://user-images.githubusercontent.com/9440172/60963190-af8e0500-a342-11e9-9e27-d2a933269d4a.png)

相同环境下 非自定义位置的toast 是没有问题的
