### ISSUE TITLE
浏览器引入scroll-view的上拉加载更多功能始终不能被触发

### ISSUE THREAD

**Issue by charleslck** [didi/mand-mobile#487]
#### **Mand Mobile Version**
mand-mobile-vx@2.2.0

#### **OS Version & Browser Version**
Macos Catalina
&
Google Chrome
版本 75.0.3770.100（正式版本） （64 位）

#### **Recurring Links**
在浏览器引入的状态下 md-scroll-view 的上拉加载更多功能始终不能被触发，我尝试修改过很多content容器的高度值，依然不行。附上sandbox的地址 [https://codesandbox.io/s/static-kmu4j](https://codesandbox.io/s/static-kmu4j)

#### **Recurring Steps**
打开浏览器移动端模拟功能，列表页往上拉至尾部

#### **Expectant Behaviors**
在页面上拉至列表尾部的时候触发endReached方法

#### **Actual Behaviors**
在页面上拉至列表尾部的时候无法触发endReached方法

**Comment by xxyan0205** [comment]
文档有误，建议监听事件`end-reached`

**Comment by charleslck** [comment]
可以触发事件了，感谢。
