### ISSUE TITLE
TabBar 对item应用flex:1 或flex-grow:1在一些尺寸导致死循环

### ISSUE THREAD

**Issue by hangpingping** [didi/mand-mobile#490]
#### **Mand Mobile Version**

mand-mobile v2.3.1
#### **OS Version & Browser Version**

window10 x64    华为荣耀8x chrome75.0.3770.67

#### **Node Version, Package Management Tool**

Node v10.15.3 npm v6.9.0 vue-cli 3.5.5 vue 2.6.10

#### **Recurring Steps**

app.vue
```
<template>
  <div id="app">
    <md-tab-bar class="tab-bar" v-model="current" :items="items" :has-ink="false">
      <template slot="item" slot-scope="{ item }">
        <div class="item">
          {{ item.label }}
        </div>
      </template>
    </md-tab-bar>
  </div>
</template>

<script>
import TabBar from "mand-mobile/components/tab-bar";
export default {
  name: "app",
  components: {
    [TabBar.name]: TabBar
  },
  data() {
    return {
      current: 2,
      items: [
        { name: 1, label: "AA" },
        { name: 2, label: "BBB" },
        { name: 3, label: "CC" },
        { name: 4, label: "CC" }
      ]
    };
  },
};
</script>

<style lang="stylus" scoped>
@import '~reset.css';
@import '~mand-mobile/lib-vw/mand-mobile.css';

.tab-bar {
  padding: 0;

  >>> .md-tab-bar-item {
    flex-grow: 1;
    padding: 0;
    font-size: 2.67vw;

    &:nth-child(2) .item {
      width: 12.792vw;
    }
  }
  .item {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 7.7vw;
    height: 100%;
  }
}
</style>
```
![test1](https://user-images.githubusercontent.com/37317774/60805719-8428e000-a1b3-11e9-9c8b-94795d6053f1.png)
上图为tab-bar源文件，我将inkWidth alert出来，下图为结果
![test](https://user-images.githubusercontent.com/37317774/60805666-58a5f580-a1b3-11e9-85df-53441e5d6c57.gif)

原因是contentW重新赋值后，item因flex-grow:1重新计算以及offsetWidth的四舍五入的原因导致inkWidth在两个值上循环，不停触发reflow，在某些尺寸会触发。

**Comment by hangpingping** [comment]
这是一个特定尺寸才会触发的问题，上述复现尺寸只在华为8x chrome75中成功复现

**Comment by supergaojian** [comment]
请问具体尺寸是多少？

**Comment by hangpingping** [comment]
手机分辨率1560x720   屏幕宽度424  上述复现才会触发

**Comment by supergaojian** [comment]
经过本地测试屏幕宽度424 + mand-mobile vw样式未成功复现，请确认是否为其他样式或代码导致
