### ISSUE TITLE
Picker 选择器运行在真机上，似乎对不准。

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#50]
https://didi.github.io/mand-mobile/#/docs/components/feedback/picker

Picker 选择器运行在真机上，似乎对不准。
线压在字的上面。
![simulator screen shot - iphone x - 2018-04-25 at 21 37 56](https://user-images.githubusercontent.com/737958/39249355-0b8d6df0-48d1-11e8-8f1b-882675042c14.png)

**Comment by xxyan0205** [comment]
这个地方是由于响应式方案差异导致引起的，因为pick内部分尺寸写死了，导致不能完成响应式。能否提供下设备的相关尺寸信息，比如屏幕的宽高等。

**Comment by snowdream** [comment]
@xxyan0205 iphone 6 sp, 小米 红米note3.

**Comment by WongJk** [comment]
补充2个问题：
前提：Picker组件在 `is-view` 为 `false` 时，且在 `mounted` 重新设置过 `pickerDefaultIndex` 后。

1. Picker组件内部滑动出现问题：比如第一列滑动不到最后一个元素。
    - 可在这个例子上修改下复现 https://github.com/didi/mand-mobile/blob/master/components/picker/demo/cases/demo1.vue
    - 环境：chrome浏览器，版本：1.0.8

2. 如果不设置 `pickerDefaultIndex` ，则在2列的情况下，第2列不能默认选择第1个选项。
    - 需要滑动到第2个，再滑动回第1个，第2列才可以默认选择第1个选项
    - 3列的情况，没有验证
    - 复现代码、环境 同问题1

**Comment by xxyan0205** [comment]
@snowdream 按照你的配置，在以上机型没有复现这个问题，是否尝试过在普通浏览器或微信中是否存在这个问题，如果可以的话帮忙提供一个可复现问题的链接，谢谢。

**Comment by LetHergo** [comment]
@xxyan0205 能否提供一下省市区的json数据

**Comment by xxyan0205** [comment]
@LetHergo 这是一个测试用的数据，无法保证准确和完整性，建议还是找一份比较权威准确数据。
https://github.com/didi/mand-mobile/blob/master/components/picker/demo/data/district.js

**Comment by xxyan0205** [comment]
@LetHergo 关于问题1 #55 已修复，会在v1.1发布。问题2中的"打不开"是click事件响应么？
