### ISSUE TITLE
NoticeBar 通告栏 和 Picker 选择器  NoticeBar z-index过高

### ISSUE THREAD

**Issue by chuangdao** [didi/mand-mobile#503]
Mand Mobile Version
Mand Mobile v2.3.2

OS Version & Browser Version
window 10 Google Chrome 74.0.3729.169

Node Version, Package Management Tool
node 10.16.0
当使用 NoticeBar 通告栏 和 Picker 选择器 同一页面时候，Picker弹出蒙版，无法覆盖 NoticeBar的内容
![微信截图_20190719024007](https://user-images.githubusercontent.com/24773738/61483314-26746f00-a9cf-11e9-8096-d97961baaabc.png)

**Comment by supergaojian** [comment]
请升级至2.3.3版本，不好意思

**Comment by chuangdao** [comment]
谢谢！
