### ISSUE TITLE
ScrollView 无法滚动 回弹  不设置固定高度

### ISSUE THREAD

**Issue by chuangdao** [didi/mand-mobile#505]
Mand Mobile Version
2.3.3

OS Version & Browser Version
win10 chrome/ android 8.0

Actual Behaviors
情况：假如顶部有tab，底部有tabbar。中间内容兼容适应设备。没办法设置固定高度。不设置固定高度，不能使用，无法拉至底，还有很长一段距离才到底部，就会发生弹回效果。 不知怎么搞。

https://codesandbox.io/embed/vue-template-6eqpo

**Comment by xxyan0205** [comment]
可以参考 #469

**Comment by chuangdao** [comment]
100vh

**Comment by kingxiaozhe** [comment]
设置这个属性：auto-reflow
