### ISSUE TITLE
ImageReader如何配合ActionSheet？

### ISSUE THREAD

**Issue by pasBone** [didi/mand-mobile#506]
#### **Expectant Behaviors**

ImageReader如何配合ActionSheet使用呢？ 感觉通过ActionSheet去选择图片呢？感觉这种场景移动端会比较常见。
![image](https://user-images.githubusercontent.com/18027183/61579788-53926000-ab3c-11e9-87ac-e389a9bfd467.png)

#### **Actual Behaviors**

看了下目前两个组件的API，应该是无法组合在一起的？

**Comment by pasBone** [comment]
估计可以结合popup来做^-^

**Comment by xxyan0205** [comment]
这个困难不是在UI层面，而是通过点击input file直接进入相册 或 直接拉起相机，目前h5存在兼容问题，没有很好的办法。移动端的话可以让native通过js bridge提供相关方法来实现。

**Comment by pasBone** [comment]
明白，谢谢！------------------ 原始邮件 ------------------
发件人: "Shawn Xu"<notifications@github.com>
发送时间: 2019年7月21日(星期天) 上午10:33
收件人: "didi/mand-mobile"<mand-mobile@noreply.github.com>;
抄送: "lastWhisper"<pasbone2@gmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [didi/mand-mobile] ImageReader如何配合ActionSheet？ (#506)



这个困难不是在UI层面，而是通过点击input file直接进入相册 或 直接拉起相机，目前h5存在兼容问题，没有很好的办法。移动端的话可以让native通过js bridge提供相关方法来实现。
 
&mdash;

**Comment by pasBone** [comment]
1. 可以结合popup来做^-^
2. 可以JS trigger input事件，偷个懒不想自己写UI了 ^-^
