### ISSUE TITLE
Amount组件能否支持数字为负数

### ISSUE THREAD

**Issue by zhixinpeng** [didi/mand-mobile#510]
#### **Recurring Steps**

显示金融大写中文，设置值为负数时

#### **Expectant Behaviors**

显示完整的字段，比如 负壹仟壹佰

#### **Actual Behaviors**

只会显示小数点后面的几位

**Comment by xxyan0205** [comment]
是什么使用场景？目前大写数字一般是用于一些票据上金额的大写

**Comment by zhixinpeng** [comment]
首先我们公司这个需求确实很奇怪，就是把输入金额数字转化为大写中文。而不是用在票据上。且不说是否应该显示负数，传入负数时，大写中文只显示小数点后面几位也有些奇怪。这边你们可以实现一下大写负，或者对负数做一下处理。
