### ISSUE TITLE
 数字键盘的配置项是否可以加一个小数点位数的配置呢？

### ISSUE THREAD

**Issue by pasBone** [didi/mand-mobile#513]
#### **Recurring Steps**

数字键盘的配置项是否可以加一个小数点位数的配置呢？因为金额一般是2位

#### **Expectant Behaviors**

![image](https://user-images.githubusercontent.com/18027183/61879677-1bb55f00-af26-11e9-92e5-a3befd9a55ae.png)

**Comment by xxyan0205** [comment]
数字键盘只是一个Data Entry类的组件，而限制数字精度属于Data Display类，更适合在Input或者展示数字的地方处理

**Comment by pasBone** [comment]
是的，是我把场景搞错了。
![image](https://user-images.githubusercontent.com/18027183/61881204-caf33580-af28-11e9-9cfe-ff26e2bc2214.png)
只能通过 formation 去做了
