### ISSUE TITLE
ios上面UC浏览器inputItem组件bug

### ISSUE THREAD

**Issue by s749312025** [didi/mand-mobile#516]
IOS UC浏览器

#### **Recurring Steps**

IOS UC浏览器 点击input ，唤起键盘，再点击键盘上方的完成，input失去焦点。

#### **Expectant Behaviors**

再次点击input能唤起键盘。

#### **Actual Behaviors**

点击input不能唤起键盘。
且页面上所有的input都出现点击不能唤起键盘，切换路由也不行，只能刷新页面。

**Comment by xxyan0205** [comment]
是否使用了fastclick？

**Comment by s749312025** [comment]
是的

**Comment by xxyan0205** [comment]
按照下面这种方式初始化fastclick
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=FastClick

**Comment by s749312025** [comment]
是我初始化方式不对
