### ISSUE TITLE
可以在select选择器中增加异步搜索功能吗？

### ISSUE THREAD

**Issue by qbl962464** [didi/mand-mobile#518]
类似于这种
![image](https://user-images.githubusercontent.com/27841848/62187262-5b9f9a80-b39b-11e9-96ab-34074259bae2.png)

**Comment by xxyan0205** [comment]
这是在桌面端的交互场景吧？

**Comment by qbl962464** [comment]
> 这是在桌面端的交互场景吧？

我们这个业务场景是当业务员在进行报价的时候，通过在这个select框内输入数据，通过输入的数据进行模糊查询，将符合条件的设备展示在下方，方便业务员快速选择。

**Comment by xxyan0205** [comment]
上述的select框跟目前的Selector组件还是有较大的区别

**Comment by lin09** [comment]
在selector的header插槽里拓展搜索功能后，data 的长度有变化时，有滚动BUG，<MdSelector>的<MdScrollView>的滚动数据没更新

**Comment by lin09** [comment]
> 上述的select框跟当前的Selector组件还是有不一致的区别，如果有类似需求，可在selector的header插槽里扩展搜索功能

在selector的header插槽里拓展搜索功能后，data 的长度有变化时，有滚动BUG，<MdSelector>的<MdScrollView>的滚动数据没更新

**Comment by lin09** [comment]
@xxyan0205 `在selector的header插槽里拓展搜索功能后，data 的长度有变化时，有滚动BUG，<MdSelector>的<MdScrollView>的滚动数据没更新`
