### ISSUE TITLE
md-scroll-view 的@end-reached 初始化自动触发，后面就无效了

### ISSUE THREAD

**Issue by chuangdao** [didi/mand-mobile#531]
<md-scroll-view
        ref="scrollView"
        :scrolling-x="false"
        @refreshing="filmList"
        @end-reached="moreFilmList"
        @scroll="closeComment"
      ></md-scroll-view>
页面一加载 就触发了@end-reached 的moreFilmList方法。并没有触底。然后拉到底部，无法触发moreFilmList事件了。

**Comment by supergaojian** [comment]
请配合auto-reflow使用

**Comment by chuangdao** [comment]
为何一加载页面，就会触发@end-reached="moreFilmList"。并没有触底

**Comment by supergaojian** [comment]
经过测试回归，未发现初始化直接触发end-reached事件，请确认您代码逻辑
