### ISSUE TITLE
[bug-report] slider 切换样式

### ISSUE THREAD

**Issue by dinglittle** [didi/mand-mobile#532]
#### Mand Mobile Version
2.2.4            

#### Vue Version
2.6.10       

#### Model / OS & Browser Info
功能不需要这个!       

#### Recurring Steps
无法根据条件切换样式

#### Expectant Behaviors
希望增加 切换样式

#### Actual Behaviors
无法根据条件切换 slider 样式, 现有组件太死板

**Comment by xxyan0205** [comment]
您好，该类issue属于`feature-request`，请选择该类型，并回答相关问题
