### ISSUE TITLE
ScrollView依然在移动端不能上拉

### ISSUE THREAD

**Issue by wulichenyang** [didi/mand-mobile#533]
Vue.js上使用，电脑和手机都是同样的问题 ，.md-scroll-view设置固定高度，且overflow:hidden，内部列表内容超出。

问题：第一次通过导航切换子路由到该页面，下滚加载更多，添加数据后无法继续下滚，会回弹。

但是刷新后可以继续下滚加载。

**Comment by xxyan0205** [comment]
您好，由于issue中缺少关键信息和相关复现示例将会被关闭，请使用[mand-mobile-issue-helper](https://mand-mobile.github.io/mand-mobile-issue-helper/)重新创建
