### ISSUE TITLE
ScrollView 设置auto-reflow 配合popup无法记录以前滚动记录

### ISSUE THREAD

**Issue by Niofh** [didi/mand-mobile#534]
ScrollView 设置auto-reflow 配合popup无法记录以前滚动记录。
1. 点击弹窗popup,异步请求数据
2. ScrollView  auto-reflow 自动计算高度
3. 关闭popup 用户滚动的高度默认重置为0 ，下次打开popup时候已经在最顶部

**Comment by xxyan0205** [comment]
您好，由于issue中缺少关键信息和相关复现示例将会被关闭，请使用mand-mobile-issue-helper重新创建

**Comment by LLwanran** [comment]
1、可以在内容发生变化时，在$nextTick调用scrollTo滚动至指定位置
2、改为手动初始化，调用scrollTo也一样
无论如何，scrollY你得自行记录保存

**Comment by AnMokoto** [comment]
`this.autoReflow && this.$_initAutoReflow()` https://github.com/didi/mand-mobile/blob/d6747467ae4eab3cbaaa62eeef9421912245093f/components/scroll-view/index.vue#L209-L213
每过100毫秒去刷新布局。调用 `scroller` 的 `setDimensions` , 
https://github.com/didi/mand-mobile/blob/d6747467ae4eab3cbaaa62eeef9421912245093f/components/scroll-view/index.vue#L381-L404

https://github.com/didi/mand-mobile/blob/d6747467ae4eab3cbaaa62eeef9421912245093f/components/_util/scroller.js#L829

当布局 `display:none` 时，获取到的 `Height` `Width`  为0，
其他所依赖的计算回调数值 **scrollX(left)**  **scrollY(top)** 就会错误
https://github.com/didi/mand-mobile/blob/d6747467ae4eab3cbaaa62eeef9421912245093f/components/scroll-view/index.vue#L155-L161
https://github.com/didi/mand-mobile/blob/d6747467ae4eab3cbaaa62eeef9421912245093f/components/scroll-view/index.vue#L351-L361



目前的解决，keepalive时，走activated 模拟 定时器调用reflowScroller，deactivated时清除，
`auto-reflow` = false, `manual-init` = false

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/pull/595/commits/a86d6b947235c0549d9abc5ec05ccb1661ebb06d

2.5.4，提了一个新的改动，可动态设置autoReflow。因此可根据是否展示来开关autoReflow

```html
<md-scroll-view
  v-show="isShow"
  :auto-reflow="isShow"
>
 <!-- content -->
</md-scroll-view>
```
