### ISSUE TITLE
[bug-report] ImageReader 在Android机上的缺陷

### ISSUE THREAD

**Issue by zhougonglai** [didi/mand-mobile#536]
#### Mand Mobile Version
2.4.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
Honor/Android/微信浏览器       

#### Node Version, Package Management Tool

node 12.7.0/npm 6.10.0

#### Recurring Links
https://codesandbox.io/s/mand-mobile-quick-start-8pzxw?fontsize=14

#### Recurring Steps
加上mime的类型限制['jpg','jpeg','png']

#### Expectant Behaviors
期望:
1.mime的类型限制能够在用户选择错误的类型文件 进入@error method
2.Android机上图片区的文件可以选择
3.加了类型限制仍然可以选择拍照

#### Actual Behaviors
实际:
1.mime在用户选择其他类型的文件在Android机上既没有进入@complete.也没有进入@error,Win 10上则是进入了@complete
2.Android机上默认的 '图片'栏内的文件全部被置灰无法选择.且符合 mime和size的限制.但是可以选择'图库'/'文件管理'栏的'所有'文件(无类型约束)
3.加上mime类型限制后Android机没有拍照选项.直接进入相册

![b2bb2017e6b67831e059392f0aef87f](https://user-images.githubusercontent.com/10954751/63237603-3d7bda80-c275-11e9-8cd5-f69c36c17582.jpg)
![dabff248e06bb01cea0047b97f2aac2](https://user-images.githubusercontent.com/10954751/63237609-42d92500-c275-11e9-9115-548ba9c04c66.jpg)

**Comment by zhougonglai** [comment]
> #### Mand Mobile Version
> 2.4.1
> 
> #### Vue Version
> 2.6.1
> 
> #### Model / OS & Browser Info
> Honor/Android/微信浏览器
> 
> #### Node Version, Package Management Tool
> node 12.7.0/npm 6.10.0
> 
> #### Recurring Links
> https://codesandbox.io/s/mand-mobile-quick-start-8
> 
> #### Recurring Steps
> 加上mime的类型限制['jpg','jpeg','png']
> 
> #### Expectant Behaviors
> 期望:
> 1.mime的类型限制能够在用户选择错误的类型文件 进入@error method
> 2.Android机上图片区的文件可以选择
> 3.加了类型限制仍然可以选择拍照
> 
> #### Actual Behaviors
> 实际:
> 1.mime在用户选择其他类型的文件在Android机上既没有进入@complete.也没有进入@error,Win 10上则是进入了@complete
> 2.Android机上默认的 '图片'栏内的文件全部被置灰无法选择.且符合 mime和size的限制.但是可以选择'图库'/'文件管理'栏的'所有'文件(无类型约束)
> 3.加上mime类型限制后Android机没有拍照选项.直接进入相册
> 
> ![b2bb2017e6b67831e059392f0aef87f](https://user-images.githubusercontent.com/10954751/63237603-3d7bda80-c275-11e9-8cd5-f69c36c17582.jpg)
> ![dabff248e06bb01cea0047b97f2aac2](https://user-images.githubusercontent.com/10954751/63237609-42d92500-c275-11e9-9115-548ba9c04c66.jpg)

**Comment by zouhangwithsweet** [comment]
这里的图片上传用的是 input type=file，在不同的安卓平台的实现方式不同；安卓原生端可以使用 JSBridge 配合下，微信端需要用微信的 SDK
