### ISSUE TITLE
[bug-report] 有部分组件直接使用了 P 标签，容易出现一些样式问题

### ISSUE THREAD

**Issue by Akimyou** [didi/mand-mobile#537]
#### Mand Mobile Version
2.4.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
andorid       

#### Node Version, Package Management Tool

node 10

#### Recurring Links
https://didi.github.io/mand-mobile/#/zh-CN/docs/co

#### Recurring Steps
审查 Popup demo 的底部 Popup，发现
`.md-popup-title-bar .title-bar-title p.title` 就是一个 P 标签。
但是 Demo 的全局使用了

```
* {
    margin: 0;
    padding: 0;
    -webkit-touch-callout: none;
    list-style: none;
}
```

#### Expectant Behaviors
希望尽量避免使用 P 标签等可能自带浏览器默认样式的 HTML 标签
或者在文档中强调需要全局 CSS reset
或者在组件内部将该类型的标签彻底格式化好

#### Actual Behaviors
P 标签可能继承浏览器样式，带上 margin 影响布局

---
类似的还有，这些
```
p.md-cell-item-title,
.md-input-item-msg p,
p.md-button-content,
p.md-cell-item-brief
  margin 0
```

**Comment by xxyan0205** [comment]
在文档快速上手的使用前准备部分有说明

**Comment by Akimyou** [comment]
https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E4%BD%BF%E7%94%A8%E5%89%8D%E5%87%86%E5%A4%87

```
使用前准备#
Normalize or Reset
为标准化浏览器元素的样式，推荐引入Normalize.css或Reset CSS
```
https://github.com/necolas/normalize.css/blob/master/normalize.css

normalize.css 并不会格式化 P 标签，文档上写到的 `推荐引入Normalize.css或Reset CSS`，是否不太妥当？

**Comment by xxyan0205** [comment]
此处说明并不是单独为了格式化标签，另外格式化标签也不止p。因为应用层可能会有自己的通用样式或定制的样式，用户可根据自己的应用情况选择第三方引入。

**Comment by Akimyou** [comment]
我的项目中之前用的是
normalize.css + mand-mobile 1.0，各个组件都表现的正常
近期切换到 mand-mobile 2.0 后，发现部分组件与组件 demo 表现得不一致，经查发现了 P 标签未格式化导致的问题

我的建议是
- 明确说明，mand-mobile 2.0 需要 Reset CSS，特别是 P 标签，只使用 Normalize.css 可能会有样式问题
- 或者，mand-mobile 2.0 的组件中，彻底格式化这种可能带格式的 HTML 标签，或者改用 span 或者 div

总之，在通用组件库中使用 P，UL，LI 等，但又不完全格式化，是不建议的。我想不到这样做的理由。

例如这个：
https://github.com/didi/mand-mobile/blob/master/components/field/index.vue
```
<p v-if="brief" class="md-field-brief" v-text="brief"></p>
```

**Comment by xxyan0205** [comment]
> 在通用组件库中使用 P，UL，LI 等，但又不完全格式化，是不建议的。我想不到这样做的理由

之前曾经考虑过把reset.css内置，但是又考虑到某种程度上做了侵入，权衡之后没有加入。我们会重新讨论内置reset部分样式的可能性。

**Comment by Akimyou** [comment]
Ok, Thanks.
