### ISSUE TITLE
[bug-report] picker的UI问题-省市过长时无法完全显示

### ISSUE THREAD

**Issue by fzq2016** [didi/mand-mobile#538]
#### Mand Mobile Version
2.4.0            

#### Vue Version
3.4.1       

#### Model / OS & Browser Info
iphone5       

#### Node Version, Package Management Tool

npm@6.4.1

#### Recurring Steps
省、市、区内容过长时，无法完整显示，比如demo页面的香港特别行政区等无法完整显示；

#### Expectant Behaviors
以下方案都可以：
1. 可以拖动显示完整的内容
2. 分多行显示

#### Actual Behaviors
无法显示完整

**Comment by xxyan0205** [comment]
感谢建议，但是目前这两个方案实施起来成本都比较高，因为都会影响到picker每一列的滚动计算。
