### ISSUE TITLE
【Check】选择项组可以设置必须选择一个的功能吗？

### ISSUE THREAD

**Issue by qbl962464** [didi/mand-mobile#543]
![image](https://user-images.githubusercontent.com/27841848/63400641-1bb25d00-c407-11e9-9b68-418255fbf7ca.png)

类似图上的业务场景，必须选择一个限额，不可以不选。或者radio可以做成这种方块的形式吗？

**Comment by xxyan0205** [comment]
可以考虑增加RadioBox
