### ISSUE TITLE
[TabPicker]默认值可以赋值在弹框展开之后的效果，点击弹框之前无法做到回显（看到的还是请选择，而不是数据赋值之后，页面直接显示选中的项）

### ISSUE THREAD

**Issue by SunshineMibai** [didi/mand-mobile#546]
The issue which is not created via <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> will be closed immediately.

---

注意：不是用 <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> 创建的 issue 会被立即关闭。

**Comment by xxyan0205** [comment]
使用存在问题，可参考示例https://didi.github.io/mand-mobile/examples/
