### ISSUE TITLE
[bug-report] Picker组件的change事件问题-回调时机不合理

### ISSUE THREAD

**Issue by LLwanran** [didi/mand-mobile#547]
Mand Mobile Version
2.4.2

Vue Version
2.6.10

Model / OS & Browser Info
iPhone6 Plus

Node Version, Package Management Tool
npm@6.4.1

Recurring Steps
稍微用力滑动时，change事件必须等到停止了才有回调，否则取不到值

Expectant Behaviors
1、提前计算change回调值，哪怕用户突然中止，此时也应该有回调值
2、希望animationDuration可以配置，实际中可能并不希望此处动画时间那么长，仿佛停不下来的样子
3、数据支持loop循环，尤其是选择0-59分钟时，iOS原生系统的闹钟那种体验更符合实际需求

**Comment by xxyan0205** [comment]
提前计算存在难度，最后速度衰减和回正两个过程很难预估，在当下与其为了体验给个错的不如保证准确。
动画时间并不是animationDuration控制的，是上述提到的速度衰减，是尽量在细腻的体验和时间上尽量短做的权衡，如果过快就像刹车过猛给人感觉突然且不适。相关api可以暴露但收益不大因为可调的空间非常有限。
作为组件库中的一个基础组件，目前这个需求暂时不会考虑，可能在专门的picker组件的上层封装更为合适，目前可通过数据的处理来模拟。

前两点我们会持续的实验和优化以期找到更优的平衡点，如果有好的方案也欢迎pr。

**Comment by LLwanran** [comment]
感谢回复！
我是感觉此处有点类似于lottery转盘那种，不管转多久，最终落地值已经提前计算出来了，这样哪怕用户此时退出或保存了，也是有值可取的，不至于为空。
我看到mand-mobile是在scrollingComplete时设置的回调，所以必须要等到Scroller停止才能生效。而其他实现我所述功能的插件区别大概是在GestureEnd时就设置了回调，而只是让Scroller再滚动到指定位置；
滚动速度我看其他是用time和speed共同计算来控制的；
至于数据loop也确实如你所述，暂时用数据模拟可行，其他的我看大概也是generate出数据再append和prepend进去的。
这些实现起来难度确实挺大的，希望mand-mobile功能越做越强大！

**Comment by xxyan0205** [comment]
> 而其他实现我所述功能的插件区别大概是在GestureEnd时就设置了回调，而只是让Scroller再滚动到指定位置

目前mand-mobile内部使用的Scroller在这个地方存在区别，只能先滚动再减速，减到一定阈值内结束减速再回正最后触发scrollingComplete，故无法提前指定滚动位置，所以很难实现所述这个效果，我们可在讨论在下个大的版本中整个替换Scroller的可能性。
