### ISSUE TITLE
[bug-report] 图片选择器在ios下点击无响应

### ISSUE THREAD

**Issue by 15362532197** [didi/mand-mobile#555]
#### Mand Mobile Version
1.2.1            

#### Vue Version
2.5.2       

#### Model / OS & Browser Info
iphone6       

#### Node Version, Package Management Tool

yarn

#### Recurring Steps
在ios下图片选择器点击添加图片

#### Expectant Behaviors
能相应，能上传

#### Actual Behaviors
在ios下图片选择器点击添加图片无响应

**Comment by xxyan0205** [comment]
系统版本，什么浏览器及版本？

**Comment by supergaojian** [comment]
请升级mand-mobile版本
