### ISSUE TITLE
[bug-report] MdScrollView的警告

### ISSUE THREAD

**Issue by artiely** [didi/mand-mobile#556]
#### Mand Mobile Version
2.3.0             

#### Vue Version
2.6.10       

#### Model / OS & Browser Info
all       

#### Recurring Steps
更新了到了最新的mand发现大量MdScrollView的警告，一直回滚到2.3.0以下的版本才没有了，并不清楚警告是否会影响使用，我是按需加载的组件，并没有引入MdScrollView组件，却有大量警告，如果我进入该组件警告同样存在,但是TabBar，和NavBar我是有使用的。

#### Expectant Behaviors
无警告和错误，

#### Actual Behaviors
[Vue warn]: Property or method "$_onScrollerTouchStart" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-b

---
"<MdScrollView> at node_modules/mand-mobile/components/scroll-view/index.vue
       <MdTabBar> at node_modules/mand-mobile/components/tab-bar/index.vue
         <TabNavBar> at src/components/tab-nav"

**Comment by supergaojian** [comment]
还不能复现问题，请使用codesandbox复现问题，谢谢

**Comment by artiely** [comment]
我问题解决了，按需加载之前的版本librarydirectory是components而现在改成了lib.对应的修改过来就可以了，升级的一个小坑。
