### ISSUE TITLE
[bug-report] 自定义svg没有生效

### ISSUE THREAD

**Issue by Stpcurry30** [didi/mand-mobile#558]
按官方文档安装svg-sprite-loader依赖并配置，但是代码并没有生效，没有看到图标。是不是漏做了什么？

#### Mand Mobile Version
2.4.2            

#### Vue Version
2.6.10       

#### Model / OS & Browser Info
chrome手机模拟器iPhone6/7/8

**Comment by xxyan0205** [comment]
可能原因有很多，可能是配置原因，也可能是图标原因。可以参考下面的示例工程：
https://github.com/mand-mobile/vue-cli3-example/blob/custom-theme/vue.config.js#L29

**Comment by Stpcurry30** [comment]
> 可能原因有很多，可能是配置原因，也可能是图标原因。可以参考下面的示例工程：
> https://github.com/mand-mobile/vue-cli3-example/blob/custom-theme/vue.config.js#L29

你好，我贴一下代码，你能帮你我看看吗？
页面代码：
`import '@/assets/svg/svg/rightArrow.svg'`
`<md-icon name="rightArrow" svg></md-icon>`
渲染后页面代码：`<svg class="md-icon icon-svg md-icon-rightArrow md"><use xlink:href="#rightArrow"></use></svg>`

**Comment by xxyan0205** [comment]
代码没有问题，但是渲染出来的svg不对，检查下配置

**Comment by Stpcurry30** [comment]
> 代码没有问题，但是渲染出来的svg不对，检查下配置

好的谢谢，我检查一下。

**Comment by LLwanran** [comment]
你多半是譬如在阿里图标库直接copy的svg代码过来，那就会导致你说的情况，你得适当修改一下svg里面的标签代码，参考icon组件的例子才行。比如这么定义的：
`<svg viewBox="0 0 1024 1024" preserveAspectRatio="xMidYMid" style="background:0 0">...</svg>`

**Comment by Stpcurry30** [comment]
> 你多半是譬如在阿里图标库直接copy的svg代码过来，那就会导致你说的情况，你得适当修改一下svg里面的标签代码，参考icon组件的例子才行。比如这么定义的：
> `<svg viewBox="0 0 1024 1024" preserveAspectRatio="xMidYMid" style="background:0 0">...</svg>`

我是从阿里巴巴iconfont下载的svg，然后丢进项目里的svg文件夹里的。渲染出来的use便签里面有个#shadow root(closed)

**Comment by lin2006yuo** [comment]
> > 你多半是譬如在阿里图标库直接copy的svg代码过来，那就会导致你说的情况，你得适当修改一下svg里面的标签代码，参考icon组件的例子才行。比如这么定义的：
> > `<svg viewBox="0 0 1024 1024" preserveAspectRatio="xMidYMid" style="background:0 0">...</svg>`
> 
> 我是从阿里巴巴iconfont下载的svg，然后丢进项目里的svg文件夹里的。渲染出来的use标签里面有个#shadow root(closed)

单独下载svg，不要下载整个项目，我也遇到这个问题

**Comment by zouhangwithsweet** [comment]
最简单的就是自己写一个 svg, 看看是否能够正确渲染。
