### ISSUE TITLE
[feature-request] NoticeBar能否实现内容不超出也能自动滚动

### ISSUE THREAD

**Issue by jameszzX** [didi/mand-mobile#564]
### What problem does this feature solve?
即便内容短也可以进行滚动

### What does the proposed API look like?
即便内容短也可以进行滚动

**Comment by supergaojian** [comment]
经过我们讨论，认为在内容未超出容器时，用户已经可见全部内容无需滚动提醒。
推荐您使用.md-notice-bar-content div:first-child添加滚动动画。
动画细节可参考notice-bar内置动画实现，地址：https://github.com/didi/mand-mobile/blob/master/components/notice-bar/index.vue#L199
