### ISSUE TITLE
[bug-report] [style]: 新增的"部分全局reset样式"问题

### ISSUE THREAD

**Issue by zhougonglai** [didi/mand-mobile#565]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
iphone x/IOS/微信       

#### Recurring Links
https://github.com/zhougonglai/mand-starter.git

#### Recurring Steps
update mand-mobile to @2.5.1

#### Expectant Behaviors
还是期望有个能够在响应式规范下的字体处理规范.
iphone 7/8/9下的font-size 都是 50px. 每个组件内的文字都得单个去set font-size

#### Actual Behaviors
..., audio[data-v-183a3b6c], video[data-v-183a3b6c] {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
现在项目所有没有指定font-size的文字都超级大..

---
目前也不知道 别人是怎么处理的.个人是参考了cube-ui 的 body{font-size:24px}
然后字体用 font-size: large,larger, small, smaller 这样子处理文字的.在update 到 2.5.1版本后出现了字体过大

**Comment by supergaojian** [comment]
请问您使用px2rem了么？

**Comment by zhougonglai** [comment]
> 请问您使用px2rem了么？

是用的 [postcss-pxtorem](https://github.com/zhougonglai/mand-starter/blob/master/postcss.config.js)

**Comment by xxyan0205** [comment]
主要问题是没有重置默认字体大小，关于设计规范我们目前考虑的控制其作用范围，而不侵入应用。设计规范可参考https://github.com/didi/mand-mobile/blob/master/components/_style/mixin/theme.basic.styl

**Comment by zhougonglai** [comment]
> 主要问题是没有重置默认字体大小，关于设计规范我们目前考虑的控制其作用范围，而不侵入应用。设计规范可参考https://github.com/didi/mand-mobile/blob/master/components/_style/mixin/theme.basic.styl

现在是这个[reset样式文件](https://github.com/didi/mand-mobile/pull/539/files)
覆盖面太广了.已经 侵入到每个页面的dom

**Comment by xxyan0205** [comment]
继承body的font-size，或默认字体大小。把body{font-size: 24px}放开。

**Comment by zhougonglai** [comment]
ok
