### ISSUE TITLE
[bug-report] [InputItem][Vue warn]: "isInputFormative"

### ISSUE THREAD

**Issue by zhougonglai** [didi/mand-mobile#566]
#### Mand Mobile Version
2.5.1            

#### Vue Version
^2.6.1       

#### Model / OS & Browser Info
iphone x/win 10/chrome 76       

#### Recurring Steps
<md-input-item
        placeholder="昵称"
        brief="输入一个响亮的昵称"
        :maxlength="20"
        clearable
        v-model.trim="nickName"
      ></md-input-item>

#### Expectant Behaviors
去掉[vue warn]

#### Actual Behaviors
[Vue warn]: Property or method "isInputFormative" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, 

---
2.4.1 update to 2.5.1

**Comment by gebilaoxiong** [comment]
您好，感谢您的反馈。可以提供一个可复现的地址吗，以便我们排查问题。

**Comment by zhougonglai** [comment]
抱歉.这个 反复查验.应该是误报...
