### ISSUE TITLE
[bug-report] Tabbar组件在某些情况会死循环reflow，导致页面渲染不出来或者崩溃

### ISSUE THREAD

**Issue by hangpingping** [didi/mand-mobile#567]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
mac64/chrome76.0.3809.87       

#### Node Version, Package Management Tool

node10.16.2/npm6.11.3

#### Recurring Links
https://github.com/hangpingping/mand-mobile-tabbar-test

#### Recurring Steps
1.vue-cli3.1创建一个空项目， 引入minireset.css和mand-mobile
2.修改App内容
3. 运行npm run serve 在chrome中模拟器中在宽度1080， 432， 375中调试

#### Expectant Behaviors
正常渲染

#### Actual Behaviors
内容一直渲染不出来， chrome render进程cpu飙到100 %，chrome中debugger paused后call stack 一直在inkwidth reflow

**Comment by hangpingping** [comment]
这个问题自迁移到mand-moble2就开始遇到，在tabbar组件添加了console.log
![image](https://user-images.githubusercontent.com/37317774/64689151-5e280080-d4c0-11e9-8093-f8da50aa7aad.png)
![image](https://user-images.githubusercontent.com/37317774/64689021-1c975580-d4c0-11e9-8127-e696acda8c54.png)
![image](https://user-images.githubusercontent.com/37317774/64689343-bced7a00-d4c0-11e9-8a2a-887b94d10bae.png)
在reflow方法中拿到的current-tab-bar-item的offsetWidth的值一直在两个数中循环，赋给inkwidth导致重新reflow

**Comment by supergaojian** [comment]
经过复现推荐您不要直接设置组件的样式

**Comment by supergaojian** [comment]
已经可复现问题，暂时推荐不要在外部使用vw + 百分比包裹tab-bar（内部flex计算不准确）。如果必须使用的话，您可以暂时为md-tab-bar-item添加flex: auto解决问题，我们会在下一个版本更新

**Comment by hangpingping** [comment]
我尝试将tab-bar宽度改成50vw，但问题依旧复现，vw + 百分比会导致内部flex计算不准确这种说法不正确

**Comment by supergaojian** [comment]
由于我们内置每一个item并没有给默认的flex导致了问题出现，我们会在下一个版本修复这个问题，您可以暂时为md-tab-bar-item添加flex: auto解决问题
