### ISSUE TITLE
[bug-report] import _style/global 导致大量重复样式导入的问题

### ISSUE THREAD

**Issue by Akimyou** [didi/mand-mobile#570]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
any       

#### Recurring Steps
在 https://didi.github.io/mand-mobile/#/zh-CN/docs/theme 的教程中，提到

```
@import '~mand-mobile/components/_style/global'
@import '~mand-mobile/components/_style/mixin/util'
@import '~mand-mobile/components/_style/mixin/theme.components'
@import '~mand-mobile/components/_style/mixin/theme.basic'

// 安装并引入css拓展nib(可选)
@import '~nib/lib/nib/vendor'
@import '~nib/lib/nib/gradients'

// 覆盖样式变量
color-primary = #1AAD19
```
其中的 `@import '~mand-mobile/components/_style/global'` 文件是一个实际样式文件，其他的都是样式变量和函数等。

在此处导入一个实际样式文件，会导致导入大量重复的样式。

如下图：

<img width="168" alt="屏幕快照 2019-09-10 下午3 04 44" src="https://user-images.githubusercontent.com/14974790/64591441-61e25700-d3dc-11e9-9696-c408bfba407d.png">

#### Expectant Behaviors
是否考虑不在 `theme.custom.styl` 中导入实际样式文件，只导入样式变量与函数？
可以编写一个重制组件内部样式的样式函数，在每个组件中都调用该函数

**Comment by xxyan0205** [comment]
大量重复样式导入的问题是指？

**Comment by Akimyou** [comment]
比如，在 dev serve 的模式下，审查发现这个写在 global 中的样式被重复导入了很多次。

<img width="180" alt="屏幕快照 2019-09-10 下午3 19 43" src="https://user-images.githubusercontent.com/14974790/64592394-79bada80-d3de-11e9-8454-a3a5bdee6670.png">

**Comment by zouhangwithsweet** [comment]
因为你 vue.config.js cssoptions import 了 这个 styl, 你把 global.styl 直接在 main.ts  引入，theme.style 去掉这个引入就行了

**Comment by Akimyou** [comment]
> 因为你 vue.config.js cssoptions import 了 这个 styl, 你把 global.styl 直接在 main.ts 引入，theme.style 去掉这个引入就行了

那是不是 https://didi.github.io/mand-mobile/#/zh-CN/docs/theme，这个文档描述的不太准确？

我试了下最新的 `vue-cli-plugin-mand`，生成了一个定制主题的项目，发现项目的 `theme.custom.styl` 没有引入 ` global.styl ` 的，反而在 man.js 中引入了 `reset.css` 和 `normalize.css`，这是基于什么考虑？

啥时候需要用到 ` global.styl ` 这个文件呢？

**Comment by xxyan0205** [comment]
不准确，theme.custom.styl 的作用是mixin，现在可以在入口处引入global.styl

**Comment by Akimyou** [comment]
我目前的理解和建议

非定制主题下：mand-mobile 默认导入了 global.styl，（使用 vue-cli-plugin-mand 创建的非定制主题项目
定制主题下：默认不会导入 global.styl（使用 vue-cli-plugin-mand 创建的定制主题项目

非定制主题下没啥问题。
定制主题下，有些问题

- global.styl 不能在 theme.custom.styl  中导入，该文件只用于导入 mixin 和 var

建议
- 修改下，https://didi.github.io/mand-mobile/#/zh-CN/docs/theme，这个文档上相关的描述
- 修改下，vue-cli-plugin-mand 初始化定制主题项目的时候的代码

**Comment by hui-fly** [comment]
@zouhangwithsweet 请教下为什么在main中引入就不会出现大量重复了呢，这跟cssoptions 中的import的关系是什么？

**Comment by zouhangwithsweet** [comment]
> @zouhangwithsweet 请教下为什么在main中引入就不会出现大量重复了呢，这跟cssoptions 中的import的关系是什么？

因为 `css` 不会被 `treeshaking`，你在`cssoptions`配置相当于在每个 `<style lang="stylus">`标签里都引入了一遍`@import xxx.styl`
