### ISSUE TITLE
已有的vue项目vue invoke mand后 vue.config.js的配置全部被删除了??

### ISSUE THREAD

**Issue by wangjun521** [didi/mand-mobile#576]
如题  只剩mand-mobile的css的配置了  这不太合适吧 今天项目配置全没了

**Comment by xxyan0205** [comment]
目前只支持新项目的创建

**Comment by wangjun521** [comment]
文档上面没看到相关说明啊   建议加一下 不然太惨了 hhhhh

**Comment by xxyan0205** [comment]
![image](https://user-images.githubusercontent.com/8409100/65003869-f1cc5780-d92c-11e9-8905-d5617a2aceab.png)
