### ISSUE TITLE
引用源码 Toast 报错 

### ISSUE THREAD

**Issue by yuancongcong** [didi/mand-mobile#582]
module.exports = {
  presets: [
    '@vue/app'
  ],
  plugins: [
    [
      'import',
      {
        libraryName: 'mand-mobile',
        libraryDirectory: 'components'
      }
    ]
  ]
}
报错行
vue.runtime.esm.js:1888 TypeError: r.show is not a function

**Comment by yuancongcong** [comment]
vue-cli  自定义主题色怎么配置源码编译

**Comment by xxyan0205** [comment]
https://github.com/mand-mobile/vue-cli3-example/tree/custom-theme
