### ISSUE TITLE
[bug-report] ScrollView 页面刚加载是，出现 refreshing 和 end-reached 一起执行

### ISSUE THREAD

**Issue by abj3ct10n** [didi/mand-mobile#584]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.5.2       

#### Model / OS & Browser Info
chrome       

#### Recurring Links
https://codesandbox.io/s/vue-template-j86yj?fontsize=14

#### Recurring Steps
使用的是 flex 布局，所以不清楚和这个有没有关系。但是自己测试了一下，好像没有关联。。
进入页面时会触发一次刷新事件，因为刷新事件和初次请求数据的业务是一样的。所以用在一起了。
然后大概在刷新事件执行完毕后，就执行了加载更多事件。。。
然后会出现无法加载更多。。很奇怪的问题，不知道哪里出了问题

#### Expectant Behaviors
初次加载只执行刷新事件

#### Actual Behaviors
初次加载执行完刷新事件后会接着执行加载更多事件。
测试过初次加载超过屏幕尺寸大小的数据，依旧会执行加载更多事件。

**Comment by abj3ct10n** [comment]
非常神奇的是，我手动触发 refresh 事件，他并不会执行加载更多事件。

即在 create 生命周期里触发 refresh 事件
`this.$refs.scroll.triggerRefresh()`
这样就不会出现执行加载更多事件。。

非常奇怪。。。

**Comment by abj3ct10n** [comment]
在 create 生命周期会报错，请在 mounted 执行

**Comment by abj3ct10n** [comment]
emmm 很奇怪，在 demo 里面测试手动触发没问题，但是在本地手动触发就不行。。

**Comment by supergaojian** [comment]
请先了解vue的生命周期原理，谢谢！

**Comment by abj3ct10n** [comment]
> 请先了解vue的生命周期原理，谢谢！

以前别的项目也用 mand-mobile 的 ScrollView 没有问题，但是在这里一样的调用一样的方法，还是不行。

哪怕是生命周期原理，也烦请告知是渲染是出错了还是怎么的。多谢

**Comment by xxyan0205** [comment]
> 哪怕是生命周期原理，也烦请告知是渲染是出错了还是怎么的。多谢

```js
  refresh() {
    console.log(`${new Date().getTime()}, execute refresh!`);

   // `refresh`中更新数据是异步的
    setTimeout(() => {
      this.list = Array.from(new Array(100), (k, v) => v);
      this.page = 0;
      this.count = 10;
      this.$refs.scroll.finishRefresh();
    }, 2000);
  }
```

仔细看这段代码，并重点关注`下拉刷新`和`上拉加载`两个事件的触发时机：

当你手动触发`下拉刷新`时，数据要在2s后才变更，这意味着当前的content的内容是空的，一定会触发`endReached`，所以无论你初次加载超过屏幕尺寸大小的多少数据，那都是2s以后的事情，第一次的`pageTurning`已经被调用了。

如果想解决这个问题，需要`下拉刷新`的状态锁，在下拉刷新结束前，避免触发`endReached`。

**Comment by abj3ct10n** [comment]
> > 哪怕是生命周期原理，也烦请告知是渲染是出错了还是怎么的。多谢
> 
> ```js
>   refresh() {
>     console.log(`${new Date().getTime()}, execute refresh!`);
> 
>    // `refresh`中更新数据是异步的
>     setTimeout(() => {
>       this.list = Array.from(new Array(100), (k, v) => v);
>       this.page = 0;
>       this.count = 10;
>       this.$refs.scroll.finishRefresh();
>     }, 2000);
>   }
> ```
> 
> 仔细看这段代码，并重点关注`下拉刷新`和`上拉加载`两个事件的触发时机：
> 
> 当你手动触发`下拉刷新`时，数据要在2s后才变更，这意味着当前的content的内容是空的，一定会触发`endReached`，所以无论你初次加载超过屏幕尺寸大小的多少数据，那都是2s以后的事情，第一次的`pageTurning`已经被调用了。
> 
> 如果想解决这个问题，需要`下拉刷新`的状态锁，在下拉刷新结束前，避免触发`endReached`。

多谢，因为之前旧版本的 `mand-mobile` 也是这样用的，没有出现过问题。
我理解差不多就是在数据渲染的时候，因为已经是空内容直接就是触底的。导致触发了 `endReached` 事件。
自己调用 refresh 方法就一定会触发 `endReached` 事件，最后是调用 `triggerRefresh()` 解决的。
没有上锁排斥 `endReached`
多谢
