### ISSUE TITLE
Toast组件 content默认显示的长度是多少？

### ISSUE THREAD

**Issue by kongling94** [didi/mand-mobile#588]
Toast组件content默认文字显示长度是多少个字节？这边通过请求拿到的err.msg过长并没有折行显示，而是省略为...

**Comment by supergaojian** [comment]
如果您有看toast的样式的话，您会发现我们是通过设置了toast的宽度实现字符隐藏的

**Comment by supergaojian** [comment]
如果希望换行，请使用css hack

**Comment by kongling94** [comment]
另外，在modal中嵌套的浮动表单项InputItem，在手机上输入的时候可能会出现输入的文字有延迟卡顿

**Comment by supergaojian** [comment]
请问有稳定复现机型么？
您如何使用的InputItem？
可以贴出您可复现的最小粒度代码demo么？
我们好有针对性的排查问题

**Comment by kongling94** [comment]
昨晚上出现的频繁，今天上午暂时没有出现此问题

**Comment by supergaojian** [comment]
请确定使用inputItem的相关事件回调逻辑导致的，例如：动态搜索等

**Comment by kongling94** [comment]
动态所搜在表单项中只有一个使用的是，触发效果是在bulr时
