### ISSUE TITLE
TextareaItem 多行输入框没有开发清除按钮

### ISSUE THREAD

**Issue by denglai** [didi/mand-mobile#589]
TextareaItem 多行输入框没有开发清除按钮，类似于input输入内容后，后边带的清除按钮

**Comment by msdlisper** [comment]
下一版会带上, 谢谢你的宝贵意见~

**Comment by denglai** [comment]
失去焦点的时候，小叉叉没有消失，会一直显示小叉叉

**Comment by msdlisper** [comment]
@denglai 下一个小迭代会在有焦点的时候显示小叉叉~

**Comment by msdlisper** [comment]
@denglai 对的, 和input-item的行为保持一致
