### ISSUE TITLE
TabPicker 多级联动选择器,选择地区文字过长，最后一个请选择出不来

### ISSUE THREAD

**Issue by denglai** [didi/mand-mobile#590]
![image](https://user-images.githubusercontent.com/20442608/65746249-e4834a00-e130-11e9-80b1-ffb1ab82dd00.png)
![image](https://user-images.githubusercontent.com/20442608/65746252-e77e3a80-e130-11e9-9085-7f4566957c4e.png)
选择文字过长的地区，最后一个请选择没有显示出来，划动也回弹不回来

**Comment by xxyan0205** [comment]
fixed@2.5.3
