### ISSUE TITLE
[bug-report] 升级最新mand版本之后初始化的css，影响到了我们原来的项目

### ISSUE THREAD

**Issue by Jiyr0119** [didi/mand-mobile#592]
#### Mand Mobile Version
2.5.2            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
谷歌浏览器模拟器       

#### Recurring Steps
我们的项目

#### Expectant Behaviors
初始化的css 去掉 font:inherit 

#### Actual Behaviors
影响我们现有项目，不能升级用最新的版本
#### Mand Mobile Version
2.5.2            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
谷歌浏览器模拟器       

#### Recurring Steps
我们的项目

#### Expectant Behaviors
怎么能不用你们初始化的css

#### Actual Behaviors
影响我们现有项目，不能升级用最新的版本

![image](https://user-images.githubusercontent.com/28727613/66698261-e2afae00-ed0e-11e9-8e64-4fc726e35076.png)

**Comment by xxyan0205** [comment]
升级至2.5.3

**Comment by Jiyr0119** [comment]
问题解决了。
再跟你们提几个建议。

- 我使用的感受，非常好，适合金融场景。但是感觉你们star老上不来，是不是可以考虑像 iview 那样 多给自己做做宣传  掘金呀 这那的   或者出个什么专栏。

- 就是虽然说提供了这种解决字体大小的模版项目，但是比如我们这个项目就是先用vux 后来才换的mand，当时搞那个 px2rem  各种找  加你们官方群  看 issues 之类的才搞定。 这种问题看你们能怎么优化一下，或者官方文档把这些解决方法也加进去。
 
愿star 早日破万

**Comment by xxyan0205** [comment]
感谢建议，过去的确有些忽略了运营宣传，把更多的精力放在了打磨项目本身，另外我为面向金融场景也限制了一些使用范围。关于上手问题也一直在想办法，包括vw/vh版本，脚手架模板，cli插件等等。我们目前也在尝试迭代一套更贴近业务层，使用更加灵活的pro级别的组件。
