### ISSUE TITLE
mand-mobile文档 标签组件 示例代码不正确

### ISSUE THREAD

**Issue by HuangJunjia** [didi/mand-mobile#594]
标签组件代码中线框和阳文的代码有误。
``` javascript
<template>
  <div class="md-example-child md-example-child-tag md-example-child-tag-2">
    <tag size="large" shape="square" font-color="#FF8843" type="ghost">可选</tag>
    <tag size="small" shape="square" font-color="#28AA91" type="ghost">可选</tag>
  </div>
</template>
```
```<tag></tag>```应为```<md-tag></md-tag>```

The issue which is not created via <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> will be closed immediately.

---

注意：不是用 <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> 创建的 issue 会被立即关闭。

**Comment by xxyan0205** [comment]
代码本身没有问题，组件注册的是 Tag
