### ISSUE TITLE
推荐的components引入方法兼容

### ISSUE THREAD

**Issue by mimanghuilang** [didi/mand-mobile#600]
通过引入组件源码(components目录下)，并覆盖样式变量的方式来实现主题定制后发现在华为mate8上面打不开，换成lib引入能打开
打不开的时候如下图
![image](https://user-images.githubusercontent.com/28793958/67650172-d8301e00-f976-11e9-8da7-40379caaff02.png)
手机的userAgent在lib方式下打开如下图
![2c21f4334e52f759e6ff478744ac3ca](https://user-images.githubusercontent.com/28793958/67650095-87b8c080-f976-11e9-909e-04ac34449b70.jpg)

**Comment by supergaojian** [comment]
您使用的是vue-cli2还是vue-cli3，从components引入需要跟随项目一起编译的

**Comment by mimanghuilang** [comment]
> 您使用的是vue-cli2还是vue-cli3，从components引入需要跟随项目一起编译的

我使用的是vue-cli3,运行步骤如下图
![image](https://user-images.githubusercontent.com/28793958/67875645-9e773700-fb71-11e9-982f-180e03cd12f9.png)

刚初始化成功是能正常打开，当删除原有的node_modules重新install然后运行项目就会打不开

**Comment by zouhangwithsweet** [comment]
应该是没加 polyfill，引入 core-js 即可
