### ISSUE TITLE
[bug-report] md-image-viewer 组件点击后，图片一半在屏幕内，一半在屏幕外，请问这个怎么解决？

### ISSUE THREAD

**Issue by WaderWei** [didi/mand-mobile#604]
#### Mand Mobile Version
2.5.3            

#### Vue Version
2.6.10       

#### Model / OS & Browser Info
微信浏览器       

#### Recurring Steps
直接复制官网md-image-viewer组件的demo

#### Expectant Behaviors
和官网展示的一样

#### Actual Behaviors
md-image-viewer 组件点击后，图片一半在屏幕内，一半在屏幕外

**Comment by xxyan0205** [comment]
请使用统一设备扫码官网demo 看是否复现该问题，如果没有请提供复现问题的demo https://codesandbox.io/

**Comment by WaderWei** [comment]
没有复现，我在github上创建了一个有这种问题的项目，麻烦看一下
https://github.com/WaderWei/ImageViewer.git

**Comment by WaderWei** [comment]
> > 没有复现，我在github上创建了一个有这种问题的项目，麻烦看一下
> > https://github.com/WaderWei/ImageViewer.git
> 
> 没有找到使用image-viewer的地方，通过浏览器的检查工具check一下样式，看是否被外部样式影响。如果有需要可以加官方交流QQ群寻求帮助，493305323

是我这边外部样式导致的，多谢麻烦了
