### ISSUE TITLE
[bug-report] 移动端 ScrollView 滚动区域 中使用 inputItem ，键盘弹起输入内容上顶

### ISSUE THREAD

**Issue by 113523249** [didi/mand-mobile#616]
#### Mand Mobile Version
2.5.5            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
iphone safari/ android webivew       

#### Recurring Steps
在IM聊天使用了ScrollView中嵌套inputItem控件，数据占满单前屏幕后，当焦点在ScrollView中的inputItem控件，就会触发系统键盘弹出，ScrollView中的内容就会往上顶，键盘消失后ScrollView的内容就有一块和键盘一样大小的空白

#### Expectant Behaviors
键盘缩回后内容恢复到底部

#### Actual Behaviors
键盘缩回后内容还停留在被顶上去的位置，并且ScrollView新增内容后，内容尾部一直有空白的一部分

**Comment by xxyan0205** [comment]
是否开启 auto-reflow

**Comment by 113523249** [comment]
@xxyan0205 开启和关闭都一样存在

**Comment by xxyan0205** [comment]
https://www.jianshu.com/p/e36cb1000284  请尝试该方法是否有效如果无效，还需要提供具体的设备信息以便复现问题（机型，系统版本，浏览器及其版本）
