### ISSUE TITLE
Radio组件，disable时，把之前选中的遮盖掉，建议置灰，不可点击就好了。

### ISSUE THREAD

**Issue by yaumingyu** [didi/mand-mobile#619]
The issue which is not created via <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> will be closed immediately.

---

注意：不是用 <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> 创建的 issue 会被立即关闭。

**Comment by xxyan0205** [comment]
设计规范中要求是这样，如果有特殊需求，可以把自带的图表名称置空，使用自定义插槽定制内容样式
