### ISSUE TITLE
Dialog 和 Toast无法同时使用

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#62]
> mand-mobile version/项目版本
1.1.0
> os version & browser version/操作系统版本&浏览器版本
ios

> recurring steps/复现步骤
1. 显示Dialog
2.点击确定按钮,Toast.loading

> expectant behaviors/期待行为
dialog和toast共存，toast在dialog之上

> actual behaviors/实际行为
toast在dialog之下

**Comment by zlab** [comment]
Captcha 验证码也有这个问题

**Comment by moyus** [comment]
Fixed in v1.1.1
