### ISSUE TITLE
[bug-report] 进行主题定制样式时报错

### ISSUE THREAD

**Issue by yangshuyi** [didi/mand-mobile#621]
#### Mand Mobile Version
2.5.5            

#### Vue Version
2.5.2       

#### Model / OS & Browser Info
pc       

#### Recurring Steps
在按照https://didi.github.io/mand-mobile/#/zh-CN/docs/theme的介绍进行配置时，配置.babelrc文件报错，提示错误 。

请帮忙看下是什么原因

#### Expectant Behaviors
正常编译

#### Actual Behaviors
webpack报错：
 error  in ./src/main.js

Module build failed: Error: Plugin 2 specified in "c:\\cccis\\proj\\dms-vue-demo\\vue-app\\.babelrc" provided an invalid property of "libraryName"

---

{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime", "import", {"libraryName": "mand-mobile", "libraryDirectory": "components"}]
}

**Comment by xxyan0205** [comment]
mand-mobile 安装的有问题，检查一下 npm ls mand-mobile
