### ISSUE TITLE
[bug-report] 图片浏览器，切换不同的数据，展示有缓存的样子。

### ISSUE THREAD

**Issue by Jiyr0119** [didi/mand-mobile#623]
#### Mand Mobile Version
2.5.3            

#### Vue Version
2.5.16       

#### Model / OS & Browser Info
苹果x       

#### Recurring Steps
一个列表循环，item的每一项里面又一个图片循环展示，点击图片 使用图片浏览器，并把展示对应的数组的数据。比如一个数组里面有五张图片，这个时候是没有问题的，点击图片关闭。然后点下一项的时候是一张图片，但是展示的时候上一个数组里面的最后一张。经过调试数组已经变了，而且看组件里面的数据也已经是当前的那一张的数据，但是展示的是上一个数组里面的最后一张图片。

#### Expectant Behaviors
期待是点击不同的图片列表，更换对应的数据。

#### Actual Behaviors
实际上是点了多张列表之后的图片，点击单张，数据有缓存或者页面有缓存的样子。

---
      this.imgs = []
      this.imgs = this.goodsList[pIndex].viewim;  // 每次之前都清空数组  然后这个viewim 也是一个数组直接赋值的。
      this.viewerIndex = index;
      this.isViewerShow = true;

**Comment by supergaojian** [comment]
请您贴出完整可复现的代码，谢谢

**Comment by Jiyr0119** [comment]
效率好高，点赞。跑起来就可以复现   https://github.com/Jiyr0119/floatButton/tree/master/my-project

**Comment by zouhangwithsweet** [comment]
工程有问题，无法启动和复现，请确认工程在本地能启动与复现。
