### ISSUE TITLE
使用数据键盘的事件击穿

### ISSUE THREAD

**Issue by Dloong** [didi/mand-mobile#625]
步骤：使用数字键盘，chrome://inspect/#devices调试，快速输入数字。
效果：会出现多个相同数字，同时，控制台报错[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
疑问：关闭usb调试，击穿效果消失

**Comment by xxyan0205** [comment]
什么版本，什么手机？是否引入了fastclick

**Comment by Dloong** [comment]
版本：2.5.1。手机型号：各种型号连上调试工具都会出现。
fastclick又引入，但依然复现

Shawn Xu <notifications@github.com> 于2019年12月9日周一 下午2:45写道：

**Comment by xxyan0205** [comment]
> fastclick又引入，但依然复现

因为键盘绑定的是touchstart，所以引入fastclick会导致上述报警，可以不再使用fastclick。至于出现重复数字，不知击穿效果具体指的是什么？如果有必要可以录屏看下效果，另外可以使用下https://didi.github.io/mand-mobile/examples/#/number-keyboard 是否可复现同样问题

**Comment by Dloong** [comment]
1、引入fastclik的目的是为了解决警告问题。但是引入以后并没有解决这个问题，我看到mandmobile已经引入fastclick，所以把我自己本地的fastclick库移除了。
2、因为一些特殊的需求，我用到两种数字键盘。这两种都会出现上述问题。
NO.1 https://didi.github.io/mand-mobile/#/zh-CN/docs/components/form/number-keyboard
NO.2 https://didi.github.io/mand-mobile/#/zh-CN/docs/components/form/input-item   金融键盘
3、录屏如下：
快速点击会出现重复，并报错。
以上情况只有在这种调试模式下会出现。
[screen-recording.mov.zip](https://github.com/didi/mand-mobile/files/3943290/screen-recording.mov.zip)

**Comment by xxyan0205** [comment]
> 我看到mandmobile已经引入fastclick

mand-mobile内部没有引入fastclick。

重复的问题可能是模拟器触发事件问题导致，设置中禁用滚轮模拟试一下

![image](https://user-images.githubusercontent.com/8409100/70502741-9e009180-1b5c-11ea-9f76-813bcaa83c2b.png)

**Comment by Dloong** [comment]
[image: image.png]依旧会出现，而且真机调试也会出现这个问题

Shawn Xu <notifications@github.com> 于2019年12月10日周二 下午2:52写道：

**Comment by xxyan0205** [comment]
使用安卓模拟器 在chrome浏览器中，使用官方示例（2.5.6）没有复现上述问题https://didi.github.io/mand-mobile/examples/#/number-keyboard

**Comment by Dloong** [comment]
[image: image.png]
使用官方事例代码，依然出现上述问题。
vue+cordova

Shawn Xu <notifications@github.com> 于2019年12月10日周二 下午3:18写道：

**Comment by xxyan0205** [comment]
因为无法复现所以不能验证是否是内部代码问题，如果有时间可以帮忙调试下上述问题是否与按钮绑定事件有关，如果定位到问题欢迎提PR，感谢
https://github.com/didi/mand-mobile/blob/master/components/number-keyboard/key.vue
