### ISSUE TITLE
[bug-report] Tabs 在 iPhone 切换时出现浮动内容重影

### ISSUE THREAD

**Issue by LLwanran** [didi/mand-mobile#627]
#### Mand Mobile Version
2.5.6            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
iPhone 11       

#### Recurring Steps
iPhone 11、iPhone X切换时均出现

#### Expectant Behaviors
不要有重影出现

#### Actual Behaviors
有重影出现

---
实测在&-leave-active样式类添加transform: translateZ(0)或will-change: transform均可修复

**Comment by zouhangwithsweet** [comment]
手机系统是什么版本呢？

**Comment by LLwanran** [comment]
系统均为iOS13.0
类似情形：https://www.zhangxinxu.com/wordpress/2015/01/chrome-absolute-display-visibility-render-bug

**Comment by zouhangwithsweet** [comment]
我自己用了 iPhone11 和 iPhone 11 pro 在测试官网 demo 尚未发现问题；
[tabs.MP4.zip](https://github.com/didi/mand-mobile/files/3997464/tabs.MP4.zip)

可以提供提个视频嘛

**Comment by LLwanran** [comment]
> 我自己用了 iPhone11 和 iPhone 11 pro 在测试官网 demo 尚未发现问题；
> [tabs.MP4.zip](https://github.com/didi/mand-mobile/files/3997464/tabs.MP4.zip)
> 
> 可以提供提个视频嘛

![image](https://user-images.githubusercontent.com/1793935/71403428-b0a1bd00-266a-11ea-94ac-6d7fea3886c2.png)
如图，切换时一直出现重影，添加上述样式即正常。

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/71403691-7258cd80-266b-11ea-80ae-478a1a0eca70.png)
是指和这个部分吗？

**Comment by LLwanran** [comment]
是的，这里实际并无内容
