### ISSUE TITLE
NoticeBar 内容过短时，开启scrollable仍然触发了滚动

### ISSUE THREAD

**Issue by LLwanran** [didi/mand-mobile#628]
Mand Mobile Version
2.4.1

Vue Version
2.6.1

Model / OS & Browser Info
iPhone 11 iOS13.0

Recurring Steps
Slots default仅设置很短几个字

Expectant Behaviors
内容未撑开时不要滚动

Actual Behaviors
开启scrollable，无论文本长短都触发了滚动

**Comment by zouhangwithsweet** [comment]
我在本地复现时，只有一种情况下才出现这个问题；就是这个 slot 的内容是动态变化；请问你的使用场景是这样的吗？

**Comment by LLwanran** [comment]
差不多是这样，实际需求确实是需要实时变更slot内容。
我这边测试结果是只要开启scrollable，哪怕就一个汉字，也会滚动。
我尝试将
`this.overflow = content.scrollWidth > wrap.clientWidth`
修改为
`
this.overflow = content.scrollWidth > Math.ceil(wrap.getBoundingClientRect().width);
`
之后结果正常

**Comment by zouhangwithsweet** [comment]
先升级一下 mand-mobile 版本

**Comment by LLwanran** [comment]
已升级最新V2.5.6，仍然是一样，看源码好像那处逻辑对比V2.4.1并无改动

**Comment by zouhangwithsweet** [comment]
本地仍然无法复现，但是修复了`slot`在动态变化下，宽度不正确的问题
