### ISSUE TITLE
[bug-report] InputItem 唤起键盘后页面上滑，导致body响应区域错位

### ISSUE THREAD

**Issue by LLwanran** [didi/mand-mobile#629]
#### Mand Mobile Version
2.4.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
iPhone 11 iOS13.0       

#### Recurring Steps
键盘弹起页面上滑，键盘收起页面不会回到原位置

#### Expectant Behaviors
期望InputItem组件能主动处理此bug，虽然自行解决也是一种方案，但仍希望组件库解决更佳

#### Actual Behaviors
1、键盘弹起页面上滑，键盘收起页面不会回到原位置
2、输入内容后确认，键盘不会收起

**Comment by xxyan0205** [comment]
请提供复现问题的示例链接

**Comment by LLwanran** [comment]
> 请提供复现问题的示例链接

浏览器没法复现，真机才有此bug，iOS12+

**Comment by xxyan0205** [comment]
> > 请提供复现问题的示例链接
> 
> 浏览器没法复现，真机才有此bug，iOS12+

什么浏览器？

**Comment by LLwanran** [comment]
iPhone 11默认Safari
bug类似情形：https://developers.weixin.qq.com/community/develop/doc/00044ae90742f8c82fb78fcae56800

**Comment by xxyan0205** [comment]
类似的解决方案直接加到单个InputItem可能会出现一些负面影响，因为InputItem的使用方式和场景有多种，比如简单粗暴的blur的时候scrollTo顶部可能会导致用户失去原来的停留位置。

**Comment by LLwanran** [comment]
> 类似的解决方案直接加到单个InputItem可能会出现一些负面影响，因为InputItem的使用方式和场景有多种，比如简单粗暴的blur的时候scrollTo顶部可能会导致用户失去原来的停留位置从而对后续的操作产生影响。

明白，多谢！
此问题确实可以后续继续观察，使用者自行fix暂时也不麻烦。
