### ISSUE TITLE
Selector 组件建议增加点击蒙层关闭

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#64]
> mand-mobile version/项目版本
1.1.0

**Comment by zlab** [comment]
有蒙层的组件，都应该支持点蒙层关闭这个选项吧

**Comment by xxyan0205** [comment]
如selector这类组件因存在`确认选中`和`撤销选中`这种交互方式，但点击蒙层关闭这个动作因为无法区分是“确认”或“取消”，故将蒙层关闭禁止需用户主动触发某种指定动作。

**Comment by shoyuf** [comment]
点击灰色蒙层应该是默认取消的交互吧，不然的话整个组件的交互很不统一，另外 ActionSheet 和 Selector 的功能是否重合度太高了？

**Comment by xxyan0205** [comment]
后面迭代中会把`默认取消`加上。
ActionSheet 和 Selector 本来从功能上区分是前者处理动作，后者处理数据选择，但目前ActionSheet的api设计的不太适当，导致两者重复度，后期可能会提供单例形式。
