### ISSUE TITLE
关于imageReader后置摄像头的问题

### ISSUE THREAD

**Issue by yujianquan** [didi/mand-mobile#640]
imageReader在华为荣耀magic2手机上调用后置摄像头取图片会出现报错102的情况，请问一下这个状况怎么解决，谢谢

**Comment by supergaojian** [comment]
您好，请确认：

1. 所有华为荣耀magic2都是这样么？
2. 是否稳定复现？
3. 其他手机是否存在这样的情况？
4. 是否可以提供原图片

谢谢

**Comment by yujianquan** [comment]
不只是magic2，还有meta30也是这个问题，稳定复现的，其他手机暂时没看到这个问题
这个是magic2的报错
![645987db715ec34f4e87811a65de205](https://user-images.githubusercontent.com/28898486/72489130-13433e80-384e-11ea-83bf-3a7a490b8247.jpg)

**Comment by yujianquan** [comment]
![4412a85e41abbbc011982af50a50a46](https://user-images.githubusercontent.com/28898486/72489158-3241d080-384e-11ea-8317-9e045357d009.jpg)
这个是meta30报的错

**Comment by yujianquan** [comment]
emmmm不太明白您说的稳定复现的图片具体指的是什么，效果就是我上面给您发的，只有华为的这两部手机调起后置摄像头然后系统返回图片的时候出现了这个报错，代码就是完完全全按照你们官方文档来的，大概就是适配的问题
![image](https://user-images.githubusercontent.com/28898486/72489789-2f47df80-3850-11ea-928c-1d3bf0159436.png)
![image](https://user-images.githubusercontent.com/28898486/72489807-42f34600-3850-11ea-9107-779db6202d2f.png)

**Comment by msdlisper** [comment]
@yujianquan 我刚刚用 华为meta30 试了下, 没有复现你说的这个问题, 我是直接在手机自带的浏览器里通过扫一扫dome二维码进行测试的, 你也可以扫一下试试
![image](https://user-images.githubusercontent.com/8390787/72505815-a34bad00-387b-11ea-9721-71c4c320b63a.png)
所以我怀疑, 你的这个问题大概率是在特定的宿主环境里(比如某个APP里的浏览器打开?)复现的, 你再看看呢

**Comment by yujianquan** [comment]
@msdlisper 确实是在app里面跑的项目，直接在浏览器中打开是不会出现问题的，所以这个问题是一直都存在的对吗

**Comment by msdlisper** [comment]
@yujianquan 对, 你这个问题我们团队也是遇到了, 因为我们没法保证你app里浏览器(端内)环境是什么样的情况, 想拉起摄像头这样的功能, 可以端内做了限制. 
你可以问下你们端上的同学:
1. 排查是否对端内环境做了限制, 是否能放开
2. 是否有暴露这样的bridge, 如果是可以通过调用bridge的方式来实现拍摄功能

**Comment by yujianquan** [comment]
@msdlisper 好的，谢谢，麻烦你们了
