### ISSUE TITLE
是否可以在 popup 组件中增加弹出时锁定底层页面滚动的属性呀

### ISSUE THREAD

**Issue by wangjun521** [didi/mand-mobile#652]
感觉这是一个挺正常的场景呢

**Comment by xxyan0205** [comment]
如果弹层内容不需要滚动，可以直接增加`touchmove.prevent`，如果需要滚动内部可以嵌套`ScrollView`

**Comment by wangjun521** [comment]
我意思是在外部常规滚动的情况下 页面内有个弹层 弹层跳出的时候 后面正常滚动的页面如果锁定的话 用户体验会更好有些吧

**Comment by wangjun521** [comment]
我并不是说弹层 而是弹层下面的常规页面

**Comment by xxyan0205** [comment]
上述方法就是用于解决弹层导致的滚动穿透问题

**Comment by wangjun521** [comment]
在弹层内部已经阻止滚动并且弹层不是全屏的情况下  用户滚动上半层的遮罩的时候 底层页面会滚动的

**Comment by 10822123** [comment]
你好，请问还会更新吗

**Comment by xxyan0205** [comment]
> 你好，请问还会更新吗

2.x目前只做小的更新，3.0正在筹划中
