### ISSUE TITLE
[bug-report] 如果开国外vpn访问 iconfont 会加载不出来

### ISSUE THREAD

**Issue by GaoXiaoLiang** [didi/mand-mobile#654]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.6.10       

#### Model / OS & Browser Info
iphone 11       

#### Recurring Steps
打开国外vpn访问 iconfont 会加载不出来

#### Expectant Behaviors
打开vpn或者国外网访问 也能正常加载

#### Actual Behaviors
iconfont 会远程加载，打开国外vpn加载不出来

**Comment by supergaojian** [comment]
您好，因为icon使用的是远程加载的国内cdn，所以开国外的vpn会加载失效。
推荐您可以下载icon字体至本地，通过mand-mobile的主题定制将字体库切换至本地引用即可
