### ISSUE TITLE
ios弹窗嵌套弹窗

### ISSUE THREAD

**Issue by xujinjie** [didi/mand-mobile#656]
页面布局大概是上面弹窗一个筛选的弹窗，弹窗里有可以选择时间的筛选，日历选择是一个在下面弹出的弹窗，在安卓和pc上是没什么问题的。
![image](https://user-images.githubusercontent.com/28759391/75947979-19b07700-5edd-11ea-8bfc-de39dbfc7211.png)
安卓和pc上正常效果。
![image](https://user-images.githubusercontent.com/28759391/75948026-3ea4ea00-5edd-11ea-98cf-69a3f587c957.png)
ios上的效果。
日历选择是嵌套在最早日期里面的。
请问有什么结局方案吗？

**Comment by xxyan0205** [comment]
没看明白，可以去官方交流群里，让大家帮忙看下问题
