### ISSUE TITLE
组件全局引入报错

### ISSUE THREAD

**Issue by hui-fly** [didi/mand-mobile#659]
#### Mand Mobile Version
2.5.9            

#### Vue Version
2.5.22       

#### Model / OS & Browser Info
与机型无关       

#### Recurring Steps
全局引入 mandMobile</br>
```
import mandMobile from 'mand-mobile'
import 'mand-mobile/lib/mand-mobile.css'

Vue.use(mandMobile)
```

#### Expectant Behaviors
引入成功，没有报错

#### Actual Behaviors
全局引入mandMobile提示 ReferenceError: mandMobile is not defined

**Comment by xxyan0205** [comment]
如果想全局引用，把babel中的按需加载配置**删掉** https://didi.github.io/mand-mobile/#/zh-CN/docs/started?anchor=%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD%28%E6%8E%A8%E8%8D%90%29
