### ISSUE TITLE
Dialog 包含 inputitem组件，IOS无法输入

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#66]
> mand-mobile version/项目版本
1.1.1

> os version & browser version/操作系统版本&浏览器版本
ios 10.3.3

> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
yarn 1.6.0

> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)
``` html
<md-dialog
      title="窗口标题"
      :closable="true"
      v-model="basicDialog.open"
      :btns="basicDialog.btns"
    >
      <md-field>
      <md-input-item
        ref="input0"
        title="普通文本"
        placeholder="普通文本"
        :maxlength="5"
      ></md-input-item>
</md-field>
    </md-dialog>
```

> recurring steps/复现步骤

> expectant behaviors/期待行为

> actual behaviors/实际行为
安卓没有问题，ios很难点到输入框，没法弹出系统键盘

**Comment by xxyan0205** [comment]
微信和Safari中没有复现这个问题，先排除下是否是ios的[点击问题](https://didi.github.io/mand-mobile/#/docs/started?anchor=%E4%BD%BF%E7%94%A8%E5%89%8D%E5%87%86%E5%A4%87)

**Comment by zlab** [comment]
这个框架也有这个问题ios10.3.3

https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN

![image](https://user-images.githubusercontent.com/2288630/39680813-817aa42e-51d7-11e8-8f27-1edaa11b67d4.png)

**Comment by zlab** [comment]
不是点击问题，我加了fastclick的

**Comment by xxyan0205** [comment]
ios 10.3.3 safari 中没有复现这个问题。
![597833930_1667597641_img_2384](https://user-images.githubusercontent.com/8409100/39684013-94d7694e-51eb-11e8-9c7e-65114c0f9d5c.png)

**Comment by zlab** [comment]
微信里面

**Comment by xxyan0205** [comment]
微信也可以
![wechatimg1](https://user-images.githubusercontent.com/8409100/39686125-d3478c1e-51f9-11e8-8c5a-2775127d9076.jpeg)
点击不行的话你试一下长按呢
