### ISSUE TITLE
无网环境下控件图标加载不出来？。

### ISSUE THREAD

**Issue by wupengfei-mango** [didi/mand-mobile#660]
无网环境下控件图标加载不出来？如arrow箭头，是否有解决方案？

**Comment by xxyan0205** [comment]
内置的样式是加载远程字体，可参考文档改成[加载本地字体](https://didi.github.io/mand-mobile/#/zh-CN/docs/components/basic/icon?anchor=%E5%BC%95%E5%85%A5%E6%9C%AC%E5%9C%B0%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6)

**Comment by wupengfei-mango** [comment]
> 内置的样式是加载远程字体，可参考文档改成[加载本地字体](https://didi.github.io/mand-mobile/#/zh-CN/docs/components/basic/icon?anchor=%E5%BC%95%E5%85%A5%E6%9C%AC%E5%9C%B0%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6)

亲测有效，多谢~~
