### ISSUE TITLE
[bug-report] Selector 组件，单选模式，设置default-value后，confirm事件在未选中前无效

### ISSUE THREAD

**Issue by chunghaochow** [didi/mand-mobile#661]
#### Mand Mobile Version
2.5.9            

#### Vue Version
2.6.11       

#### Model / OS & Browser Info
iPhone8       

#### Recurring Links
https://codesandbox.io/s/mand-mobile-quick-start-mgmk9?fontsize=14&hidenavigation=1&theme=dark

#### Recurring Steps
点击按钮，不做选择操作，直接点击确认按钮。选择器没有反应。

#### Expectant Behaviors
触发confirm事件，隐藏选择器。

#### Actual Behaviors
选择器没有触发confirm事件。

---
selector组件$_onSelectorConfirm方法没有对tmpActiveIndex === -1 时做处理，我想应该是这儿的问题吧^_^

**Comment by zouhangwithsweet** [comment]
这其实是个统一逻辑，在用户没选择之前， `confirm`  是一直不会被触发的。
