### ISSUE TITLE
[bug-report] 文字链接按钮文字显示不全

### ISSUE THREAD

**Issue by xjchengo** [didi/mand-mobile#663]
#### Mand Mobile Version
2.5.9            

#### Vue Version
2.6.11       

#### Model / OS & Browser Info
华为P30 Pro/Android/微信浏览器       

#### Recurring Steps
安卓微信浏览器内打开DEMO,创建一个无ICON的文字链接按钮

#### Expectant Behaviors
按钮文字完全显示

#### Actual Behaviors
按钮文字未完全显示

---
`.md-button-inner`类设置了`overflow: hidden;`，`.md-button.link`设置了`line-height: 1;`，文字实际高度受字体影响要大于font-size，所以文字未完全显示

![image](https://user-images.githubusercontent.com/4819996/80087429-a5fe2280-858d-11ea-9576-068e36eefd4d.png)
去看看三个字上方有部分未显示

**Comment by zouhangwithsweet** [comment]
iphone / s10 暂无复现。寻找机器中...
