### ISSUE TITLE
自定义svg图标

### ISSUE THREAD

**Issue by ming2882** [didi/mand-mobile#669]
vue cli3 按写的要求做了,把const path = require('path')

module.exports = {
  module: {
    loaders: [
      {
        test: /\.svg$/i,
        loader: 'svg-sprite-loader',
        include: [
          // 将某个路径下所有svg交给 svg-sprite-loader 插件处理
          path.resolve(__dirname, 'src/my-project-svg-folder')
        ],
      }
    ]
  }
}加到vue.config.js会报错的。没有module个
能给个具体的的方法吗？

**Comment by xxyan0205** [comment]
https://github.com/mand-mobile/vue-cli3-example/tree/custom-theme
