### ISSUE TITLE
Picker 城市联动demo无法默认选中

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#67]
> mand-mobile version/项目版本
1.1.1

### 官网效果
![image](https://user-images.githubusercontent.com/2288630/39704156-10d3922e-523d-11e8-9175-cc38c3c40e80.png)

### 我的效果
![image](https://user-images.githubusercontent.com/2288630/39704172-1d243bb4-523d-11e8-8942-f11d23ab2b5e.png)

**Comment by xxyan0205** [comment]
请提供一些调试或者报错等能够帮助排除问题的信息。

**Comment by zlab** [comment]
找到原因了，奇怪的原因。
``` js
data() {
    return {
      msg: "Welcome to Your Vue.js App",
      show: true,
      pickerData: district,
      pickerDefaultIndex: [3, 2, 1],
      pickerValue: ""
    };
  },
  mounted() {
    // 为什么必须在mount之后设置数据源，直接在data里已经给了数据源，没有用？？？
    // this.pickerData = district;
  },
```

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jzxx5k9w8w)

**Comment by moyus** [comment]
Fixed in `v1.2.0`
