### ISSUE TITLE
[bug-report] 定制主题并按需引入组件和使用路由懒加载后打包部署，组件样式重复载入

### ISSUE THREAD

**Issue by RobinBoom27** [didi/mand-mobile#673]
#### Mand Mobile Version
2.5.1            

#### Vue Version
2.6.11       

#### Model / OS & Browser Info
所有       

#### Node Version, Package Management Tool

node 12.11.1/npm 6.11.3

#### Recurring Links
https://github.com/RobinBoom27/test

#### Recurring Steps
打包部署后，访问/home页面再访问/about后，回到/home页面button样式被覆盖

#### Expectant Behaviors
在不同页面引入同一组件，不会重复载入该组件样式

#### Actual Behaviors
在不同页面引入同一组件，导致该组件样式重复载入并覆盖了<style lang="stylus" scoped>内的样式

---
Mand Mobile Version2.5.10也有上诉问题，望大佬指点下😣
将vue.config.js中 css.extract设为false 可解决
该例子中把App.vue引入的ActivityIndicator组件去掉或者路由不使用懒加载就没有该问题

**Comment by xxyan0205** [comment]
跟定制主题没有关系，是选择器优先级问题，覆盖`width`应该使用 `.md-button.block`

**Comment by RobinBoom27** [comment]
可是为什么.md-button.block这个样式会被重复引入两次

**Comment by RobinBoom27** [comment]
请看下这两张图片

第一次进入首页https://github.com/RobinBoom27/test/blob/master/src/assets/img/WechatIMG56133.png
然后进入About后再返回首页https://github.com/RobinBoom27/test/blob/master/src/assets/img/WechatIMG56141.png

**Comment by xxyan0205** [comment]
> 可是为什么.md-button.block这个样式会被重复引入两次

因为了 button的样式被提取到各页面的chunk css中，没有被提取到vendor中。

**Comment by RobinBoom27** [comment]
![image](https://user-images.githubusercontent.com/31871202/81635339-99aa0e80-9443-11ea-9b23-991011920594.png)
感天动地  大佬就大佬  一语道破

我还有一个问题想请教下，公司另一个项目也是采用的mand-mobile，但是也没有提取到vendor中，可是并没有这个问题🤯

**Comment by xxyan0205** [comment]
> 我还有一个问题想请教下，公司另一个项目也是采用的mand-mobile，但是也没有提取到vendor中，可是并没有这个问题🤯

本质是选择器优先级导致样式被覆盖，但覆盖的原因是css被多次抽到了不同的chunk，所以很巧合...

**Comment by RobinBoom27** [comment]
好滴  谢谢
![image](https://user-images.githubusercontent.com/31871202/81635823-d32f4980-9444-11ea-9f65-bb2fbf860e98.png)
