### ISSUE TITLE
TabBar各个标签，有没有阻止change事件的方法？本意是，让有些标签，禁止点击选中

### ISSUE THREAD

**Issue by zyw0605688** [didi/mand-mobile#676]
TabBar组件，使用change事件，更改选中的标签。
我想根据标签的状态，判断是不是可以被点击选中
目前的change事件，好像无法阻止被点击选中。
有没有什么好的办法

**Comment by xxyan0205** [comment]
items中元素设置属性disabled为true

**Comment by zyw0605688** [comment]
> items中元素设置属性disabled为true

解决了，的确可以，感谢！
