### ISSUE TITLE
mand-mobile用什么好的包来做表单验证吗？

### ISSUE THREAD

**Issue by zhou0818** [didi/mand-mobile#68]
> mand-mobile version/项目版本
1.1.0

> os version & browser version/操作系统版本&浏览器版本
win10&chrome

> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
cnpm

> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)

> recurring steps/复现步骤

> expectant behaviors/期待行为

表单验证

> actual behaviors/实际行为

请问 mand-mobile 做表单验证时有什么好的工具推荐吗？我使用 vee-validate 做表单验证，除了 required 之外的规则，只要是失去焦点就会触发验证失败，例如 numeric 规则，我输入的全数字，但是失去焦点时就验证失败

**Comment by xxyan0205** [comment]
vee-validate 默认绑定了一些事件（如blur）与input-item的触发的事件冲突，导致每次事件触发（如blur）没有传入表单值而出发报错，所以需要设置vee-validate监听的事件， 可以参考下面的文档和示例

https://baianat.github.io/vee-validate/guide/events.html

[![Edit Mand Mobile with VeeValidate](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5z344nk79x)
