### ISSUE TITLE
toast组件是基于popup开发的，为什么没有transition选项呢

### ISSUE THREAD

**Issue by hemengke1997** [didi/mand-mobile#682]
`<md-toast ref="toast" :duration="5000" position="top" transition="fade-bounce">
      <div >
      </div>
    </md-toast>`
这样写并没有transition的效果

**Comment by hemengke1997** [comment]
<md-toast ref="toast" :duration="5000" position="top" transition="fade-bounce">
      
    </md-toast>

**Comment by xxyan0205** [comment]
因为在规范中，toast是定制化的具有特定的样式和交互的组件，跟dialog，popup有不同使用场景。如果有特殊需求可以考虑直接使用popup。
