### ISSUE TITLE
DropMenu 组件下拉选项div无法滑动

### ISSUE THREAD

**Issue by stonemakers** [didi/mand-mobile#685]
DropMenu 组件下拉选项div自定义高度，无法滑动，如下图
![picture](http://chuantu.xyz/t6/739/1594022328x1700340427.png)

**Comment by xxyan0205** [comment]
参考 https://didi.github.io/mand-mobile/examples/#/drop-menu 示例二，或提供复现问题的示例链接

**Comment by stonemakers** [comment]
> 参考 https://didi.github.io/mand-mobile/examples/#/drop-menu 示例二，或提供复现问题的示例链接

示例二是因为限制了最外层div的高度，是可以滚动的
我的页面是无限下滑加载的页面，所以是自适应高度，在这种情况下无法滚动

![pic](http://chuantu.xyz/t6/739/1594023836x1033347913.png)

**Comment by xxyan0205** [comment]
<img src="https://im2.ezgif.com/tmp/ezgif-2-3fe5248a2bac.gif" width="300">

**Comment by stonemakers** [comment]
抱歉，看不到您的回复

**Comment by zouhangwithsweet** [comment]
看下这个
![FullSizeRender-_1_](https://user-images.githubusercontent.com/21095710/86688635-dad03080-c038-11ea-8870-4e96a0281068.gif)

**Comment by stonemakers** [comment]
> 看下这个
> ![FullSizeRender-1](https://user-images.githubusercontent.com/21095710/86688635-dad03080-c038-11ea-8870-4e96a0281068.gif)
这个源码能提供一下么？

**Comment by stonemakers** [comment]
> > 看下这个
> > ![FullSizeRender-1](https://user-images.githubusercontent.com/21095710/86688635-dad03080-c038-11ea-8870-4e96a0281068.gif)
> > 这个源码能提供一下么？

我知道了，你这个是因为限制了外层的最大高度，所以是可以滚动的。如果最外层container的高度是未知的无限下拉的，就无法滚动了

**Comment by zouhangwithsweet** [comment]
未知高度和滚动似乎是相悖的；滚动的原理就是外层的高度固定，内部元素超出其高度

**Comment by zouhangwithsweet** [comment]
可以看下这个文档：[滚动原理](https://better-scroll.github.io/docs/zh-CN/guide/#%E6%BB%9A%E5%8A%A8%E5%8E%9F%E7%90%86)

**Comment by stonemakers** [comment]
> 可以看下这个文档：[滚动原理](https://better-scroll.github.io/docs/zh-CN/guide/#%E6%BB%9A%E5%8A%A8%E5%8E%9F%E7%90%86)

![picture](http://chuantu.xyz/t6/739/1594090509x1033347913.png)

**Comment by zouhangwithsweet** [comment]
提供一个复现链接？

**Comment by stonemakers** [comment]
> 提供一个复现链接？



内网穿透测试链接 会比较慢 你看一下  [点击访问](http://gittest.nat300.top/live/34 )

**Comment by zouhangwithsweet** [comment]
看了一下布局，感觉是布局导致的问题。由于你的一些 css 设置导致下图的代码没有执行。可以考虑重新换个布局
![image](https://user-images.githubusercontent.com/21095710/86726268-fe0cd700-c05c-11ea-92d7-81a180bde8d2.png)

**Comment by stonemakers** [comment]
> 看了一下布局，感觉是布局导致的问题。由于你的一些 css 设置导致下图的代码没有执行。可以考虑重新换个布局
> ![image](https://user-images.githubusercontent.com/21095710/86726268-fe0cd700-c05c-11ea-92d7-81a180bde8d2.png)

你们这个组件设计的时候，布局结构都是fixed，是以浏览器进行定位的。即便在外层套div为relative也无法再次定位。修改起来会比较麻烦。。
