### ISSUE TITLE
Toast.info等系列方法默认duration问题

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#69]
> mand-mobile version/项目版本
1.1.1

**Comment by zlab** [comment]
### 显示1秒足够，更希望默认1秒

> 每次使用toast都要import，为什么不直接放到Vue.prototype

``` js
Vue.prototype.$toast = Object.assign({}, Toast);
    Vue.prototype.$toast.succeed = (content) => {
      Toast.succeed(content, 800);
    };
```

**Comment by xxyan0205** [comment]
目前mand mobile只是作为通用工具，还不是应用级的解决方案，另外还要支持按需加载的能力，所以不太适合做侵入式的操作。类似的全局设定更适合在上层的应用层入口处增加。
