### ISSUE TITLE
希望 Dialog.confirm Dialog.alert 等 能够支持传入 maskClosable 配置

### ISSUE THREAD

**Issue by lonelyWalkor** [didi/mand-mobile#692]
在 Dialog 是 基于 popup 组件封装的  但 popup 组件的 maskClosable 配置项 在  Dialog.confirm Dialog.alert 不被支持，希望能够添加支持此配置项

**Comment by zouhangwithsweet** [comment]
这种情况不是很符合我们的交互规范，如果有这种需求的话。可以自己做一些修改，比如选中 mask，为其绑定事件
