### ISSUE TITLE
[bug-report] DatePicker组件更新minDate/maxDate时,月份、日期列表显示异常

### ISSUE THREAD

**Issue by xiterjia** [didi/mand-mobile#694]
#### Mand Mobile Version
2.5.12            

#### Vue Version
2.6.11       

#### Model / OS & Browser Info
Mac/Mac/Chrome 84.0.4147.125       

#### Node Version, Package Management Tool

node 8.11.0 npm 5.6.0

#### Recurring Links
https://codesandbox.io/embed/gifted-cdn-dibzy

#### Recurring Steps
Bug1：

1、点击出生时间，显示DatePicker，再隐藏DatePicker；

2、年龄可选范围选中`18岁到45岁`，再次点击出生时间。

Bug2：

1、年龄可选范围选中`18岁到45岁`，出生时间选中最小可选值`1975/8/18`(当前时间减45年)，点击确定；

2、年龄可选范围选中`18岁到55岁`，点击出生时间时，显示的是1965年整年的可选日期，最小值限制并没有起作用。

#### Expectant Behaviors
Bug1：

月份列表可选项应该为1-12

日期列表可选项应为对应的选中月份的日期

Bug2：

月份列表可选项应该为当月之后-12

日期列表可选项应该为当日之后的日期

#### Actual Behaviors
Bug1：

月份列表只显示1-8(当前月)

日期列表只显示1-18(当前天)

Bug2：

月份列表与日期列表全部显示

---
目前此问题可以通过 `this.$refs.datePicker.$refs.picker.oldActivedIndexs = null` 来暂时解决。

**Comment by xxyan0205** [comment]
因为最大最小限制变更超出了当前选中日期，所以需要通过动态改变key属性的方法强制重置DatePicker

```html
<md-date-picker
  :min-date="minDate"
  :max-date="maxDate"
  :default-date="currentDate"
  :key="tmpKey"
></md-date-picker>
```

```js
export default {
  data () {
    return {
      minDate: new Date(),
      maxDate: new Date(),
      currentDate: new Date(),
      tmpKey: Date.now()
    }
  },
  methods: {
   //...
   setNewDate(maxDateYear, minDateYear) {
      const maxDate = new Date()
      maxDate.setFullYear(maxDate.getFullYear() - maxDateYear)
      const minDate = new Date()
      minDate.setFullYear(minDate.getFullYear() - minDateYear)
      this.minDate = minDate
      this.maxDate = maxDate
      this.tmpKey = Date.now()
    },
  }
  //...
}
```
