### ISSUE TITLE
文档需要修改了， 全量引入这样才会生效

### ISSUE THREAD

**Issue by JokerLoLgrey** [didi/mand-mobile#695]
按照官网文档配置全量引入，会报mandMobile not defind,只有按照下面的方式配置才会生效
![image](https://user-images.githubusercontent.com/33446705/90712126-e7e96c00-e2d4-11ea-88b3-ea9d30ca63a7.png)

**Comment by xxyan0205** [comment]
全量引入的话 需要把babel中的按需加载配置去掉

**Comment by JokerLoLgrey** [comment]
> 全量引入的话 需要把babel中的按需加载配置去掉

https://github.com/JokerLoLgrey/vueVantMand你看一下嘛，我Babel都没怎么配

**Comment by jingjing09** [comment]
clone -> npm install -> 修改全量引入如下 -> npm run serve 并没有发现报 mandMobile not defind 的问题
![image](https://user-images.githubusercontent.com/19836082/90724802-b29f4700-e2f1-11ea-9386-77850a44bc70.png)

**Comment by JokerLoLgrey** [comment]
> clone -> npm install -> 修改全量引入如下 -> npm run serve 并没有发现报 mandMobile not defind 的问题
> ![image](https://user-images.githubusercontent.com/19836082/90724802-b29f4700-e2f1-11ea-9386-77850a44bc70.png)

我试试， 之前是在家里面测试的， 现在换个公司电脑试试
