### ISSUE TITLE
[bug-report] 官网为什么那么卡

### ISSUE THREAD

**Issue by Messilimeng** [didi/mand-mobile#698]
#### Mand Mobile Version
官网为什么那么卡            

#### Vue Version
官网为什么那么卡       

#### Model / OS & Browser Info
官网为什么那么卡       

#### Recurring Steps
官网为什么那么卡

#### Expectant Behaviors
官网为什么那么卡

#### Actual Behaviors
官网为什么那么卡

**Comment by zouhangwithsweet** [comment]
国内镜像: https://mand-mobile.gitee.io/docs/index.gitee.html#/zh-CN/home
