### ISSUE TITLE
[bug-report] DatePicker放到popup后，年份一半以下时间无法选择

### ISSUE THREAD

**Issue by AAaNEIgeiDEItao** [didi/mand-mobile#704]
#### Mand Mobile Version
2.4.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
imac/osx/chrome85.0.4183.102       

#### Recurring Steps
DatePicker放到popup后，年份一半以下时间无法选择

#### Expectant Behaviors
DatePicker放到popup后，年份可以正常选择

#### Actual Behaviors
DatePicker放到popup后，年份一半以下时间无法选择

**Comment by zouhangwithsweet** [comment]
https://mand-mobile.gitee.io/docs/index.gitee.html#/zh-CN/docs/components/feedback/date-picker
看下最后一个 demo，date-picker 本身就是在 popup 里边，是正常的。可以提供一个在线复现 demo 吗？

**Comment by MissLiu34** [comment]
md-date-picker的is-view属性为true， 放在md-popup中时，无法滚动。

**Comment by MissLiu34** [comment]
`<md-popup v-model="isPopupShow.bottom" position="bottom">
        <md-popup-title-bar
          title="选择日期"
          ok-text="完成"
          cancel-text="取消"
          large-radius
          @confirm="hidePopUp('bottom')"
          @cancel="hidePopUp('bottom')"
        ></md-popup-title-bar>
        <div class="time-popup-content">
          <md-date-picker
            ref="datePicker"
            v-show="isSettingTime === 'start'"
            is-view
            type="custom"
            :custom-types="['yyyy', 'MM', 'dd']"
            :min-date="minDate"
            :max-date="maxDate"
            :default-date="startDateForPicker"
            @change="changeStartTime"
          />
        </div>
      </md-popup>`

**Comment by xxyan0205** [comment]
> md-date-picker的is-view属性为true， 放在md-popup中时，无法滚动。

可以在外层popup第一次`beforeShow`事件触发的时候，对内部嵌套的DatePicker进行一次refresh
`this.$refs.datePicker.picker.refresh()`
