### ISSUE TITLE
<md-input-item type="phone" preview-type="phone">时，光标位置错误

### ISSUE THREAD

**Issue by suxue1994** [didi/mand-mobile#710]
1. 代码样例
`<md-input-item type="phone" preview-type="phone"></md-input-item>`
2. 描述：如上所示，当type为phone时，在粘贴手机号码的时候光标会自动往前跳2位

**Comment by xxyan0205** [comment]
请使用 [mand-mobile-issue-helper](https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile) 提交issue，并提供相关复现问题信息，谢谢
