### ISSUE TITLE
popup类弹出插件在iphonex以上兼容如何去掉

### ISSUE THREAD

**Issue by zhaohang1993** [didi/mand-mobile#712]
在iphonex以上机型会向上距离底部留出来一点空隙，请问如何去掉兼容呢。。。

**Comment by xxyan0205** [comment]
请使用 [mand-mobile-issue-helper](https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile) 提交issue，并提供相关复现问题信息，谢谢

**Comment by zhaohang1993** [comment]
mand-mobile在iphone-x系列以上对下面小黑条做了兼容处理 - popup弹出类组件会和下面有一定间隙，如何去掉兼容达到没有间隙呢 。。。
| |
111
|
|
zhaohang_pic@163.com
|
签名由网易邮箱大师定制


在2020年10月30日 14:53，Shawn Xu<notifications@github.com> 写道：

请使用 mand-mobile-issue-helper 提交issue，并提供相关复现问题信息，谢谢
