### ISSUE TITLE
[bug-report] mand-mobild对iphonex下面小黑条做了兼容处理如何去掉兼容处理

### ISSUE THREAD

**Issue by zhaohang1993** [didi/mand-mobile#713]
#### Mand Mobile Version
best new             

#### Vue Version
best new        

#### Model / OS & Browser Info
iphonex       

#### Node Version, Package Management Tool

best new

#### Recurring Steps
mand-mobild对iphonex下面小黑条做了兼容处理，popup类组件会在下面多出来一条空隙。。

#### Expectant Behaviors
如何去掉兼容，不留空隙。

#### Actual Behaviors
如何去掉兼容，不留空隙。

---
如何去掉兼容，不留空隙。

**Comment by xxyan0205** [comment]
哪个组件库版本？哪个组件？

如果提到的空隙是指的安全区的话吗，Popup组件本身没有加padding，基于Popup的组件中Selector和NumberKeyboard有背景色覆盖

**Comment by zhaohang1993** [comment]
已解决
