### ISSUE TITLE
picker组件当cols属性大于1的时候refresh方法只能重置第一列的数据

### ISSUE THREAD

**Issue by zhaohang1993** [didi/mand-mobile#715]
<a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">picker组件当cols属性大于1的时候refresh方法只能重置第一列的数据</a>

**Comment by zouhangwithsweet** [comment]
来个复现demo吧

**Comment by zhaohang1993** [comment]
直接给您链接可以吗

**Comment by zouhangwithsweet** [comment]
https://codesandbox.io/ 可以用这个搞一个 demo
