### ISSUE TITLE
[bug-report]  列表页面滑动后 点击某列  跳转到详情后返回原页面初始位置 该如何实现

### ISSUE THREAD

**Issue by Messilimeng** [didi/mand-mobile#717]
#### Mand Mobile Version
2.4.1            

#### Vue Version
2.6.1       

#### Model / OS & Browser Info
微信浏览器 iPhone android       

#### Recurring Steps
类似于头条新闻 滑动列表 点击查看详情后  在回退到原来阅读的位置

#### Expectant Behaviors
回退到原来阅读

#### Actual Behaviors
页面复原了回到初始页面了

**Comment by PHenryy** [comment]
不想让组件销毁用 keep-alive
