### ISSUE TITLE
请问下有上传附件的组件吗(除了图片)?

### ISSUE THREAD

**Issue by chenny** [didi/mand-mobile#719]
有些需求需要上传附件,但是好像没有找到.
The issue which is not created via <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> will be closed immediately.

---

注意：不是用 <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile">Mand Mobile Issue Helper</a> 创建的 issue 会被立即关闭。

**Comment by xxyan0205** [comment]
没有。
