### ISSUE TITLE
vuecli2.0 官方示例模板中 Toast 组件引入会报错，IOS11以下均不可用

### ISSUE THREAD

**Issue by stonemakers** [didi/mand-mobile#73]
vuecli2.0 官方示例模板中 Toast 组件引入会报错，IOS11以下均不可用

**Comment by stonemakers** [comment]
目前找到一个解决办法  不能用 import { Toast } from 'mand-mobile'  必须用 import Toast from 'mand-mobile/lib/Toast' 的方式引入

**Comment by LetHergo** [comment]
@xxyan0205

**Comment by moyus** [comment]
@stonemakers 已修复，请重新通过模板创建项目

**Comment by stonemakers** [comment]
@moyus 能否告知改动的地方，我的项目已经写得很大了，重新创建比较麻烦。 谢谢

**Comment by moyus** [comment]
@stonemakers https://github.com/mand-mobile/mand-mobile-template/commit/b3d83948fe7e70272495d283db5a2e3996918a84
