### ISSUE TITLE
2.5.18 image-reader 图片有一定几率出现重叠

### ISSUE THREAD

**Issue by faller** [didi/mand-mobile#740]
2.5.18会出现重叠，2.5.17会出现y轴压缩，2.5.9是OK的
<img width="596" alt="截屏2021-04-22 上午9 58 26" src="https://user-images.githubusercontent.com/3031252/115644860-d8ce2880-a351-11eb-99d2-0e4ae35ab79b.png">
<img width="679" alt="截屏2021-04-22 上午9 58 49" src="https://user-images.githubusercontent.com/3031252/115644861-d8ce2880-a351-11eb-960d-a4c3d5b73b41.png">
<img width="649" alt="截屏2021-04-22 上午9 59 00" src="https://user-images.githubusercontent.com/3031252/115644865-d9ff5580-a351-11eb-8984-d413ab613401.png">
<img width="787" alt="截屏2021-04-22 上午10 05 07" src="https://user-images.githubusercontent.com/3031252/115645071-4a0ddb80-a352-11eb-85fc-3114e909579f.png">

**Comment by zouhangwithsweet** [comment]
先降级版本吧，这个问题有点复杂了

**Comment by faller** [comment]
> 先降级版本吧，这个问题有点复杂了

请问一下，哪一个版本的image-reader比较稳定？

**Comment by zouhangwithsweet** [comment]
2.5.15

**Comment by faller** [comment]
> 2.5.15

好的，谢谢
