### ISSUE TITLE
使用弹出层出现报错

### ISSUE THREAD

**Issue by lzcnice** [didi/mand-mobile#742]
项目代码
[mand-test.zip](https://github.com/didi/mand-mobile/files/6383506/mand-test.zip)
项目以springboot形式运行，启动类为MandTestApplication
启动后访问地址为http://127.0.0.1:9997/mandTest/index
问题如下：
1.触发弹出层报错
![弹出层弹出](https://user-images.githubusercontent.com/83273033/116221167-f2bba100-a77f-11eb-9841-2c7cc0820616.png)
2.弹出层关闭时
![弹出层关闭](https://user-images.githubusercontent.com/83273033/116221169-f3543780-a77f-11eb-8259-51ad2b263aa9.png)

**Comment by xxyan0205** [comment]
如果使用组件源码 需要进行编译配置，内部有环境变量`process.env.MAND_ENV`。参考 https://github.com/didi/mand-mobile/blob/master/build/webpack/webpack.dev.conf.js#L51

**Comment by lzcnice** [comment]
> 如果使用组件源码需要进行编译配置，内部有环境变量`process.env.MAND_ENV`。参考https://github.com/didi/mand-mobile/blob/master/build/webpack/webpack.dev.conf.js#L51

![image](https://user-images.githubusercontent.com/83273033/117627112-67dc9c80-b1aa-11eb-8d5a-525a8ea496e8.png)
前辈，项目中使用cdn引入mand-mobile，和你说的配置conf结合不起来呀
