### ISSUE TITLE
DatePicker 默认时间不在最小时间和最大时间的范围内，取不到值

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#75]
> mand-mobile version/项目版本
1.2.2
```
参数
minDate: 2000-08-08
maxDate: 2018-08-08
defaultDate:  1990-08-08
```

此时由于1990小于2000，选择器会显示最小的年，即2000-08-08，但是取值的时候
`this.$refs.datePicker.getFormatDate('yyyy-MM-dd');`拿到的确是'yyyy-08-08'

**Comment by xxyan0205** [comment]
原来是将这种情况当异常情况处理，所以没有做容错处理。
