### ISSUE TITLE
主题定制部分的文档和mand-mobile/mand-mobile-template中实际的主题定制部分不一致。

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#80]
- **Mand Mobile Version**

    "mand-mobile": "^1.0.8",

- **OS Version & Browser Version**

macOS 10.13.4

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

node -v
v8.11.1

- **Recurring Links**

https://didi.github.io/mand-mobile/#/docs/theme

- **Recurring Steps**

https://didi.github.io/mand-mobile/#/docs/theme

- **Expectant Behaviors**

https://didi.github.io/mand-mobile/#/docs/theme
主题定制部分的文档和mand-mobile/mand-mobile-template中实际的主题定制部分不一致。
希望更新文档，按照代码中主题定制的部分，更新步骤。

- **Actual Behaviors**

主题定制部分的文档和mand-mobile/mand-mobile-template中实际的主题定制部分不一致。

**Comment by xxyan0205** [comment]
具体什么不一致，`mand-mobile-template`内也是按照主题定制部分的文档实现的，只不过是对于`mand-mobile-template`的用户无需自己再实现一遍了。

**Comment by snowdream** [comment]
与mand-mobile/mand-mobile-template相比：
1. 文档没有提及util部分。
    stylus: generateLoaders('stylus', {
      import: [config.mand.theme.path]
    }),
    styl: generateLoaders('stylus', {
      import: [config.mand.theme.path]
    })

2. 文档没提交具体怎么应用自定义主题文件。
实例代码main.js中有提到。
import './styles/theme.styl'
import './styles/global.css'
