### ISSUE TITLE
官网demo，页面返回toast不消失

### ISSUE THREAD

**Issue by zlab** [didi/mand-mobile#82]
> 手机体验
1. 微信扫码进入demo，toast页面
2. 随便选择一个，比如loading
3. loading还没关闭的时候点左上角返回
4. 回到demo主页面，loaidng还在

## 问题来了
在执行ajax请求开始的时候，显示了loading，延迟时间设置10秒，也就是ajax超时时间，
服务器或者网络卡了一下，5秒了还没返回结果，用户点了返回，回到上一个页面，loading会一直等到超时才消失

**Comment by zlab** [comment]
问题应该是loading默认挂载在body，vue-router没法控制

**Comment by xxyan0205** [comment]
由此可见，单例模式用起来虽爽，但同时也会带来副作用。

<br>

![20dfbf64d40859ff3fbfa636826da6dc](https://user-images.githubusercontent.com/8409100/40184250-5c671bdc-59b5-11e8-84dc-f8c01a2f400c.jpg)
