### ISSUE TITLE
按照官网教程修改主题样式,报错 ParseError: expected "indent", got ";"

### ISSUE THREAD

**Issue by Nick-Tsao** [didi/mand-mobile#83]
- **Mand Mobile Version**

Mand-ui   1.X
Vue-cli 3.0

- **OS Version & Browser Version**

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

- **Recurring Links**

- **Recurring Steps**

引入theme.custom.styl 无效.
![2018-05-18 3 13 55](https://user-images.githubusercontent.com/31433951/40221145-26905c9a-5aae-11e8-8400-aed98509c04e.png)

编译时报错
![2018-05-18 3 09 21](https://user-images.githubusercontent.com/31433951/40220984-9d57afd2-5aad-11e8-927a-a318381275a6.png)

- **Expectant Behaviors**

通过官网教程成功切换主题.

- **Actual Behaviors**

目前更改源码中lib文件下组件源码,来修改主题

**Comment by xxyan0205** [comment]
theme.custom.styl 有什么内容？

如果是新项目可以使用[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)初始化，内置了自定义主题功能。

**Comment by Nick-Tsao** [comment]
我看一下 mand-mobile-template 这个吧. 现在使用的dev包,修改theme.styl的变量 然后重新打包. 再放进node_modules 包里,能实现功能,比较麻烦.

**Comment by lucker2046** [comment]
@Nick-Tsao 是否可以提供下以下环境的版本，以便于我们还原问题，谢谢
1、npm
2、node
3、stylus
4、stylus-loader

**Comment by Nick-Tsao** [comment]
已经迁移到了 mand-mobile-template  .  怀疑是vue-cli3.0在vue.config.js 中配置webpack 引起的冲突.
