### ISSUE TITLE
[bug-report] DatePicker 组件，自定义 custom-types 问题

### ISSUE THREAD

**Issue by gennng** [didi/mand-mobile#833]
#### Mand Mobile Version
2.6.1            

#### Vue Version
2.4.2       

#### Model / OS & Browser Info
iphone/android       

#### Recurring Steps
    <md-date-picker
      v-model="isDatePickerShow"
      title="选择出险时间"
      :unit-text="['', '', '']"
      :keep-index="true"
      type="custom"
      :custom-types="['dd', 'MM', 'yyyy']"
    ><

#### Expectant Behaviors
选择月份，天数根据月份变化

#### Actual Behaviors
选择月份，天数永远不变

**Comment by qifeng0748** [comment]
> #### Mand Mobile Version
> 2.6.1
> 
> #### Vue Version
> 2.4.2
> 
> #### Model / OS & Browser Info
> iphone/android
> 
> #### Recurring Steps
> ```
> <md-date-picker
>   v-model="isDatePickerShow"
>   title="选择出险时间"
>   :unit-text="['', '', '']"
>   :keep-index="true"
>   type="custom"
>   :custom-types="['dd', 'MM', 'yyyy']"
> ><
> ```
> 
> #### Expectant Behaviors
> 选择月份，天数根据月份变化
> 
> #### Actual Behaviors
> 选择月份，天数永远不变

感谢反馈，目前这个属性存在问题
