### ISSUE TITLE
vue 3引入报错帮忙看下吧

### ISSUE THREAD

**Issue by matianheng** [didi/mand-mobile#845]
WARNING in ./node_modules/.store/mand-mobile@2.6.1/node_modules/mand-mobile/lib/mand-mobile.esm.js 1:201450-201460
export 'default' (imported as 'Vue') was not found in 'vue' (possible exports: BaseTransition, BaseTransitionPropsValidators, Comment, EffectScope, Fragment, KeepAlive, ReactiveEffect, Static, Suspense, Teleport, Text, Transition, TransitionGroup, VueElement, assertNumber, callWithAsyncErrorHandling, callWithErrorHandling, camelize, capitalize, cloneVNode, compatUtils, compile, computed, createApp, createBlock, createCommentVNode, createElementBlock, createElementVNode, createHydrationRenderer, createPropsRestProxy, createRenderer, createSSRApp, createSlots, createStaticVNode, createTextVNode, createVNode, customRef, defineAsyncComponent, defineComponent, defineCustomElement, defineEmits, defineExpose, defineModel, defineOptions, defineProps, defineSSRCustomElement, defineSlots, devtools, effect, effectScope, getCurrentInstance, getCurrentScope, getTransitionRawChildren, guardReactiveProps, h, handleError, hasInjectionContext, hydrate, initCustomFormatter, initDirectivesForSSR, inject, isMemoSame, isProxy, isReactive, isReadonly, isRef, isRuntimeOnly, isShallow, isVNode, markRaw, mergeDefaults, mergeModels, mergeProps, nextTick, normalizeClass, normalizeProps, normalizeStyle, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, openBlock, popScopeId, provide, proxyRefs, pushScopeId, queuePostFlushCb, reactive, readonly, ref, registerRuntimeCompiler, render, renderList, renderSlot, resolveComponent, resolveDirective, resolveDynamicComponent, resolveFilter, resolveTransitionHooks, setBlockTracking, setDevtoolsHook, setTransitionHooks, shallowReactive, shallowReadonly, shallowRef, ssrContextKey, ssrUtils, stop, toDisplayString, toHandlerKey, toHandlers, toRaw, toRef, toRefs, toValue, transformVNodeArgs, triggerRef, unref, useAttrs, useCssModule, useCssVars, useModel, useSSRContext, useSlots, useTransitionState, vModelCheckbox, vModelDynamic, vModelRadio, vModelSelect, vModelText, vShow, version, warn, watch, watchEffect, watchPostEffect, watchSyncEffect, withAsyncContext, withCtx, withDefaults, withDirectives, withKeys, withMemo, withModifiers, withScopeId)
 @ ./node_modules/.store/vue-loader@17.3.1/node_modules/vue-loader/dist/index.js??ruleSet[1].rules[7].use[0]!./src/views/about.vue?vue&type=script&lang=js 2:2-36 7:7-18 7:21-27
 @ ./src/views/about.vue?vue&type=script&lang=js 1:0-174 1:0-174 1:175-338 1:175-338
 @ ./src/views/about.vue 2:0-56 3:0-51 3:0-51 8:49-55
 @ ./src/router/index.js 10:15-51
 @ ./src/index.js 3:0-30 18:8-14

webpack 5.89.0 compiled with 6 warnings in 13447 ms

**Comment by qifeng0748** [comment]
Vue3 版本是这个 https://mand-mobile.github.io/mand-mobile-next/zh-CN/
