### ISSUE TITLE
ActionSheet 包含数据过多,touch无法滚动

### ISSUE THREAD

**Issue by Nick-Tsao** [didi/mand-mobile#86]
- **Mand Mobile Version**

- **OS Version & Browser Version**

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

- **Recurring Links**

- **Recurring Steps**

- **Expectant Behaviors**

ActionSheet 中即使包含很多的行为,也是可以触摸滑动的.

- **Actual Behaviors**

![2018-05-18 7 23 40](https://user-images.githubusercontent.com/31433951/40232357-03efd120-5ad1-11e8-8886-8c14d6e6a289.png)

**Comment by Nick-Tsao** [comment]
md-selector 这个组件也是一样的 当数据过多后. 鼠标滚轮可以滑动,  touch事件无法滑动

**Comment by Nick-Tsao** [comment]
查看源码 发现是 Popup  阻止了滚动默认事件. 但是 这些组件是根据Popup分发出来的.  而且没有提供 prevent-scroll 的参数设置. 期望可以在分发组件中提供 prop   prevent-scroll  的设置

**Comment by xxyan0205** [comment]
增加了`maxHeight`来控制容器最高高度，超出后可滚动

**Comment by Nick-Tsao** [comment]
1.2.3 直接到 1.3.0了嘛?  还是要等很久?
