### ISSUE TITLE
popup 类似组件的 v-model 不支持传vuex getter. 

### ISSUE THREAD

**Issue by Nick-Tsao** [didi/mand-mobile#88]
- **Mand Mobile Version**

- **OS Version & Browser Version**

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

- **Recurring Links**

- **Recurring Steps**

- **Expectant Behaviors**

- **Actual Behaviors**

popup中隐藏视窗是触发this.$emit('input', false),而vuex getter 作为value 不存在setter.

**Comment by xxyan0205** [comment]
不要数据层状态直接绑定到页面子组件上，最好通过页面的数据作为中转去同步子组件的双向绑定和数据层单选数据流转。

**Comment by Nick-Tsao** [comment]
最后通过,监听Getter和中转数据的改变值.来实现的. Thank you.
