### ISSUE TITLE
如何自定义Toast展示位置，比如展示在屏幕底部位置。

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#89]
- **Mand Mobile Version**

    "mand-mobile": "^1.0.8",

- **OS Version & Browser Version**

macOS 10.13.4

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

node -v
v8.11.2

- **Recurring Links**

https://didi.github.io/mand-mobile/#/docs/components/feedback/toast

- **Recurring Steps**

如何自定义Toast展示位置，比如展示在屏幕底部位置。

- **Expectant Behaviors**

如何自定义Toast展示位置，比如展示在屏幕底部位置。

- **Actual Behaviors**

展示在屏幕中部

**Comment by moyus** [comment]
只支持展示在屏幕中间。

**Comment by xxyan0205** [comment]
如果是系统级的提示，比如安卓的再次返回退出，最好使用系统的toast

**Comment by snowdream** [comment]
希望可以支持自定义toast的位置。
