### ISSUE TITLE
如何引入ionicons

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#91]
- **Mand Mobile Version**

"mand-mobile": "^1.0.8",

- **OS Version & Browser Version**

macOS 10.13.4

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

node -v
v8.11.2

- **Recurring Links**

- **Recurring Steps**

https://didi.github.io/mand-mobile/#/docs/components/basic/icon
https://github.com/ionic-team/ionicons
- **Expectant Behaviors**

mand-mobile自带icon太少，请问一下，如何引入ionicons。

- **Actual Behaviors**

**Comment by xxyan0205** [comment]
把你用的到图标svg下载到工程里，比如放到`src/my-project-svg-folder`下，然后按照文档的配置即可。

**Comment by snowdream** [comment]
没有这么简单。ionicons区分ios，android。如果使用ion-前缀引用，则会自动根据平台进行选择。
如果按照文档配置，不知道怎么支持这个特性。

**Comment by xxyan0205** [comment]
只有在运行时是才可以确定ios或者android，就得需要提前将所有可能用到的资源引入进来。这在native里可以，但是在web中就会造成bundle过大。

**Comment by snowdream** [comment]
我的应用场景是cordova+mand-mobile，可以打包ios，android。有什么办法支持这种吗

**Comment by xxyan0205** [comment]
目前只能手动的去做两种图标的引入逻辑，或者直接将mand-mobile源码加入工程加以改造，将逻辑加到Icon中。
```
<md-icon name="iconName"></md-icon>
```
```
import { Icon } from 'mand-mobile'
import 'src/my-project-svg-folder/hello-ios.svg'
import 'src/my-project-svg-folder/hello-android.svg' 

export default {
  components: {
    [Icon.name]: Icon,
  },
  data () {
    return {
      devicePlatform: device.platform
    }
  },
  computed: {
    iconName () {
      return this.devicePlatform === 'ios' ? 'hello-ios' : 'hello-android'
    }
  }
}
```

**Comment by snowdream** [comment]
好的，谢了。
