### ISSUE TITLE
希望支持TitleBar组件。

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#92]
- **Mand Mobile Version**

"mand-mobile": "^1.0.8",

- **OS Version & Browser Version**

macOS 10.13.4

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**

node -v
v8.11.2

- **Recurring Links**

- **Recurring Steps**

https://didi.github.io/mand-mobile/#/docs/introduce

- **Expectant Behaviors**

希望增加标题组件，类似左右两边可以自定义图标，中间可以添加标题文字，同时支持自定义标题背景。

- **Actual Behaviors**

没有类似组件

**Comment by xxyan0205** [comment]
组件库未来可能会更专注金融业务相关的组件，通用类型组件会逐渐减少
