### ISSUE TITLE
Steps步骤条组件，页面里面使用刷新一次样式会变

### ISSUE THREAD

**Issue by jury09** [didi/mand-mobile#94]
- **Mand Mobile Version**
^1.2.1

- **OS Version & Browser Version**
mac os High Sierra Chrome 66.0.3359.181

- **Node Version, Package Management Tool(such as npm/cnpm/yarn) & Version for building errors**
node -v 7.10.1 npm -v 4.2.0

- **Recurring Links**

- **Recurring Steps**
1、 手册中vue2.0 脚手架安装 vue init mand-mobile/mand-mobile-template my-mand-mobile-project
2、  新建vue页面
3、 import { Button, Toast, Steps } from 'mand-mobile'
4、 Vue.component(Steps.name, Steps)
5、 ```<md-steps :steps="steps" :current="currentStep"></md-steps>```

- **Expectant Behaviors**
显示正常的步骤条

- **Actual Behaviors**
收到刷新页面后，步骤条样式失效

![image](https://user-images.githubusercontent.com/2839476/40317498-3eac7a7c-5d54-11e8-8bfb-6093c6cfc4e7.png)

**Comment by remote-star** [comment]
请问在运行demo时是否也会出现类似问题？

**Comment by jury09** [comment]
我怀疑是responsive.js的问题，在我切换大小，跳转路由都会出现样式错位的问题~

**Comment by xxyan0205** [comment]
能否调试下或检查元素看下，引起“条样式失效”的直接原因是什么？是元素classname丢失，或者是有其他报错
