### ISSUE TITLE
为啥我按教程定制样式不生效呢

### ISSUE THREAD

**Issue by yangbys** [didi/mand-mobile#97]
@import '~mand-mobile/components/_style/mixin/util'
@import '~mand-mobile/components/_style/mixin/theme'

// 建议安装并引入css拓展nib
@import '~nib/lib/nib/vendor'
@import '~nib/lib/nib/gradients'

// 覆盖样式变量
color-primary = #1AAD19

**Comment by xxyan0205** [comment]
是否引入的是源码(components目录下)，默认引入的是编译后的代码(lib目录下)。

如果是新项目，可使用[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)初始化，内部已做好了相关配置。

**Comment by snowdream** [comment]
建议参考[mand-mobile-template](https://github.com/mand-mobile/mand-mobile-template)来进行定制样式。

**Comment by qidaneix** [comment]
请问使用vue-cli@3.x版本，该如何配置自定义主题？

**Comment by qidaneix** [comment]
@xxyan0205 你好，再问一个问题：如果自定义主题，可以使用vw/vh的手机屏幕自适应的解决翻案嘛？还是只能用rem？

**Comment by xxyan0205** [comment]
目前还不支持。自定义主题有两种方式，第一种是通过引入源码在编译时，第二种是通过我们提供的调色板产出自定义主题的css。如果要使用vw/vh可以从以上两种方式选择，然后多做一步px转vh vw

**Comment by xxyan0205** [comment]
https://github.com/didi/mand-mobile/blob/master/build/rollup/build-vw-responsive.js  可以参考这个脚本拷过去 改改里面的路径之类

**Comment by qidaneix** [comment]
@xxyan0205 有点迷😵😵😵，请问会推出针对不同的屏幕兼容方案（rem或vw/vh）的自定义主题方式吗？或者更理想一些，屏幕兼容方案也成为自定义主题的一个可配置项？比如在stylus里设置一个变量length-unit，length-unit='rem'时用rem，length-unit='vw'时用vm/vh。
谢谢

**Comment by xxyan0205** [comment]
里面提及到两件事，一个是自定义主题，一个是px转换至vw/vh。两者都是工程化中的编译的工作，只不过前者是靠stylus，后者是靠postcss。所以没法通过stylus增加配置项搞定这两件事。另外调色板工具其实是一个静态页面因为没有服务端资源所以没法做一些编译工作。当时产出包中直接包含vw/vh的版本是考虑尽量减少通用场景的工程化配置，其他场景比如主题定制，单位用px，rem，vw，dp，pt种种这些是应用层工程中的自定义配置。
----

如果上述配置如果觉得有成本，建议可以采用我们提供的vue cli2模板或vue cli3的demo快速初始化一个项目，使用自定义主题+rem的方式，我们也会在将来将自定义主题+vh/vw的场景加入其中。当然更建议和欢迎先学习尝试，如果成功了欢迎给我们提pr。
