### ISSUE TITLE
我再mac上试了几次按需引入都没有UI库的css样式,不知道什么原因

### ISSUE THREAD

**Issue by petersam11** [didi/mand-mobile#98]
我首先是用webpack的模板然后自己配置结果没效果,我以为是自己配置的问题,然后我就直接下载模板vue init mand-mobile/mand-mobile-template my-mand-mobile-project 发现也是不行.我什么都没操作,就把项目跑起来

**Comment by xxyan0205** [comment]
有什么报错么

**Comment by petersam11** [comment]
就有几个依赖自动装不上，然后我手动再装一次就可以了，就没见有报错了，之前项目我也用了这个ui库，不过是window系统，一切正常，现在换了电脑了，就不行了




| |
沈丕豪
邮箱：petersam@yeah.net
|

签名由 网易邮箱大师 定制

在2018年05月23日 18:13，Shawn Xu 写道：

有什么报错么

**Comment by petersam11** [comment]
可以加个微信帮我看下吗？新项目打算用这个




| |
沈丕豪
邮箱：petersam@yeah.net
|

签名由 网易邮箱大师 定制

在2018年05月23日 18:16，petersam11 写道：
就有几个依赖自动装不上，然后我手动再装一次就可以了，就没见有报错了，之前项目我也用了这个ui库，不过是window系统，一切正常，现在换了电脑了，就不行了




| |
沈丕豪
邮箱：petersam@yeah.net
|

签名由 网易邮箱大师 定制

在2018年05月23日 18:13，Shawn Xu 写道：

有什么报错么

**Comment by xxyan0205** [comment]
可以加下Mand Mobile的交流群 493305323

**Comment by MaZhaolin** [comment]
我也遇到了一样的问题，请问解决了吗？
